### ISSUE TITLE
Recursive mkdir hangs when there is no write permission.

### ISSUE THREAD

**Issue by adamczykm** [theophilusx/ssh2-sftp-client#101]

**Comment by theophilusx** [comment]
OK thanks for the report. Will look into it and see if I can reproduce. It is possible the ssh2 module is not returning an error, so the promise never gets resolved.

**Comment by theophilusx** [comment]
Have added tests for explicit case where there is no write permission. Seems to be working with the new code in the development branch (release-4.0.0).
