### ISSUE TITLE
Can't Get Image Base Encoding in SFTP, Pipe works

### ISSUE THREAD

**Issue by ghost** [theophilusx/ssh2-sftp-client#113]
I have a SFTP server running in my local and I'm trying to get a sample image. I'm using [ssh2-sftp-client][1] npm module for this.

The issue is if I pipe the response directly to a writable node stream, it works. But if I try to add up the chunk using `data` event it doesn't work. 

The purpose of this whole process is to get base encoding of an image without downloading the actual file on the server.

Some points which might help you are added as comments in the code.

Any other method is welcome.

**Code**

    let Client = require('ssh2-sftp-client');
    let fs = require('fs');
    let sftp = new Client();
    const btoa = require('btoa');

    sftp.connect({
        host: '*******',
        port: '22',
        username: '******',
        password: '******'
    })
    .then(() => {
        // true is to use compression, i have tried changing both true and false
        // null is to avoid using any encoding
        return sftp.get('Path To My File', true, null);
    }).then((stream) => {
        // stream.pipe(fs.createWriteStream('pipe-image.png')); This is working.
        var fileBuffer = '';
        var i = 0;

        stream.on('data', (chunk) => {
            // data event is coming 4 times in my case
            console.log(i++, chunk.length);
            fileBuffer += btoa(chunk);
        });

        stream.on('end', () => {
            console.log('end');
            fs.writeFileSync('new.png', fileBuffer, {
                encoding: 'base64'
            });
        });

        stream.on('close', data => console.log('close'));
        stream.on('error', data => console.log('error'));
        stream.on('readable', () => console.log('readable'));
    });

**Console Output**
    
    0 65536
    1 65536
    2 65536
    3 51985
    readable
    end
    close

My best guess is that the first `data` event is given partial image (top part) correct but subsequent `data` events are messing up the things.

  [1]: https://www.npmjs.com/package/ssh2-sftp-client

**Comment by theophilusx** [comment]
I'm not sure I understand why you are trying to do both pipe and on('data',....) on same stream at the same time? At any rate, I suspect part of the problem is likely mixing up the two different stream APIs. 

> The purpose of this whole process is to get base encoding of an image without downloading the actual file on the server.

I don't understand this statement. Regardless of weather you use 'data' or pipe, your downloading the file. Are you saying you just want to download part of the file and then stop?

**Comment by theophilusx** [comment]
No response to question for further clarification. Closing issue
