### ISSUE TITLE
sftp.put(localfilepath,remotefilepath) is not working

### ISSUE THREAD

**Issue by eragon11** [theophilusx/ssh2-sftp-client#120]
I got an error.:
errno: -2,
No such file or directory .
filepath: '/batch/reports/*'

MySyntax:    
sftp.connect(config)
.then({}=>{
return sftp.put('/batch/reports/*','/drag/filedone/')
}
.then({data}=>{
console.log(data);
}

**Comment by dimitriy-k** [comment]
@eragon11 I think you can upload only one file with this sftp.put.

I am also looking for a command to upload directory, but looks like default ssh2 client cannot do it.

**Comment by theophilusx** [comment]
No, there is no support for uploading a directory of files. A PR which implements such a feature would probably be welcomed. However, it is fairly trivial to implement this in your own code using fastPut and a loop - could even use Promise.all and create an array of upload promises.

**Comment by theophilusx** [comment]
Probably should add a 'feature' label to this issue.

**Comment by dimitriy-k** [comment]
I use **node-sftp-deploy** to deploy directory

**Comment by theophilusx** [comment]
Fature request in #27
