### ISSUE TITLE
Is v2.5.0 really a latest?

### ISSUE THREAD

**Issue by medikoo** [theophilusx/ssh2-sftp-client#126]
On npm v2.5.0 installs by default as _latest_ version (and it's version shown on front page: https://www.npmjs.com/package/ssh2-sftp-client ) while I also see non-deprecated v3.1.0 being published.

Is that this way it should be?

**Comment by jyu213** [comment]
yes. the lastest version is V2.5.0. 
V3.1.0 is to reslove to node10.x, unfortunately there is a problem with this version.

**Comment by medikoo** [comment]
Ok, thanks for confirmation. It'll be great then to deprecate v3x (or publish with some `-beta` postfix) then it wouldn't b confusing.

**Comment by Saini01Basu** [comment]
Does the V2.5.0 of ssh2-sftp-client work with node10.x?

**Comment by nchase** [comment]
can someone update the version number here in this repo too, to avoid any confusion? (master currently shows `2.4.3`)

**Comment by theophilusx** [comment]
Done.
