### ISSUE TITLE
rename should error if remote path already exists and file is not renamed

### ISSUE THREAD

**Issue by lady3bean** [theophilusx/ssh2-sftp-client#127]
I have noticed that when using rename function, if a file exists that has the same remote path as what I'm trying to rename the source file to, the source file is not renamed. While it makes sense that renaming would fail in this case, if it fails it should throw an error. Other possibility is forcing the rename, e.g. file_name(1), filename(2) and so on, but I think throwing an error here is more intuitive.

**Comment by theophilusx** [comment]
Not sure if changes subsequent to this issue fixed this or what, but I cannot reproduce this. When the tests try to rename a file to a filename which already exists, the promise is rejected with a failure message.
