### ISSUE TITLE
upload without credentials

### ISSUE THREAD

**Issue by piyush94** [theophilusx/ssh2-sftp-client#128]
My node app is running on a server that has password less login to remote servers.
How can i tell sftp to connect without password.

**Comment by KalleVuorjoki** [comment]
I managed to do public key authentication like this: 
```const Client = require('ssh2-sftp-client');

let sftp = new Client();
sftp.connect({
  host: 'YOUR-HOST',
  port: 'YOUR-PORT',
  username: 'YOUR-USERNAME',
  agent: process.env.SSH_AUTH_SOCK
}).then(() => {
  sftp.upload('YOUR-FILE')
}
```

`process.env.SSH_AUTH_SOCK` is your system specific variable, no need to set it in `.env` file.

**Comment by KalleVuorjoki** [comment]
Maybe these basic use cases should be documented in project page...

**Comment by theophilusx** [comment]
You can also used the privateKey property e.g.

````
sftp.connect({
  host: "host.com",
  username: "user",
  privateKey: fs.readFileSync("/path/to/ssh/key")
}).then(.....
```

**Comment by theophilusx** [comment]
Added details/examples to FAQ seciont of readme in release-4.0.0
