### ISSUE TITLE
Please increment major version on breaking changes

### ISSUE THREAD

**Issue by edbrannin** [theophilusx/ssh2-sftp-client#131]
Just an FYI: `2.5.0` quietly broke something because of the `put()` change from `(input, remotePath, useCompression, encoding, otherOptions)` to `(input, remotePath, options)`.

Next time you make a breaking change, could you please update the version like `2.4.3` -> `3.0.0` so npm doesn't think it's a safe upgrade?

**Comment by theophilusx** [comment]
Will be done in all future releases.
