### ISSUE TITLE
How to catpure connection errors in the SFTP read stream

### ISSUE THREAD

**Issue by dvlato** [theophilusx/ssh2-sftp-client#133]
I have some code that can access a number of different network/file resources, including a SFTP server.  This code gets a Stream from any of those different resources and then pipes it doing some processing.  

 Our problem is that for ssh2-sftp-client, if the connection drops the stream does not fail. We have added keepAliveInterval to have an error event when the connection drops, but that event does not make our stream fail.  Are we doing anything incorrectly?  We would like the stream to fail so we can capture the error, is that possible? Otherwise, what would be your recommended approach to make sure the download() method below fails? 
 
Sample pseudocode where client is an abstraction over ssh2 sftpclient (with some other implementations):
  
async download() { 
   await client.connect(params);
   const stream = await client.getReadStream(name);
   return new Promise((resolve, reject) => {
            stream
                .on('error', err => {
                    LOG.error(`Error {err}, Full stack: ${err.}`);
                    reject(err);
                })
                .pipe(unzipper.Parse())...
}

**Comment by theophilusx** [comment]
getREadStream is not part of the ssh2-sftp-client library -0 that is a function from the underlying SSH2 and SSH2 sftp-streams libraries, which do not use promises. The ssh2-sftp-client library is a convenience library that just uses these other underlying libraries, wraps some useful extensions as promises etc. If you want to interact directly using streams, you are probably better off just using the underlying libraries directly.  Alternatively, use the get method, passing it a writeable stream (which could be for example a zlib unzip stream). It will return a promise that is either resolved or rejected if there is an error.
