### ISSUE TITLE
Configure to open/write with sudo?

### ISSUE THREAD

**Issue by ChandrashekarBemagoni** [theophilusx/ssh2-sftp-client#137]
I have access to a remote system with a given user (not root).
Usually from the putty/terminal when I logged in/ SSH session after getting sudo su -  i can able get read and write permission folder and I would like to have the same feature, passing sudo su -. But sadly,  we dont have such option

Would it be possible to include a "sudo" option in the configuration which will kind of run any read/write operation with sudo?

**Comment by theophilusx** [comment]
I think this is outside the responsibility of this library. Even if we wanted to implement this, it would not be possible as this library is restricted to the facilities provided by the SSH2 library that it uses.
