### ISSUE TITLE
Directory listing issue with sftp.list

### ISSUE THREAD

**Issue by nikitamiro** [theophilusx/ssh2-sftp-client#14]
The return sftp.list('/pathname'); command just returns a #<Promise> and nothing else. If returned, the value is just Promise { <pending> }. I put the file directly to the main directory of the server, so the request looks like: 
`sftp.put('C:\\Homeware\\Test_folder\\test_file.csv','test_file.csv');`

The list request is: 
`sftp.list('//');`

What are your thoughts?
As you can see, the test_file.csv is saved at the <root>, so the list command should just look at there, 
i.e. `'/ <root>'`.

**Comment by jyu213** [comment]
@nmirosh , is also a problem?
