### ISSUE TITLE
question: how to pass writable stream as dst for get method?

### ISSUE THREAD

**Issue by lady3bean** [theophilusx/ssh2-sftp-client#142]
[Since the update](https://github.com/jyu213/ssh2-sftp-client/commit/a640cc119c7875ac5820109466e09d846f2ecc36) introducing the new options for the `get` method as described in the readme, https://github.com/jyu213/ssh2-sftp-client#getsrcpath-dst-options, the file stream seems to have no data. Could you please provide an example of how to pass a writable stream as the destination? I've tried the below, which does return a stream, but its length is empty. Also tried using the default buffer option, which also resulted in no data.

On version 2.4.3, not specifying any options, this was not a problem, though I was having the same issue as discussed here, which is why I was trying out the patch for Node 10x.

```
const Writable = require("stream").Writable;
const ws = Writable();
ws._write = function(chunk, enc, next) {
   console.dir(chunk);
   next();
};

return sftp.get(config.fileDownloadDir + file.name, ws, {
   encoding: "utf-8",
   highWaterMark: 65535,
   autoClose: true
 });
```
(sftp is the ssh2 sftp client)

**Comment by theophilusx** [comment]
Have a look at the code in the test directory - it should give you enough to get you started.

**Comment by wtflove** [comment]
@lady3bean Do you have a solution to this issue? Many thanks.

**Comment by theophilusx** [comment]
Below is a very simple example. It will retrieve a file from the remote server, convert it to all upper case and save it to a local file.  It shows how to pass a writeable into the get method and how that writeable can be piped into another writeable. I've used this technique where the middle writeable is a zlib gunzip writeable, which will uncompress compressed files as they are transferred. 

```javascript
'use strict';

// Example of using a writeable with get to retrieve a file.
// This code will read the remote file, convert all characters to upper case
// and then save it to a local file

const Client = require('../src/index.js');
const path = require('path');
const fs = require('fs');
const through = require('through2');

const config = {
  host: 'arch-vbox',
  port: 22,
  username: 'tim',
  password: 'xxxx'
};

const sftp = new Client();
const remoteDir = '/home/tim/testServer';

function toupper() {
  return through(function(buf, enc, next) {
    next(null, buf.toString().toUpperCase());
  });
}

sftp
  .connect(config)
  .then(() => {
    return sftp.list(remoteDir);
  })
  .then(data => {
    // list of files in testServer
    console.dir(data);
    let remoteFile = path.join(remoteDir, 'test.txt');
    let upperWtr = toupper();
    let fileWtr = fs.createWriteStream(path.join(__dirname, 'loud-text.txt'));
    upperWtr.pipe(fileWtr);
    return sftp.get(remoteFile, upperWtr);
  })
  .then(() => {
    return sftp.end();
  })
  .catch(err => {
    console.error(err.message);
  });
```

**Comment by theophilusx** [comment]
Added example to FAQ section of README.
