### ISSUE TITLE
Not working with Node v10.x. Not connecting, also not throwing any error

### ISSUE THREAD

**Issue by Saini01Basu** [theophilusx/ssh2-sftp-client#144]
None of the versions of ssh2-sftp-client are working with Node v10.x. Not connecting, also not throwing any error

**Comment by Saini01Basu** [comment]
I have node v10.15.3. I tried with ssh2-sftp-client v2.5.0, v3.0.0, v2.3.0, v2.2.0. None of them connects to sftp server also the catch block is not catching any errors.

**Comment by Saini01Basu** [comment]
@jyu213 Could you please help me understand where I am going wrong?

**Comment by theophilusx** [comment]
I've been using this library with node 10.x for the past 5 months with no problems. Perhaps post your code?

**Comment by theophilusx** [comment]
Added additional tests for connections. No errors in current dev version with Node 10.x.
