### ISSUE TITLE
Unable to retrieve files from folders other than 'Input'

### ISSUE THREAD

**Issue by pkdhara95** [theophilusx/ssh2-sftp-client#149]
I am trying to retrieve the files from 'Preprocessed' folder but unable to do the same. If I give the path as '/' it gives me the files of Input folder. So how can I retrieve the files from other folders i.e. 'Preprocessed'. I have tried with '../' but gives error 'The file path does not exists '. I am attaching the screenshot of folder structure for the same.   
![Screenshot from 2019-06-19 10-42-55](https://user-images.githubusercontent.com/51983594/59738948-b2846100-9280-11e9-91ca-422db5cfdab3.png)

**Comment by theophilusx** [comment]
This sounds like a sftp server issue. Can you access the folder/files with another sftp client?
