### ISSUE TITLE
TypeError: .pipe is not a function

### ISSUE THREAD

**Issue by wtflove** [theophilusx/ssh2-sftp-client#153]
Trying to download files from a remote SFTP folder to local.

I know sftp.get returns a Promise with readableStream but the error said .pipe is a not function.

Many thanks to you.

Below is the error message and the code:

```
TypeError: stream.pipe is not a function
    at sftp.get.then (D:\GitHub\siemens_edi\ftp-download.js:24:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```javascript
let Client = require('ssh2-sftp-client')
let fs = require('fs')
let sftp = new Client()

const remoteRootPath = '/path/to/remote'
const localRootPath = '/path/to/local'

sftp.connect({
    host: '',
    port: '22',
    username: '',
    password: ''
}).then(() => {
    return sftp.list(remoteRootPath)
}).then((data) => {
    for (var i = 0; i < 10; i++) {
        var localFileName = localRootPath + '/' + data[i].name
        var remoteFileName = remoteRootPath + '/' + data[i].name

        sftp.get(remoteFileName).then((stream) => {
            stream.pipe(fs.createWriteStream(localFileName))
        }).catch((error) => {
            sftp.end()
            console.log(error)
        })
    }

}).catch((error) => {
    sftp.end()
    console.log(error)
})
```

**Comment by AoiYamada** [comment]
According to the doc
> get(srcPath, dst, options)
> dst: If undefined, the remote file will be read into a Buffer and the buffer returned.

I think it returns buffer
`
sftp.get(remoteFileName).then(buffer => {
   // code to handle buffer
})
`

I want to get a readable stream but get a buffer :(

**Comment by ganarajpr** [comment]
The problem is with a dependency of ssh2-sftp-client. 

concat - does not work with node10. 

We have fixed this temporarily by creating a fork of this library: Basically all it does is, in the lines below.

https://github.com/jyu213/ssh2-sftp-client/blob/master/src/index.js#L218

We replace this: 

```
        if (dst === undefined) {
          // no dst specified, return buffer of data
          let concatStream = concat(buff => {
            return resolve(buff);
          });
          rdr.pipe(concatStream);
        } 

```
with this:

```
        if (dst === undefined) {
              return resolve(rdr);
        } 

```

I know this is not a backward compatible change. But this works for us.

**Comment by theophilusx** [comment]
@wtflove  you are using the API incorrectly. If you call get() withonly one argument, the remote file path, it returns a buffer, not a stream. If you call it with a second argument that is a string, it will assume it is a local file path and will write the file to that location. if you call it with a writeable stream, it will pipe the data to that stream. If you want to do additional processing of the stream, for example to decompress the data, you can pipe the writeable you pass in to something like zlib. For example

```
  const src = path.join(srcPath, fileName);
  const dst = path.join(dstPath, dstName);
  const gunzip = zlib.createGunzip();
  const out = fs.createWriteStream(dst, {
    flags: "w",
    encoding: null
  });

  gunzip.pipe(out);
  return client
    .get(src, gunzip)
    .then(() => {
      return "file transferred and unzipped";
    })
   .catch(err => {
     console.error(err.message);
  })
```

**Comment by theophilusx** [comment]
@AoiYamada The problem is you cannot just return the readable stream because of the way Promises work. However, what you can do is pass in a writeable stream and then pipe that to whatever you want as that will create a readable stream at your end you can do whatever you want with. See gunzip example above.

**Comment by theophilusx** [comment]
Extend documentation with examples to assist in use of module API
