### ISSUE TITLE
What version of ssh2-sftp-client works with node 10.x?

### ISSUE THREAD

**Issue by salerak** [theophilusx/ssh2-sftp-client#154]
Are there plans to release a version soon compatible with node 10.x.x? @jyu213

**Comment by theophilusx** [comment]
I've been using the current version (2.5.0) in a Node 10.x environment for the past 6 months with no issues. While there are a number of outstanding issues to be addressed, none of them appear to be specific to Node 10.x. Issues with Node 10.x reported previously were addressed in the last release (March 2019)
