### ISSUE TITLE
Add a mkdirp function

### ISSUE THREAD

**Issue by switz** [theophilusx/ssh2-sftp-client#155]
Would be nice to have

`mkdir -p` (create a directory if one doesn't exist)

At the moment, one would have to `list` a directory, see if the subdir exists and if not create it.

**Comment by theophilusx** [comment]
You can set the recursive parameter to true and mkdir will create all the directories which do not exist in the supplied path i.e.

```javascript
    sftp.mkdir('/d1/d2/d3', true);
```

will create d1, d2 and d3 if they do not exist.

**Comment by switz** [comment]
Yes but won’t it overwrite any directories that currently exist?

**Comment by theophilusx** [comment]
No. There really isn't any such thing as over writing a directory. If you try to create a directory which already exists, the operation just fails. However, this is not an issue as the recursive flag really just tells the command to create the directory if it does not exist. If it exists, it does nothing. 

The command takes the supplied path and looks at the first directory. If it doesn't exist, then it knows all the following directories in the path need to be made,  so it does that. If the first directory exists, it looks at the next one and if it does not exist, creates it and all the following directories. If it does exist, it then looks at the next directory etc etc until the last directory - essentially, recursively travel down the directory path until it reaches the last one, creating directories if they don't exist.

**Comment by theophilusx** [comment]
Expanded documentation in README to make purpose of recursive flag clearer
