### ISSUE TITLE
mkdir hangs for no reason

### ISSUE THREAD

**Issue by kishor1221** [theophilusx/ssh2-sftp-client#157]
mkdir hangs for no reason, when we pass a directory name "xyz". Could you please tell me if i am doing something wrong over here?
await sftp.mkdir('xyz/hh', true);

**Comment by kishor1221** [comment]
Could you please tell me if i am doing something wrong over here? 
await sftp.mkdir('xyz/hh', true);

**Comment by theophilusx** [comment]
My guess would be the 'relative' path you have set. However, is should not just hang, so that needs to be investigated. Anyway, try using a full path. I will invetigate fuirther.

**Comment by theophilusx** [comment]
Fixed in version 4.0.3, which has just been published to npmjs
