### ISSUE TITLE
What's breaking in @3 and @4?

### ISSUE THREAD

**Issue by piotr-s-brainhub** [theophilusx/ssh2-sftp-client#158]
What's breaking in `ssh2-sftp-client@3` and `ssh2-sftp-client@4`?

I cannot find anything on https://github.com/theophilusx/ssh2-sftp-client/releases but if nothing is breaking, why the major version is updated?

**Comment by theophilusx** [comment]
Version 3 was a failed release that was deprecated quite some time ago (before my time).  Version 2.5 should have been released as version 4.0.0 as it had major API changes. This was not done. Version 4.0.0 is a major bug fix (see closed issues for details) and some minor API changes which are not backward compatible (documented in the README) as well as removal of support for Node < 8.x Version 4.x also marks the change in owner/maintainer for this package. 

The main breaking changes in 4.x are

- Deprecation of auxList()
- Removal of connectMethod in connect()
- Removal of permissions property in object returned by stat()
= Addition of filter argument to list()

All of the above is documented in the README under the heading "Breaking Changes in Version 4.0.0".

**Comment by piotr-s-brainhub** [comment]
thanks
