### ISSUE TITLE
Unable to do a Get after List

### ISSUE THREAD

**Issue by ngky** [theophilusx/ssh2-sftp-client#163]
I am trying to do first the "client.list" follow by "client.get" operation. "client.get" does not work. I am getting a zero byte file in the dest dir.

However, if I reverse the order, first do the "client.get" then "client.list", it is successful. What did I do wrong. Thank you. 

**Declaration code**
let Client = require('ssh2-sftp-client')
let client = new Client()
const config = {
          host: 'XXXXXXXXX',
          port: '1022',
          username: 'XXXXXXX',
          password: 'XXXXXXX',
          retries: 3
}

**This code is working**
client.connect(config) 
.then(() => {
  client.get("/OUT/SPH/PROCESSED/IFSS_2108.txt22-08-2019-19:56", "/tmp/IFSS_2108.txt22-08-2019-19:56888")
  list = client.list(remotePath, "ifs*")
  return(list)
}) 

**Dir listing**
ngky@instance-1:~$ ls -l /tmp/IF*
-rw-r--r-- 1 ngky ngky 786432 Sep 16 07:37 /tmp/IFSS_2108.txt22-08-2019-19:56888

**This code is NOT working. the file is zero byte**
client.connect(config) 
.then(() => {
  list = client.list(remotePath, "ifs*")
  client.get("/OUT/SPH/PROCESSED/IFSS_2108.txt22-08-2019-19:56", "/tmp/IFSS_2108.txt22-08-2019-19:56888")
  return(list)
}) 

**Dir listing**
ngky@instance-1:~$ ls -l /tmp/IF*
-rw-r--r-- 1 ngky ngky 0 Sep 16 07:38 /tmp/IFSS_2108.txt22-08-2019-19:56888

**Comment by theophilusx** [comment]
The problem is in the way you have your code structured. All of the commands return a promise and you are not waiting for the promise to resolve correctly in the second call. What you want is something like

````
client.connect(config)
.then(() => {
  return client.list(...);
})
.then(listing => {
  console.log(listing);
  return client.get(src, dst);
.then(() => {
  console.log('file downloaded');
})
.catch(err => {
  console.error(err.message);
});
```

Alternatively, you could use async/await e.g.

```
async my-work() {
  await client.connect(config);
  let listing = await connect.list(...);
  await client.get(...);
}

my-work()
.catch(err => {
  console.error(err.message);
})
```

**Comment by ngky** [comment]
Thanks alot Tim. I managed to get it working. This is the working code.

`let Client = require('ssh2-sftp-client');
let client = new Client();
  
const config = {
          host: 'XXXXXX',
          port: '1022',
          username: 'XXXXX',
          password: 'XXXXX',
          retries: 3
}; 

let remotePath = '/OUT/SPH/PROCESSED/';
let localPath = '/tmp/'; 

client.connect(config) 
.then(() => {
  return client.list(remotePath); 
}) 
.then((listing) => {
  console.log("Remote dir listing");
  console.log(listing);
  return client.get("/OUT/SPH/PROCESSED/IFSS_2108.txt22-08-2019-19:56", "/tmp/IFSS_2108.txt22-08-2019-19:56888")
}) 
.then(() => {
  console.log("File downloaded");
  return client.end();
})
.catch(err => {
  console.error(err.message);    
  return(err.message);
})`

**Comment by theophilusx** [comment]
Glad you got it working. Thanks for posting an example of your working code. This helps others a lot.
