### ISSUE TITLE
how to watch for files while connected?

### ISSUE THREAD

**Issue by parkbroom** [theophilusx/ssh2-sftp-client#166]
is it possible to use fs.watch to watch for file changes in the directory?

Thanks

**Comment by theophilusx** [comment]
no. There is nothing like fs.watch in the ssh2 module this module uses for connecting to the remote server, so you would need to roll your own version using list() and comparing results from last call with current call etc.  Main challenge will likely be dealing with network failures (depending on where the remote side is) and what time resolution you want (i.e. how soon after a change and how quickly does the remote side change). The other problem is knowing what the change means - for example, if it is a large file and it is being updated by another process over a slow network, how do you know when the change is complete i.e. all data written? (I've managed something similar using last modified times, but you need to ensure you allow a large enough 'gap'). .
