### ISSUE TITLE
SSH2 module fails to throw error when connection ended prematurely by remote server

### ISSUE THREAD

**Issue by theophilusx** [theophilusx/ssh2-sftp-client#169]
Looking more like this may be a known issue in the ssh2 module. See [Issue #610 ](https://github.com/mscdex/ssh2/issues/610)

_Originally posted by @theophilusx in https://github.com/theophilusx/ssh2-sftp-client/issues/168#issuecomment-533777576_

**Comment by theophilusx** [comment]
See https://github.com/mscdex/ssh2/issues/610

**Comment by stheine** [comment]
I guess this is the same issue here, right?

```
Unhandled exception Error: : Connection ended unexpectedly
    at formatError (/app/node_modules/ssh2-sftp-client/src/index.js:58:10)
    at Client.<anonymous> (/app/node_modules/ssh2-sftp-client/src/index.js:90:13)
    at Client.emit (events.js:209:13)
    at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:312:10)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

in my case, that is intermittently happening in the `list()` method. and since it's not properly rejecting the promise, my application goes down due to this unhandled exception.

**Comment by theophilusx** [comment]
That does look like it might be the same error. However, the connect()
promise should be rejecting this rather than it being unhandled.

Can you provide some code which reproduces this so I can see why it
isn't being handled?

thanks.


stheine <notifications@github.com> writes:

> I guess this is the same issue here, right?
>
> ```
> Unhandled exception Error: : Connection ended unexpectedly
>     at formatError (/app/node_modules/ssh2-sftp-client/src/index.js:58:10)
>     at Client.<anonymous> (/app/node_modules/ssh2-sftp-client/src/index.js:90:13)
>     at Client.emit (events.js:209:13)
>     at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:312:10)
>     at Socket.emit (events.js:214:15)
>     at endReadableNT (_stream_readable.js:1178:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> ```
>
> in my case, that is intermittently happening in the `list()` method. and since it's not properly rejecting the promise, my application goes down due to this unhandled exception.


-- 
Tim Cross

**Comment by stheine** [comment]
I wasn't able to reproduce it, it seemed intermittent, as I couldn't related it to any user activity happening at the same time.
but then I also realized that I missed the `end()` method in my code - so I added that - and since then I haven't see that error.
could that error happen, a while after the last successful action (that's why I couldn't relate it to any activity), if there's no call to `end()`? could that behavior have changed with a recent update, because I had missed that `end()` call always, but just experienced the error since yesterday, when I had upgraded 4.1.0 to 4.2.0?

**Comment by theophilusx** [comment]
Thinking about this a little more, I suspect this is a slightly
different problem.

The original issue was occurring when the remote server would just drop
the network connection during the initial connect() call. What you
appear to be seeing is lost network connections after the connection has
been made and you have an authenticated connection. This is typically a
sign of some sort of intermittent network failure between your client
and the remote server.

If this is occurring during a list() call, it should be resulting in the
list() Promise being rejected. Have you got a .catch() associated with
the list() i.e.

```js
client.connect()
.then(() => {
  return client.list(..);
})
.then(data => {
  ....
}}
.catch(err => {
  ....
});
```

or using a try/catch block if doing the async/await style? Also, make
sure, if your using the .then/.catch chain that any client calls are
done as part of explicit return statements (like the list() call
above). If you don't make the new call as part of the return statement,
it will kick off a new Promise chain and will be outside your current
chain, so your .catch() will not catch it and you will get the uuncaught
exception problem.

If you have all of the above and you still cannot catch the error, I
would be very interested in a short test case. By definition, this sort
of intermittent error is difficult to test/reproduce and there is always
a possibility I've missed some edge case. In the meantime, the other
think you can try is adding a custom error listener using the
client.on() method, which should allow you to catch this error and do
something more 'graceful' than just bombing out.

BTW: what platform is this on? Linux, macOS or Windows?

**Comment by theophilusx** [comment]
OK, yep I think I know what was probably going on.

Without the end() call, eventually, the remote server will end the
connection due to inactivity (i.e. timeout). This will generate an 'end'
event, which will cause ssh2-sftp-client to throw an exception. As your
not in any promise chain at that time (i.e. your list() call has
resolved successfully), there is nothing to catch the error.

This is a change as a result of the work-around to deal with the issue
of ssh2 just sending an end event without an error event if the
connection is ended during the initial connect stage. Previously,
ssh2-sftp-client did not listen for end events as it assumed an error
would be associated with an end event if that end event occurred outside
an expected flow (i.e. you would expect an 'end' event when you call
end() or when authebntication fails and the server closes the
connection). Now we listen for both error and end events because we now
know that 'end' events are raised without accompanying 'error' events
even though, from a client perspective, these are probably 'errors'. 

Previously, the module did not respond to end events, so when you forgot
to call end() and the connection timed out, it would silently end.

**Comment by stheine** [comment]
ok, thanks for that explanation.
after adding the missing `end()` I'm fine now.

**Comment by theophilusx** [comment]
The new error handling in the latest version appears to have resolved this issue, so closing it.
