### ISSUE TITLE
mkdir throwing exception for multiple folder creation scenario.

### ISSUE THREAD

**Issue by MdAbdulSamadBaig** [theophilusx/ssh2-sftp-client#170]

**Comment by theophilusx** [comment]
There is no where near enough information for this to be considered an issue. At a minimum you need to provide

- node version
- platform
- module version
- example code which reproduces the issue.

**Comment by MdAbdulSamadBaig** [comment]
Code is giving error when executed on below environment..

**Node version** — v10.15.3
**Platform** — OS platform
**module version** — "ssh2-sftp-client": "^4.0.3"

**Sample code**

const Client = require('ssh2-sftp-client');
const log = require('../logger');

const sftp = new Client();
sftp.connect({
  host: <sftpHost>,
  port: <port>,
  username: <userName>,
  password: <password>,
}).then(() => sftp.mkdir('/repo3/abc1/abc2', true)).catch((err) => {
  log.error(err, 'catch error');
});


  **Error**: sftp.mkdir: Failed to create directory

**Comment by theophilusx** [comment]
OK. I'll try to see if I can reproduce.

You should try the latest version (4.1.0).

To eliminate server issues, make sure you can execute the same command
using just a plain sftp CLI client (like opnessh client). .

Also, what platform - OS Platform doesn't tell me (Linux, Windows,
macOS)?

MdAbdulSamadBaig <notifications@github.com> writes:

> Code is giving error when executed on below environment..
>
> **Node version** — v10.15.3
> **Platform** — OS platform
> **module version** — "ssh2-sftp-client": "^4.0.3"
>
> **Sample code**
>
> const Client = require('ssh2-sftp-client');
> const log = require('../logger');
>
> const sftp = new Client();
> sftp.connect({
>   host: <sftpHost>,
>   port: <port>,
>   username: <userName>,
>   password: <password>,
> }).then(() => sftp.mkdir('/repo3/abc1/abc2', true)).catch((err) => {
>   log.error(err, 'catch error');
> });
>
>
>   **Error**: sftp.mkdir: Failed to create directory


-- 
Tim Cross

**Comment by theophilusx** [comment]
Using the below script, I cannot reproduce this error on either Linux or macOS using either node 10.15.3 or node 10.16.3. 

```js
'use strict';

// sample mkdir use

const dotenvPath = __dirname + '/../.env';

require('dotenv').config({path: dotenvPath});

const Client = require('../src/index');

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22
};

const path = '/tmp/testing/abc1/abc2';

let client = new Client();

client
  .connect(config)
  .then(() => {
    console.log('Connected. Check if dir already exists');
    return client.exists(path);
  })
  .then(alreadyExists => {
    if (alreadyExists) {
      console.log(`Path ${path} already exists!`);
      return false;
    } else {
      console.log('Making directory');
      return client.mkdir(path, true);
    }
  })
  .then(rslt => {
    console.log(`Result: ${rslt}`);
    return client.end();
  })
  .catch(err => {
    console.log(`Error: ${err.message}`);
  });
```
