### ISSUE TITLE
posix rename

### ISSUE THREAD

**Issue by thomascolibert** [theophilusx/ssh2-sftp-client#173]
Hello,

I'm using ssh2-sftp-client v4.2.0.
When doing a "rename", it fails if the target path already exists, which is compliant with the sftp protocol. But, does your module support the "posix rename" extension ? If yes, how can I enable it ? otherwise, have you planned to support it ?

Thanks & regards,
Thomas

**Comment by theophilusx** [comment]
This is really a question for the [ssh2-streams](https://github.com/mscdex/ssh2-streams/issues) maintainer as this module just uses ssh2-streams to implement the rename functionality. 

The limiting factor here is likely to be the capabilities of node. These modules are all pure Javascript modules, with no native code extensions. Therefore, the low level file system capabilities are all restricted to what node provides in the 'fs' module.

**Comment by jhorbulyk** [comment]
[`ssh2-streams` now supports client side *posix rename*](https://github.com/mscdex/ssh2-streams/issues/152)
