### ISSUE TITLE
get and rename fails with CoreFTP Server over SFTP

### ISSUE THREAD

**Issue by lambia** [theophilusx/ssh2-sftp-client#176]
We encountered issues while trying to get or rename files on a CoreFTP Server.
After successfully connected to the server, we retrieve the files list using "list" function, but when we try to use any other method on it (such as _get_, _rename_ or even _exists_) we receive a "no such file" or "file does not exist" error.
We tried to pass the same path returned from "list", and even to use "realPath", with no result.
Is there any known issue with this server?

Thanks, Luca.

**Comment by theophilusx** [comment]
This is likely related to the path issue identified in #174 . Try using the windows-path--fix branch and see if that fixes the issue.

**Comment by theophilusx** [comment]
Version 4.2.1 released which should have fixed this issue
