### ISSUE TITLE
get method with writeStream from fs doesn't save entire ZIP file

### ISSUE THREAD

**Issue by jbgrunewald** [theophilusx/ssh2-sftp-client#182]
Greetings, 

Perhaps it's a mistake on my end but my understanding of the get method is that I should be able to pass a write stream into the method and pass the contents of the file along from the remote server. When I do this with a passthrough stream I don't have any issues, however when I try to save a ZIP file to disk using a write stream creating from the fs library, the file is missing 65536 bytes of data, or two chunks of data from the buffer. Any idea why this might be the case?

I was able to use the fastget function to download the zip file contents without issue. So I'm wondering if there's something I'm not doing when creating the writestream from the fs library.

**Comment by theophilusx** [comment]
I do this regularly and it is even included as one of the tests for the package, so my suspicion is there is something wrong in your code. Generate a minimal example and post it and I'll see if I can spot the issue. Don't forget to say what platform and version of node and ssh2-sftp-client you are using.

**Comment by theophilusx** [comment]
OK, if that is an accurate reflection of your actual code, the problem is you have no await on the get() function. As a result, your code will exit before the transfer has completed.  Due to the way the Promises are setup, you also don't need to add an end listener. So your code could be

```
const load = async ({
        host, port, username, password, filePath,
      }) => {
        const sftp = new SftpClient();
        await sftp.connect({
          host, port, username, password,
        });
        const writePath = 'some/sort/of/path
        const fileStream = fs.createwritestream(writepath)
        await sftp.get(filePath, fileStream);
        await sftp.end();
        // do something with downloaded file. 
      }
```

In the case where you want to do additional processing to the data as it is transferred, then the pip() method is what you want. For example (pseudo code - not tests) the following will unzip a .gz file and store the result in 'some/sort/of/path' (though paths should start with '/', './' or '../' to avoid ambiguity). 

```
const load = async ({
        host, port, username, password, filePath,
      }) => {
        const sftp = new SftpClient();
        await sftp.connect({
          host, port, username, password,
        });
        const writePath = 'some/sort/of/path;
        const fileStream = fs.createwritestream(writepath);
        const gunzip = zlib.createGunzip();
        gunzip.pipe(fileStream);
        await sftp.get(filePath, gunzip);
        await sftp.end();
        // do something with downloaded file. 
      }
```

**Comment by jbgrunewald** [comment]
Ok, let me try it out. I did experiment with using an await for the sftp.get() call previously, but I did have the sftp.end() inside the 'end' event callback. I'm still not clear why I shouldn't be able to return the fileStream in this case and wait on the 'end' event to be called. When the 'end' event is called, shouldn't the entire contents of the file have been written by the sftp.get() call?

In my case I can't do additional processing while the file is being transferred by piping into . I'm working with an actual .zip, not a gzipped filed. So I needed to download the file completely, then decompress and evaluate the directory contents before doing further processing.

**Comment by theophilusx** [comment]
The problem with not having an await on the get() is that the script may exit before the end listener fires. 

You can use an end listener to do stuff if you want, but ensure you have an await on the get() and an await on the end(). If you really want to put the end() in the listener, you can do that, but don't forget to define the listener as async. 

Personally, I think adding the listener just makes the code less clear and has no processing benefit. Once get() has completed successfully, you know the file has been transferred and can start doing whatever you want to do next. There is no reason to do this in a listener. 

I would recommend putting it all inside a try/catch as there is a chance you will have errors (i.e. network errors). I will often do 

```
try {
  client = new Client();
  await client.connect(...);
  await client.get(....);
  // use downloaded data
} catch (err) {
  console.log(err.message);
} finally {
  await client.end();
}
```

**Comment by jbgrunewald** [comment]
I would agree if my only goal was to download files to disk. Where I'm using this, the API is to return the stream, and before having to handle .zip files I was passing a passthrough stream to the sftp.get() call and returning the passthrough stream from my method to do other processing on the data by piping into various transforms.

How useful is the stream if I'm using an await on the get() call? What event is the get call waiting for to resolve the promise?

**Comment by theophilusx** [comment]
If you look at my gunzip example, you can replace that with whatever processing/transforming you want. All the createGunzip() method does is return a  processing stream which pipes its output to a file writeStream - it could be any stream object which will receive the data from a pipe and then do whatever you want. 

The get() method creates a readStream from the remote server linked to the remote file target and pipes that data into whatever stream you have passed in. The promise is resolved when the passed in stream emits a finish event.

**Comment by jbgrunewald** [comment]
I think I see where my mistake is now. Since I'm passing in a writestream I should be waiting for a 'finish' event, which indicates that the data has been flushed and written from the buffer. It seems the 'end' event is when the writing has completed. Let me test if this fixes my issue.

**Comment by theophilusx** [comment]
Yes, that could be it. As I understand it, the main difference between 'end' and 'finish' is that finish is raised once the buffers have been flushed. The 'end' is raised once the writing has ended, but possibly before all buffers have been flushed.

If it still doesn't work, try to create a minimal example of what your doing and I'll have a look when I get a chance (will take a few days as I've got a deadline looming on another contract and as Douglas Adams said - I love deadlines. I love the wooshing sound they make as they go past!). Would be good to know what node version and platform your using as well.

**Comment by theophilusx** [comment]
Is this resolved and can it be closed?

**Comment by jbgrunewald** [comment]
Yes, I think we can resolve this. I haven’t found the time to verify, but I’m convince it was that I waited for the wrong event. Thanks.
