### ISSUE TITLE
Is the node module multi tenant capable ?

### ISSUE THREAD

**Issue by apasrini** [theophilusx/ssh2-sftp-client#183]
Wanna know if the node module is capable of working in multi tenant environment. Wanted to understand if data isolation ability is present

**Comment by theophilusx** [comment]
I guess that would depend on your definition of multi-tenant. If you are using a model which is based on node's cluster module, then provided the client is created inside the child process and not the parent process, then all should be fine. If on the other hand, each tenant runs its own separate node process, then you hae completely separate execution contexts, so no issue.
