### ISSUE TITLE
Wrong type for get method in @types

### ISSUE THREAD

**Issue by CU-Sam** [theophilusx/ssh2-sftp-client#189]
Hi

In the @types node_modules\@types\ssh2-sftp-client\index.d.ts the dst param of the get method is declared as string or NodeJS.ReadableStream but it shoud be NodeJS.WriteableStream. The code insde (and your documentation) process this var as à WriateableStream and not a ReadeableStream.

This results as a syntax error when specifying @ts-check

Thanks

**Comment by theophilusx** [comment]
I don't have anything to do with the @types/ssh2-sftp-client
module. This is something someone else has put together. You will need
to raise an issue against that module. 

The ssh2-sftp-client documentation should be made a little
clearer with respect to the parameter. In fact, all that is required is
that the 2nd argument is either a string (specifying a file path) or a
stream object which supports the pipe() method. While this will often be
a Writeable stream, it could also be a Readable stream, so really, the
ts definition should specify that it needs to be a stream object which
supports data being passed in via pipe(). 


CU-Sam <notifications@github.com> writes:

> Hi
>
> In the @types node_modules\@types\ssh2-sftp-client\index.d.ts the dst param of the get method is declared as string or NodeJS.ReadableStream but it shoud be NodeJS.WriteableStream. The code insde (and your documentation) process this var as à WriateableStream and not a ReadeableStream.
>
> This results as a syntax error when specifying @ts-check
>
> Thanks


-- 
Tim Cross

**Comment by CU-Sam** [comment]
Okay, thank you for this answer. I dont know who generates this file (@types)... Weird...
