### ISSUE TITLE
Support for tilde (~) in paths

### ISSUE THREAD

**Issue by jhorbulyk** [theophilusx/ssh2-sftp-client#191]
Consider a filename of `~/sample.file` executed on an SFTP server/user combination where the home directory for the authenticated user is `/home/myuser/`.  When I perform `.exists('~/sample.file')` I would expect that the file that the test is performed against is `/home/myuser/sample.file`.  However in reality the test is performed against `/home/myuser/~/sample.file`.  This isn't necessarily what I was expecting but it is hard to see how to otherwise handle operations on files in the `~` directory of the home/working directory.  Is the best approach to add a note to the readme saying that tilde expansion is not supported or does it make sense to add this support some how?

**Comment by theophilusx** [comment]
I'm not aware of any reliable way to determine the 'home directory', especially as this is really a shell related concept and may not always make sense (for example, anonymous sftp or sftp servers setup in a chroot envrionment etc). 

I will document ~ as not being supported in the README.

**Comment by theophilusx** [comment]
README updated
