### ISSUE TITLE
Add support to auto-convert timestamps to JS dates

### ISSUE THREAD

**Issue by jhorbulyk** [theophilusx/ssh2-sftp-client#192]
Consider the output form a `.stat()` operation:
```
{
  "mode": 33206,
  "uid": 1318,
  "gid": 1319,
  "size": 11,
  "accessTime": 1575038371000,
  "modifyTime": 1575038371000,
  "isDirectory": false,
  "isFile": true,
  "isBlockDevice": false,
  "isCharacterDevice": false,
  "isSymbolicLink": false,
  "isFIFO": false,
  "isSocket": false
}
```
Observe that the values of `accessTime` and `modifyTime` represent time values.  It would be nice if there was a way to return this data as a JavaScript Date object.

**Comment by theophilusx** [comment]
I thought about this and decided against it for a number of reasons

- It is trivial for the user to do this if they need it. If you don't need it it is just unnecessary overhead
- The Javascript Date() object is not great at dealing with time zones and when the client wants/needs better time related operations, something like moment.js is probably going to be preferred, in which case, the 'raw' format is more convenient. 
- I think the format is more in keeping with the expected output from a stat() call
- Having it as a JS Date object is really only convenient for display. The 'raw' format is more convenient for many other operations i.e. just become simple numeric comparisons.
