### ISSUE TITLE
localhost authentication failure

### ISSUE THREAD

**Issue by bamerf** [theophilusx/ssh2-sftp-client#194]
For some reason sftp to local machine fails with this error: 

```
Error: sftp.connect: All configured authentication methods failed after 2 attempts
```

auth details are correct since they work with other libraries and ftp.

```
const Client = require("ssh2-sftp-client");

    const sftp = new Client();

    const config = {
      host,
      port,
      username,
      password
    };

    return sftp
      .connect(config)
      .then(() => {
        return sftp.put(string, path, { flags: "w", autoClose: true });
      })
      .then(() => {
        res.status(200).send({ message: "SFTP test was successful" });
        return sftp.end();
      })
      .catch(err => {
        console.log(err);
        res.status(200).send(err);
        return sftp.end();
      });
```

Am I missing something?

**Comment by theophilusx** [comment]
It could be that the underlying SSH2 library has not loaded the necessary ciphers, key exchange or other options. Have a look at the Troubleshooting section of the README and the relevant section in the ssh2 docs.  It is sometimes helpful to use sftp to connect to the server using the -vv flag to dump out debug info on the algorithms and key exchange used when making a connection. Then verify ssh2 is using the same.
