### ISSUE TITLE
Passing returns as call backs

### ISSUE THREAD

**Issue by jasonmacer** [theophilusx/ssh2-sftp-client#199]
@theophilusx , I want to say thanks for all the hard work that has gone into this from you, and everyone else. It is a great package.

I am wondering if it is possible to pass the connection through into a function and then return say a "fastGet" from that function?  

Scenerio

1.) make connection
2.) return file list as watchList
3.) watchList.forEach ...
In here is where I need to do several things on each file So like a 
3a.) download the file from the remote location (requires a return)
3b.) append a remote log file (requires a return)
3c.) process file through an API handler for internal uses
3d.) archive remote file (requires a return)
3e.) update the remote archive (requires a return)
4.) end connection

The issue that I'm running into is that inside the forEach i am unable to reuse the existing connection from 1.) and have to start a named connection for each file which then means that I am nesting a pretty good chain of .then statements inside a .then statements.

My hope was to call 3a, 3b, 3c, 3d, and 3e as separate functions using a callback to return the fastGet, append, rename, et cetera, but when i log it I'm getting a <pending> object.

Is what I'm talking about here even possible? 

I greatly appreciate any help!

Thanks!

**Comment by theophilusx** [comment]
I think what you are looking for is async/await. This avoids the large .then() 
chains and would allow you to pass the client object as an argument, which would
allow you to break your code up into different functions which you can then 
call in the manner you outline. Look in the example directory of the repo 
on github for some examples.

**Comment by jasonmacer** [comment]
Thanks @theophilusx!  I'm looking at "bulk-fastget.js", "multiple-get2.js", and "test-get-writable.js"

I'm thinking a combination of all three is where I'm going to need to work towards.

**Comment by theophilusx** [comment]
The use of async/await will allow you to write your code in a more 'traditional' 
manner. You can break your code up into functions and pass the client object
into the function and use it.

The key is to remember to add the async to your functions and then ensure
all client method calls are preceded with await. Then it is pretty much  
the normal familiar pattern. Note that you can get some pretty obscure
error messages when you forget to add an 'await' to a call and remember 
that any function declared with async means that function will now return 
a promise, so it will need to be in a Promise chain or be called with 'await'.
