### ISSUE TITLE
Can't connect to server with DSA key - "Handshake failed: no matching host key format"

### ISSUE THREAD

**Issue by joshuaohana** [theophilusx/ssh2-sftp-client#208]
I have a Node server I want to connect to an SFTP server with. Via FileZilla I can connect to the SFTP server fine, and it presents me a DSA key for me to allow.

When I try to connect with this package in my Node app I get "Handshake failed: no matching host key format"

I'm sure all I need to do is set it to accept the DSA key but I don't know how?

**Comment by theophilusx** [comment]
This is covered in the last section of the FAQ in the README. You will need to look at the documentation for ssh2 at https://github.com/mscdex/ssh2#user-content-client-methods - essentially, you need to add and 'authentication' key tot he config.

**Comment by joshuaohana** [comment]
@theophilusx I saw that section and have tried to put the key in any param that might match, as well as trying to use publickey in authHandler. I couldn't figure out how to set it up though, could you point me in the right direction?

In my desktop ftp client when connecting it returns a message to allow an incoming DSA Finger, which looks like b2:0d:d8:4a:41:23:f0:6a:17:8a:4d:9c:4e:8f:53:74 ... where should I be entering that info?

**Comment by theophilusx** [comment]
I've never setup for DSA as it is the least secure of the available
methods, so I can't really answer your question.

This level of configuration is handled by the SSH2 module. You would be
far better off asking via the SSH2 author - there is probably an
existing issue in the list of closed issues for ssh2 which will provide
the info you need. If not, log an issue with that module (all that
ssh2-sftp-client does is wrap around that module and passes through the
ocnfiguration settings to the ssh2 connect method).

**Comment by joshuaohana** [comment]
Awesome thanks your suggestion got it sorted out asap, the comment over on https://github.com/mscdex/ssh2/issues/464#issuecomment-244977279 was the answer just adding the below to client config worked perfectly

```
          algorithms: {
            serverHostKey: [
              'ssh-dss'
            ]
          }
```
