### ISSUE TITLE
Creating new sftp connections in a loop causes no connection error.

### ISSUE THREAD

**Issue by hcfk** [theophilusx/ssh2-sftp-client#209]
I am connecting to multiple servers to download a specific file from that servers.
I am accessing a file to read the ip adresses from that list and in a foreach loop try to connect to the servers. 
It runs for the first IP address but get an error
I ve tried different approaches but no way.
Interestingly i can manage to run this for shell commands but could not manage to do so for sftp.

> Error: sftp.fastGet: No SFTP connection available
    at Object.formatError (C:\dev\uzakGetir\node_modules\ssh2-sftp-client\src\utils.js:57:18)
    at SftpClient.fastGet (C:\dev\uzakGetir\node_modules\ssh2-sftp-client\src\index.js:437:17)
    at C:\dev\uzakGetir\server.js:24:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_NOT_CONNECTED'
} get error

                var fs = require('fs');
                lines = require('fs').readFileSync('AnahtarAdresleri.txt', 'utf-8').split(/\r?\n/);
                lines.forEach((line) => {
                   var Client = require('ssh2-sftp-client');
                   sftp = new Client();
                    sftp.connect
                        ({
                            host: line,
                            port: 22,
                            username: 'manager',
                            password: 'xxxxx',
                            privateKey: require('fs').readFileSync('./keys/private.key')
                        }).then(() => {
                            var fileName = line + ".gz";
                            var remotePath = "flash:/at";
                            var localPath = ".\/dosyalar/";
                            sftp.fastGet(remotePath + fileName, localPath + fileName).then(() => {
                                sftp.end();
                            }).catch((err) => {
                                sftp.end();
                                console.log(err, 'get error');
                            })
                        }).catch((err) => {
                            sftp.end();
                            console.log(err, 'get error');
                        })
                });

**Comment by theophilusx** [comment]
There are a number of problems in your code. 

- For every line in your file you are calling require to load the library. This only needs to be done once
- You are making a new sftp connection for every request. This is almost certainly going to trigger rate limiting protection on the remote server and is a really inefficient way to do this. Create one connection and then use it for each fastGet() or create multiple separate connections (using different sftp client objects) if you want to run parallel runs (you will need to use clustering of course). 
- Each time through your outer loop, you are overwriting the sftp object with a new object, but you may not have finished with the old object yet (remember this is async code). 

You need to re-write your code and break off the retrieval and processing into a separate function. You might find async/await useful in your situation.

**Comment by hcfk** [comment]
Yes you are right for all the items, but beleive me tried lots of alternatives. But could manage a different approach running. without using ssh2-sftp-client library.

Here is the code.

			var Client = require('ssh2').Client;
			var fs = require('fs');
			require('fs').readFileSync('AnahtarAdresleri.txt', 'utf-8').split(/\r?\n/).forEach(function (line) {
				var conn = new Client();
				conn.on('ready', function () {
					var strCommand;
					strCommand = "\nen\nshow tech-support all outfile at" + line + "\nexit\n";
					//console.log('Anahtar:' + strCommand);
					console.log('Client :: ready');
					var fileName = line + ".gz";
					var remotePath = "flash:/at";
					var localPath = ".\/dosyalar/";
					console.log("Baglanti: " + line);
					console.log("uzak    : " + remotePath + fileName);
					console.log("yerel   : " + localPath+ fileName);
					conn.sftp(function (err, sftp) {
						if (err) throw err;
						sftp.fastGet(remotePath + fileName, localPath + fileName, function (err, list) {
							if (err) throw err;
							conn.end();
						});
					});
				}).connect({
					host: line,
					port: 22,
					username: 'manager',
					password: 'xxx',
					privateKey: require('fs').readFileSync('./keys/private.key'),
				});
			});

**Comment by theophilusx** [comment]
Have a look at some of the examples in the /example directory of the repository. They might help get you started. 

I would recomment you first get the basic functionality of downloading the file working and then from there, build on that. 

BTW, your remote path variable looks wrong. I would make sure you can donwload the file you are after using just plain command line sftp first (not a gui or any other high level tool - just CLI sftp).

**Comment by hcfk** [comment]
Thank you very much @theophilusx. As the remote system is an Allied Telesis switch the remotepath is correct.
We have tested the system today against 200 switches country wide and it is running. The only thing is you should do error handling against erronous IP addresses and such things.
I will go in for deep to check why the ssh2-sftp-client librry client does not allow multiple connections.
I will try to figure out and create a test case that can be inspected.

**Comment by theophilusx** [comment]
There is error checking for failed connections and when possible, the errors do try to reflect the fundamental cause of the error e.g. DNS name lookup, no route to host etc. Of course, for hosts specified as just an IP address about theonly error you can give is cannot connect or no route to host. 

What ssh2-sftp-client is able to check and report is bound by what the underlying ssh2 module does. It is that module which handles all the connection process and we only have what it returns in the error event to work with with regards to error reporting.
