### ISSUE TITLE
SftpClient.end() promise never resolves when SftpClient.client is not actually disconnecting

### ISSUE THREAD

**Issue by andrepaap** [theophilusx/ssh2-sftp-client#210]
When calling SftpClient.end(), the function prepares for handling the disconnect and returns a promise. The promise only resolves when the internal client is actually disconnecting. The cient only disconnect in a specific state and other wise it does not handle the disconnect and return false. In that case the promise from SftpClient.end() is not resolving.

You can reproduce this:

1. Create a new client, but don't connect. => let Client = require('ssh2-sftp-client'); let exampleClient = new Client();
2. await exampleClient.end();  // nothing after this will get called, since end will never resolve

**Comment by theophilusx** [comment]
thanks, good catch. I have added the same test used by all the other methods to ensure a valid connection exists and to reject otherwise.
