### ISSUE TITLE
Can we access the underlying ssh2 client to invoke its functions?

### ISSUE THREAD

**Issue by watery** [theophilusx/ssh2-sftp-client#220]
I'm using this package to upload a file to a remote server, then I need to run a remote shell script and I'd like to directly run it, without having to close the `ssh2-sftp-client` connection and open a separate `ssh2` one.

I've seen that ssh2 exposes an [`exec() function`](https://www.npmjs.com/package/ssh2#client-methods), though I don't seem to be able to call it through the `ssh2-sftp-client`: is this possible?

**Comment by theophilusx** [comment]
No, I don't believe this is possible.

There is quite a difference between SFTP and SSH. You can think of SFTP
as a subset of SSH. While this module does use the SSH2 module, it
really only uses this to establish the connection - all the actual
functionality is built on top of the sftp subsystem and only has access
to the commands provided by that system i.e. the ssh2-streams API.

To achieve what you need, you will need to roll your own using the SSH2
module directly. There are some good examples in the SSH2 repository.

There are listeners added to the client object which are specific to the
sftp functionality. These may well get in the way when it comes to using
other client methods such as exec. Note also that if your remote server
is a *real* SFTP server and not just an ssh connection allowing SFTP,
you may not be able to execute a script - it will depend on the SFTP
server being used. (by real I mean a dedicated SFTP server configures
like an FTP server where the user is put into a chroot environment that
limits what you have access to - these environments typically don't
allow execution of scripts and even when they do, the script is limited
to what is in the chroot environment).

**Comment by theophilusx** [comment]
Just for some additional clarity, the ssh2 object is stored inside the SftpClient object under the property 'client'. The ssh2-streams object used for sftp is stored under the property 'sftp'. There is nothing stopping anyone from directly accessing either 'client' or 'sftp'. However, doing so is not supported and it is likely you will run into numerous complications due tot the event listeners that are critical to the Promise API and which are attached to the 'client' object and specific to the sftp methods.. 

So bottom line is that you can access the other ssh2 API methods, but this is unsupported use. There are no plans to add this level of functionality to this module. My advice would be to just use the ssh2 module directly if you really want to be able to use both the ssh and sftp APIs in the same connection. This would not be difficult, especially if all you want to do is upload a file and then execute a script. The SSH2 documentation is pretty good - the main challenge will depend on the extent to which you are comfortable  working with events and event handlers as there is no Promise API in SSH2 or SSH2-STREAMS.

**Comment by watery** [comment]
Thanks for the information @theophilusx.

I'm actually writing a quick script to automate a deployment, so I'll switch to ssh2 as you suggested.

**Comment by shanehoban** [comment]
@watery hey, I have the exact same problem and am wondering if you would share your automated script for doing the above? The `ssh2-sftp-client` docs are much easier to follow than the `SSH2` docs. Thanks!

**Comment by watery** [comment]
@shanehoban Actually, that script hadn't had any update since my last message, it is still using this library to upload the zipped file.
I run the other script by hand.

**Comment by shanehoban** [comment]
Thanks for getting back to me @watery , I went ahead and created one that does what I need in the end (upload my zip, and execute a command), it does use both `ssh2-sftp-client`, and `ssh2` but I only run it myself anyway so I don't really mind. Here it is in case anyone else wants to do something like this:

``````
const fs = require('fs')

let sftp = require('ssh2-sftp-client');
let client = new sftp();

const { Client } = require('ssh2');

const host = 'HOST_IP'
const port = 'HOST_PORT'
const username = 'HOST_USERNAME'
const privateKey = fs.readFileSync(__dirname + '/PRIVATE_KEY.ppk')

const remoteDirectory = '/directory/to/my/webserver/and/site'

client.connect({
  host: host,
  port: port,
  username: username,
  privateKey: privateKey
})
.then(() => {
  let localDistFolder = fs.createReadStream(__dirname + '/dist.zip')
  let remoteLocation = remoteDirectory + '/dist.zip'
  
  console.log('Uploading zip...')
  return client.put(localDistFolder, remoteLocation)
})
.then(() => {
  // second ssh to execute the script (stupid I know)
  const conn = new Client();

  conn.on('ready', () => {
    console.log('Client :: ready')
    
    let execCommand = 'cd ' + remoteDirectory + ' && ./DEPLOY_SCRIPT.sh'
    
    conn.exec(execCommand, (err, stream) => {
      if (err) {
        throw err
      }

      stream.on('close', (code, signal) => {
        console.log('Stream :: close :: code: ' + code + ', signal: ' + signal)
        conn.end()
      }).on('data', (data) => {
        console.log('STDOUT: ' + data)
      }).stderr.on('data', (data) => {
        console.log('STDERR: ' + data)
      })
    })
  }).connect({
    host: host,
    port: port,
    username: username,
    privateKey: privateKey
  })
})
.then(() => {
  return client.end();
})
.catch(err => {
  console.log(err, 'catch error');
})

``````

**Comment by vitaly-t** [comment]
This is a very common scenario - to copy over some files via SFTP and then execute a script. It should be part of this library, IMO, since the connection object is already there.

**Comment by theophilusx** [comment]
This SFTP connection object is not the same as the ssh2 connection object. The sftp protocol is a subsystem of ssh and not the same as ssh. This module is an ssh2-sftp client and only designed to work with the sftp protocol (which is essentially the FTP protocol run over an ssh connection). The ability to run arbitrary scripts using sftp is not supported and is not functionality that will ever be added to this module.
