### ISSUE TITLE
Cut in progress upload crash with not catched error

### ISSUE THREAD

**Issue by jpablogn** [theophilusx/ssh2-sftp-client#225]
Hello,
These piece of code is working fine uploading as many files as needed:

```
try{
  await sftp.connect(config_conexion);
  console.log('CONECTADO!');

  for(var aux=0; aux<ficheros.length;aux++){
    console.log('fichero: ' + aux + ' de ' + ficheros.length + ' a subir: ', ficheros[aux]);									
    var resultado = await sftp.fastPut( PATH_LOCAL + ficheros[aux], PATH_REMOTO + ficheros[aux] ); 
    console.log('resultado: ', resultado);
  }
	
}catch(err){
  console.error(err.message);
}finally{
  await sftp.end();
}
```
But if I turn off the WiFi while uploading one file and I turn on the WiFi again, once the wifi is up and running and the PC watch again the server the program crash without catching any error.

I can see the error by adding this inside the try-catch but I think i should not need it:
```
sftp.on('error', ()=>{
  console.log("Error EVENT");	
});
```
This is all described in the documentation in "Try/catch and Error Handlers" but as far as the error seem to be in "await fastPut()" line I think the normal try-catch should work.

Is it right?
Thank you.

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client are you running?

What version of node are you running?

What platform are you running on?

What do you mean when you say the script 'crashes' - do you have any
error messages or backtraces etc or does it just exit?

**Comment by jpablogn** [comment]
Sorry, It was my fault:
- node v10.16.0
- windows 10 & Ubuntu 16.04 LTS
- ssh2-sftp-client ^2.3.2

After upgrading form ^2.3.3 to 5.1.2 seems to be working properly on W10.
I will check it in detail in both platforms this week and I will back it there is any problem but seems that this was the only problem.

Thank you & Sorry.

**Comment by jpablogn** [comment]
By the way, section **"using async/await"** shows this example:

```
async function doSftp() {
  try {
    let sftp = await sftp.connect(conf);
    let d = await sftp.cwd();
    console.log(`remote dir is ${d}`);
    await sftp.fastGet(`${d}/foo.txt`, 'bat.txt');
  } catch (e) {
    console.error(e.message);
  } finally () {
    await sftp.end();
  }
}
```
I had to change this two small things  in my code to make it work:
1. take out "let sftp=".
2. take out "()" from finally.

Should your example be changed to this or should it work like that?:

```
async function doSftp() {
  try {
    await sftp.connect(conf);
    let d = await sftp.cwd();
    console.log(`remote dir is ${d}`);
    await sftp.fastGet(`${d}/foo.txt`, 'bat.txt');
  } catch (e) {
    console.error(e.message);
  } finally {
    await sftp.end();
  }
}
```
I am not a NodeJS expert so probably it is not importat or even it is not right, I am just point this out to help you improbe the example/doc (if possible).

Thank you again.

**Comment by theophilusx** [comment]
Juan Pablo García Nieto <notifications@github.com> writes:

> This is all described in the documentation in "Try/catch and Error Handlers" but as far as the error seem to be in "await fastPut()" line I think the normal try-catch should work.
>

Actually, you cannot use try/catch block to catch errors raised via an
eventEmitter - at least not in a reliable manner. The basic problem is
that the event is raised in a different execution context to the
try/catch block and you have no guarantee that the try/catch block has
not already run before the event is raised. See
https://nodejs.org/dist/latest-v12.x/docs/api/errors.html#errors_error_first_callbacks 

This is primarily a result of the somewhat unusual way Javascript
provides asynchronous behaviour when it is a single threaded
environment.

Handling event emitter errors within the API has been somewhat
challenging. This is the main enhancement for version 5.1.2, so
definitely use that version and it should work a lot better.

**Comment by theophilusx** [comment]
The finally issue is a bug and the let sftp = is from an older version
of the API, so basically, I do need to update the docs. thanks.
