### ISSUE TITLE
Is there a way to know if the current SFTP instance is connected ?

### ISSUE THREAD

**Issue by mathias22osterhagen22** [theophilusx/ssh2-sftp-client#226]
The software on which I is notifying a server after that a file is download and move from SFTP.
Some errors can occur before the SFTP connection and between the "connect" and "end" of the sftp instance calls.

I would want to call the "end" function of the sftp instance if this one is connected in case of error from another part.

How can I know that the current SFTP instance is still connected?

Thank you.

**Comment by theophilusx** [comment]
Whenever the connection is closed, either because of a call to end() or
because of an error or connection reset by peer etc, the SftpClient.sftp
property is set to undefined. When a connection exists, this property is
an object which defines the SFTP connection details.

Note that all methods do a check for a valid connection and will throw
an ERR_NOT_CONNECTED exception if there is no connection.

It is quite safe to call end() even if the connection no longer exists,
so I would not bother about testing to verify the connection exists and
just call end(). I usually put the end() call in a 'finally' block and
forget about it.

**Comment by mathias22osterhagen22** [comment]
Thank you. Fact it is that if I call "end()" and that the connection no longer exist then the "then" callback is never called and my program is waiting on promise forever.

There is the implementation that I made and that is working: 
```js
  endIfConnected() {
        return new Promise((res, rej) => {
            if (this.sftp.sftp) { //NOTE:: if sftp connected then end connection
                thisftp.end().then(() => {
                    console.log(`Disconnected (error)`);
                    res();
                }).catch((err) => { rej(err); });
            }
            else {
                res();
            }
        });
    }
```

Thank you @theophilusx

**Comment by theophilusx** [comment]
What version are you running?

There was an issue like that in a previous version, but should not be an
issue with current version, which is 5.1.2

**Comment by sallyzoughaib** [comment]
@theophilusx I am trying to check the connection with sftp server 
I got this error :
>  "message": "connect: getConnection: Timed out while waiting for handshake"


```
import Client from 'ssh2-sftp-client;
public async testConnection(): Promise<MessageResponse> {
    try {
      const config = {
        host: '185.99.32.188',
        port: 3000,
        username: 'super',
        password: 'DS2@dm1n',
      };
      const sftp = new Client();
      await sftp.connect(config);
      console.log('Connected to SFTP server successfully');
      await sftp.end();
      console.log("123456789")
      return {
        message: 'SFTP connection is successful',
      };
    } catch (error) {
      return {
        message: error.message,
      };
    }
  }
```

**Comment by sallyzoughaib** [comment]
@theophilusx I am trying to check the connection with sftp server 
I got this error :
>  "message": "connect: getConnection: Timed out while waiting for handshake"


```
import Client from 'ssh2-sftp-client;
public async testConnection(): Promise<MessageResponse> {
    try {
      const config = {
        host: '*****',
        port: 22,
        username: '***',
        password: '*****',
      };
      const sftp = new Client();
      await sftp.connect(config);
      console.log('Connected to SFTP server successfully');
      await sftp.end();
      return {
        message: 'SFTP connection is successful',
      };
    } catch (error) {
      return {
        message: error.message,
      };
    }
  }
```

**Comment by theophilusx** [comment]
There are many possible causes for this error.

My recommendation would be to verify the sftgp server is accessible and
working by using the exact same conneciton options to connect using
openSSH sftp CLI. If this works, call it a second time, passing -vvv to
turn up debugging and note what algorithms are used to perform the key
excahnge etc. THen verify those algorithms are enabled/supported by the
ssh2 module which ssh2-sftp-client depends on (see the ssh2 docs,
especially the section on connect and setting algorithms to be used.

Note that some algorithms are particularly slow when it comes to the key
exchange and connection cipher negotiation. IN this case, you either
need to force a different algorithms or increase the timeout.

Also,m adding a debug function to get additional debug details from
ssh2-sftp-client may help identify exactly why the handshake is failing.

Look at some of the issues in the ssh2 repository. The error you are
seeing is resonably common and is usually resolved with some additional
configuration and many of the issues listed against the ssh2 repository
can provide valuable guidance.
