### ISSUE TITLE
Basic usage -> in further methods

### ISSUE THREAD

**Issue by foberm2s** [theophilusx/ssh2-sftp-client#229]
Hi, 

so I wrote a function that i.e. lists the files in a given directory. however, when I call that function in another function like so: 
`var res = await myFunctionThatGetsInfo()`
I dont have the real data in the variable, it is undefined. Could someone care to explain how to use it properly?
When using `.then((data) => {console.log(data)});` in the call of the sftp server, the data is there.

Thanks in advance

**Comment by theophilusx** [comment]
Without seeing the source code of your function, I have no idea, it
could be anything. It is almost certainly a bug in your function.

Provide the source of your function, the node version, platform and
ssh2-sftp-client version and I'll have a quick look (no promises I will
spot the bug though!)

**Comment by theophilusx** [comment]
Is this still an issue or can it be closed?
