### ISSUE TITLE
 connect: Timed out while waiting for handshake after 2 attempts

### ISSUE THREAD

**Issue by ankitadate** [theophilusx/ssh2-sftp-client#234]
Hi,

I am using "ssh2-sftp-client": "5.1.2" version and facing the issue while running the application with serverless mode. Getting following error even after passing the correct credentials

` connect: Timed out while waiting for handshake after 2 attempts`

Can anyone help with it ?

**Comment by theophilusx** [comment]
It is likely that you don't have the necessary authentication key
exchange or ciphers loaded. Have a look at the troubleshooting section
in the README.org file within the repository. You may need to add an
authentication object to the config (see the ssh2 README for details).


-- 
Tim Cross

**Comment by ankitadate** [comment]
@theophilusx  Thanks for the quick support. The issue is resolved now , was happening because of VPN Connection. Closing this issue.

Thanks & Happy Coding!

**Comment by jerosau** [comment]
> @theophilusx Thanks for the quick support. The issue is resolved now , was happening because of VPN Connection. Closing this issue.
> 
> Thanks & Happy Coding!

@ankitadate  Hello,
I have the same issue. 
Could you detail the changes you made to the VPN configuration, please ?
