### ISSUE TITLE
Clarification over put TypeScript Options

### ISSUE THREAD

**Issue by yagop** [theophilusx/ssh2-sftp-client#236]
According with docs the put options are as follow:

```
put(src, remotePath, options) ==> string

{
  flags: 'w',  // w - write and a - append
  encoding: null, // use null for binary files
  mode: 0o666, // mode to use for created file (rwx)
  autoClose: true // automatically close the write stream when finished
}
```

But the TypeScript `@types/types/ssh2-sftp-client` defines different options:

```
    concurrency?: number;
    chunkSize?: number;
    step?: (total_transferred: number, chunk: number, total: number) => void;
    mode?: number | string;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ssh2-sftp-client/index.d.ts#L41
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ssh2-streams/index.d.ts#L1616

Could you please help me to clarify which are the correct options?

**Comment by theophilusx** [comment]
The options as documented in the ssh2-sftp-client README are correct.
The ones you listed from the typscript definition look like the options
associated with the fastPut/fastGet methods, not the put() method. These
are not options supported by put().

The put() and get() methods in ssh2-sftp-client use createWriteStream
and createReadStream from the ssh2-streams module. The definitive source
for all the sftp methods is the ssh2-streams documentation. All that
ssh2-sftp-client does is wrap some of the methods provided by that
module in higher level methods, like put() and get(), which in turn are
wrapped in a Promise based API.

**Comment by yagop** [comment]
Thank you!
