### ISSUE TITLE
How should client.end() be called when if there is no connection

### ISSUE THREAD

**Issue by Caerbannog** [theophilusx/ssh2-sftp-client#248]
# Summary
We could improve instructions on how to close a connection, so that it works better when the connection was not established. Or we could change client.end() to ignore these connections instead of throwing an error.

# Details
Tested version of ssh2-sftp-client: 5.2.1
There have been a few similar issues reported in the past, and I believe that the situation used to be worse (see #246). But it might become a little better for little effort.

From the README I would say that the canonical way of managing a connection for short tasks is:
```js
function doWork() {
  try {
    await client.connect(config);
    ...
  } finally {
    client.end();
  }
}
```

When the client fails to connect, the following error will be thrown:
```
Error: end: No SFTP connection available
  File "/tmp/node_modules/ssh2-sftp-client/src/utils.js", line 62, col 18, in formatError
    let newError = new Error(msg);
  File "/tmp/node_modules/ssh2-sftp-client/src/utils.js", line 627, col 20, in Object.haveConnection
    let newError = formatError(
  File "/tmp/node_modules/ssh2-sftp-client/src/index.js", line 1318, col 19, in null.<anonymous>
    if (utils.haveConnection(this, 'end', reject)) {
  ?, in new Promise
  File "/tmp/node_modules/ssh2-sftp-client/src/index.js", line 1305, col 12, in SftpClient.end
    return new Promise((resolve, reject) => {
```

Some use cases require a long-running process. In this case, care should be taken to free all resources after use, and to close connections. That's why we call `client.end()`. But we also want to monitor errors that the developers don't know about. So we can't just blindly swallow all errors in `doWork()`. So here are the solutions : 

- developpers could wrap `client.end()` in a `try` block, and ignore errors
- developpers could skip calling `client.end()` in the `finally` block when there is no active connection (see #226)
- the library could be changed to avoid throwing an error in this case ; but it might be surprising for some people (ex: https://nodejs.org/api/net.html#net_server_close_callback)

If the best way is to let developpers handle it, then we can update the README with instructions.
What is your opinion @theophilusx ?

**Comment by theophilusx** [comment]
At one stage, end() did not throw an error if it was called when no
connection existed, but this caused problems for some use cases, so was
removed. IMO a library should not make any assumption regarding how it
is being used. If a function is called and an error occurs, it should be
passed back to the caller. It is the responsibility of the callers code
to decide how to handle possible errors.

In the example you give, an error will be thrown when the connection
fails. The finally clause should wrap the call to end() inside a test
for a valid connection if they don't also want an error raised by
finally when end() is called on non-existent connection. 

I'm not sure if try/catch/finally is the canonical way of managing a
connection. Real world use cases tend to be more complex and of course,
many people still prefer to use Promise chains over async/await. I would
not advise never calling end() as an approach. 

Quite happy to consider any PR which proposes updates for the README.
However, please note that the README.md file is generated from the
README.org file, so any updates must be to README.org and not README.md.
