### ISSUE TITLE
rmdir recursive=false doesn't always behave as expected

### ISSUE THREAD

**Issue by meelash** [theophilusx/ssh2-sftp-client#249]
Apparently, on some implementations of sftp server, directories can be deleted without the recursive flag. This means if you have directory with files in it and call rmdir(directory, false) expecting it to throw if there are the directory is not empty, instead it will successfully delete the directory and its sub-files.

My test looks something like this:

```
    const testDir = 'devTestDirectory2/devTestDirectory1'
      it('should not delete folder with false passed', async function() {
        let sftp = await ftpUtility.connectedClient();
        try {
          await sftp.rmdir(testDir, false);
        }
        catch (error) {
          console.log(error)
        }
        await sftp.end();

        return ftpUtility.listFiles(testDir).should.be.fulfilled;
      })
```

On my locally running sftp server, the test passes, but on a client's sftp it fails.

**Comment by meelash** [comment]
To be clear, I don't think anything needs to be done to "fix" this, but maybe add a line in the documentation to not rely on recursive=false and assume your files won't get deleted.

**Comment by theophilusx** [comment]
Do you know what type, version and platform the remote sftp server is?
(You can often get this info by adding a debug function to the connect
object props). It would be good to know what sftp server allows this and
whether it is a configurable option or not. Also, for complete info, did
the remote directory include both files and sub-directories or just files?

**Comment by theophilusx** [comment]
Note added to documentation
