### ISSUE TITLE
sftp.put doesn't work after making a new folder

### ISSUE THREAD

**Issue by RelyIz** [theophilusx/ssh2-sftp-client#252]
Hi,

If you have a question or need something I didn't mention here please ask.
I'm trying to create a new folder then put a file into it but then it gives this error:

`
(node:38844) UnhandledPromiseRejectionWarning: Error: put->put: Bad path: /usr/share/nginx/cdn/image/wallpaper/car parent not exist
    at Object.formatError (C:\Users\Sander van der Ploeg\Documents\Projects\api's\Private API\node_modules\ssh2-sftp-client\src\utils.js:62:18)
    at SftpClient.put (C:\Users\Sander van der Ploeg\Documents\Projects\api's\Private API\node_modules\ssh2-sftp-client\src\index.js:740:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:38844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
`

This is my code:

`// SFTP Client
let sftp_Client = require('ssh2-sftp-client');
let sftp = new sftp_Client();

sftp.connect({
    host: process.env.SFTP_HOST,
    port: process.env.SFTP_PORT,
    username: process.env.SFTP_USER,
    password: process.env.SFTP_PASS
})
.catch(err => {
    console.log(err, 'catch error');
    return;
});

sftp.mkdir(`${external_Folder}/image/`)
.then(sftp.mkdir(`${external_Folder}/image/${category}/`))
.then(sftp.mkdir(`${external_Folder}/image/${category}/${sub_category}/`))
.then(sftp.put(`${resources_folder}/${fileName}`, `${external_Folder}/image/${category}/${sub_category}/${fileName}`))`

**Comment by theophilusx** [comment]
For future reference, providing details on which version of
ssh-sftp-client, version of node and platform your running on is
important.

Looking at your code, the first thing I notice is that your not using
Promise chains correctly. You must return the new promise from within a
then block if you want that promise to continue in the chain e.g.

.then(() => {
  return sftp.put(....);
})
.then(() => {
  return sftp......
})
.catch((e) => {
  console.log.....
});

If you fail to return the Promise created in the then block, that block
will return a resolved promise immediately and the next then block will
start executing. What I suspect is happening with your code is that the
put() is running before the mkdir() has completed.

There are some examples of using both the promise chain and async/await
in the example directory of the github repository.

**Comment by RelyIz** [comment]
Thanks for the info will keep that in mind for next time.
I returned the new promise in the then block by adding: 

`() =>`

Now it works without any issues.
