### ISSUE TITLE
Can "Client.list" not show hidden files?

### ISSUE THREAD

**Issue by funjobs** [theophilusx/ssh2-sftp-client#256]
I call Client.list here to show all files and folders, I don't want to show hidden files. Can it be set?

**Comment by theophilusx** [comment]
The second argument of list() is an optional regular expression. If
there are some files you don't want to appear in the list, you can
define a regexp to filter the list in whatever way you want.

**Comment by funjobs** [comment]
Can you give an example? Filter hidden files

**Comment by theophilusx** [comment]
It is a basic regular expression. Assuming hidden files are files (and
directories) with a leading period (.) in the name, then something like
^[^.].* should work.
