### ISSUE TITLE
 How to limit the upload / download network speed?

### ISSUE THREAD

**Issue by kennylbj** [theophilusx/ssh2-sftp-client#259]
Is there a way to set the threshold/boundary of network speed when upload/download the file?

For now, the step callback in ``fastGet`` is the only exposed function that I can use to implement this feature.

Hope there are something like downloadLimit / uploadLimit configuration for it.

**Comment by theophilusx** [comment]
No, there is nothing in ssh2-streams module to support this, so nothing
available via ssh2-sftp-client module.

If you were able to implement a 'throttled' stream object, you could use
that as the input/output for put()/get() methods as they both allow
passing in a stream as the source/destination argument.

**Comment by kennylbj** [comment]
Oh thanks! I missed that the get/put API accept streams to pipe in/out.

**Comment by kennylbj** [comment]
Thanks to @theophilusx 's suggestion, here is my solution with speed throttle and progress callback:

```js
const Throttle = require('throttle');
const progress = require('progress-stream');

 // limit download speed
  const throttleStream = new Throttle(config.throttle);

  // download progress stream
  const progressStream = progress({
    length: fileSize,
    time: 500,
  });
  progressStream.on('progress', (progress) => {
    console.log(progress.percentage.toFixed(2));
  });

  const outStream = createWriteStream(localPath);

  // pipe streams together
  throttleStream.pipe(progressStream).pipe(outStream);

  try {
    await client.get(remotePath, throttleStream);
  } catch (e) {
    console.log('sftp error', e);
  } finally {
    await client.close();
  }
```

**Comment by theophilusx** [comment]
That is a good example. I will add it to the README if that is OK with
you?

**Comment by kennylbj** [comment]
Sure, glad to hear that!

**Comment by kennylbj** [comment]
There is a caveat that we must set the autoClose flag to false to avoid calling an extra _read() on a closed stream that may cause ``_get Permission Denied`` error in ``ssh2-streams``.  I think this also needs to be documented.

Here is the fixed version:
```ts
  try {
    // set autoClose to false
    await client.get(remotePath, throttleStream, { autoClose: false });
  } catch (e) {
    console.log('sftp error', e);
  } finally {
    await client.end();
  }
```

By the way, should other actions be made (something like manually destroy the ssh2 read stream) if we set ``autoClose`` to false? @theophilusx

**Comment by theophilusx** [comment]
OK, thanks for the update. Will update the README.

Yes, closing the remote stream object is probably required. At the
moment, there is no interface to do that. I'll need to check and give it
some thought. Might be a little challenging to get right. The 'finish'
signal is what triggers the resolve for the Promise. Cannot just provide
an interface to call close as the stream object is not referenced once
the Promise completes. I guess I could just check for an autoClose:
false in the options and if it is there, call close on the stream after
the promise has called resolve.

Will update over the weekend and let you know when it is done. If you
can then test that would be good.

**Comment by kennylbj** [comment]
Happy to help.

I agree with you, maybe we should check the autoClose flag when the writable stream emits a finish event. and if it is true, call ``destroy()`` on that readable stream.

```js
wtr.once('finish', () => {
    utils.removeListeners(rdr);
     if (typeof localDst === 'string') {
       resolve(localDst);
     } else {
      resolve(wtr);
    }
    if (!options.autoClose) {
      rdr.destroy();
    }
    this.removeListener('error', errorListener);
    this.removeListener('close', closeListener);
});
```

**Comment by theophilusx** [comment]
Yes, that was what I was thinking. However, as autoClose is not always a
property, we will need to explicitly test it is false, otherwise we will
try to call close when autoClose is absent (and is therefore default true).

**Comment by kennylbj** [comment]
Yes, I missed it.  :D

**Comment by theophilusx** [comment]
I have updated the code and documentation to deal with the autoClose
settings. The changes are in the master branch of the repo. If you can
give it a test and let me know, I'll see about releasing a new version
if all is good.

**Comment by kennylbj** [comment]
Since the get method can not expose the ssh2 read stream, it's hard to write a test case to verify whether the read stream is destroyed or not.

An excepted test case would like this if we are able to access remote readable / writable stream:

```js
it('get with autoClose set to false', async function () {
    let localPath = makeLocalPath(config.localUrl, 'test.txt');

    // if we can access the ssh readable stream, we can test whether it's destroyed.
    let in = sftp.createReadStream('test.txt');
    let out = fs.createWriteStream(localPath);
    await sftp.get(in, out, { autoClose: false });
    let stats = await sftp.stat(in);
    let localStats = fs.statSync(localPath);
    const sameSize = expect(localStats.size).to.equal(stats.size);
    const streamDestroyed = in.destroyed()
    return sameSize && streamDestroyed;
  });
```

In addition, I think should destroy the remote stream before the promise is resolved, which guarantees that further invocation always based on a destroyed remote stream.

```js
wtr.once('finish', () => {
    utils.removeListeners(rdr);
    // destroy the rdr before promise resolved
    if (options.autoClose === false) {
      rdr.destroy();
    }
   if (typeof localDst === 'string') {
     resolve(localDst);
   } else {
    resolve(wtr);
   }
  this.removeListener('error', errorListener);
  this.removeListener('close', closeListener);
 });
```

**Comment by kennylbj** [comment]
hi, @theophilusx, Any suggestion on the tests? I use the latest code in my project and everything works well, but I can't find a way to test if the stream is closed normally or not.

**Comment by theophilusx** [comment]
No, there is no easy way to verify the stream has been destroyed
(without making significant changes to the API). All I
can think of is testing by doing a large number of downloads and see if
we observe any errors or memory leak. The problem is that we don't know
when the download has finished until the promise is resolved, but by
that point, the stream is out of scope. I could possibly make the stream
handle a property of the object, but doing that just to facilitate
testing seems like a bad design choice and a potential source of other
problems.


-- 
Tim Cross
