### ISSUE TITLE
fastGet throws Undefined Error

### ISSUE THREAD

**Issue by okhick** [theophilusx/ssh2-sftp-client#261]
I'm trying to pull down a file from a server. Using `sftp.stat(file)` returns the following: 

``` 
{
  mode: 16893,
  uid: 0,
  gid: 33,
  size: 4096,
  accessTime: 1599621461000,
  modifyTime: 1599621458000,
  isDirectory: true,
  isFile: false,
  isBlockDevice: false,
  isCharacterDevice: false,
  isSymbolicLink: false,
  isFIFO: false,
  isSocket: false
}
```
However, when I call `sftp.fastGet(file, dest)` I get the following error: 

> Error: fastGet->fastGet: Undefined error - probably a bug!
    at Object.formatError (/Users/oliverhickman/dev/website_backup/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at SftpClient.fastGet (/Users/oliverhickman/dev/website_backup/node_modules/ssh2-sftp-client/src/index.js:603:19)
    at async downloadBackup (/Users/oliverhickman/dev/website_backup/app.js:29:5) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}

Using just `sftp.get(file, dst)` with a writable stream works fine. This could be a setting on my server, I'm just not sure how to troubleshoot it. Full code snippet below. 

```js
const Client = require('ssh2-sftp-client');
const sftp = new Client();
const backupPath = 'path/to/backup/folder';
const backupFile = 'backup.file';

downloadBackup();

async function downloadBackup() {

  try {
    await sftp.connect({
     // connection creds
    });
  
    const stats = await sftp.stat(`${backupPath}/${backupFile}`);
    console.log(stats)

    await sftp.fastGet(`${backupPath}/${backupFile}`, './test.log');
  
    console.log("end")
    sftp.end();

  } catch (e) {
    console.log(e);
    sftp.end();
  }
}
```

**Comment by theophilusx** [comment]
What version of Node?
What platform is the client running on?
What platform is the server running on?
What version of ssh2-sftp-client?

**Comment by okhick** [comment]
Sorry I should have included that.

- Node version v12.18.0
- Client on MacOS 10.15.5
- Server on Debian GNU/Linux 9.13 (stretch)
- ssh2-sftp-client 5.3.0

**Comment by theophilusx** [comment]
Based on the output you sent, the stat(file) call is returning details
on an object that is a directory (see isDirectory property). So fastGet
is not going to work as it only works on files.

However, the error is not informative and so something is not quite
right here. Can you run it again, but this time, add a debug function to
the connect object e.g.

{
  username: ....
  ...
  debug: (msg) => {
    if (msg.startsWith('CLIENT')) {
      console.log(msg);
    }
  }
}

This will generate a fair amount of debug output. Send it and I'll see
why we are getting that undefined error (it should be an error saying
that the object is not a file).

**Comment by okhick** [comment]
I was in the weeds last night and I can't reproduce the `isDirectory : true` when I call `stat(file)`. Not sure what was going on there...
I still get the undefined error though. Looks to be something with the destination file? Here's the debug: 

```
CLIENT[sftp]: Debugging turned on
CLIENT[sftp]: SFTP connection established
CLIENT[sftp]: Connected - do stage 2 setup
CLIENT[sftp]: absPath = /
CLIENT[sftp]: Remote platform unix like
CLIENT[sftp]: Connection and setup completed successfully
CLIENT[sftp]: exists -> applications/kqyzrsjabg/local_backups/backup.log
CLIENT[sftp]: stat -> applications/kqyzrsjabg/local_backups/backup.log
CLIENT[sftp]: stats <-  {
 "mode": 33279,
 "permissions": 33279,
 "uid": 1003,
 "gid": 33,
 "size": 15,
 "atime": 1599622680,
 "mtime": 1599621458
}
CLIENT[sftp]: Removing listener from error
CLIENT[sftp]: Removing listener from close
CLIENT[sftp]: exists <-  {
 "mode": 33279,
 "uid": 1003,
 "gid": 33,
 "size": 15,
 "accessTime": 1599622680000,
 "modifyTime": 1599621458000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
CLIENT[sftp]: fastGet remote path info  {
 "path": "applications/kqyzrsjabg/local_backups/backup.log",
 "type": "-",
 "valid": true
}
CLIENT[sftp]: fastGet local path info  {
 "path": "test.log",
 "type": false,
 "valid": false,
 "msg": "No such file: ",
 "code": "ENOENT"
}
Error: fastGet->fastGet: Undefined error - probably a bug!
    at Object.formatError (/Users/oliverhickman/dev/website_backup/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at SftpClient.fastGet (/Users/oliverhickman/dev/website_backup/node_modules/ssh2-sftp-client/src/index.js:603:19)
    at async downloadBackup (/Users/oliverhickman/dev/website_backup/app.js:55:5) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}
CLIENT[sftp]: Adding enderrorListener
CLIENT[sftp]: Have connection - calling end()
```

**Comment by okhick** [comment]
Okay a bit more information. When I use an absolute path on the destination, I get no error. When I use a relative path, I get the error. However the relative path does seem to work when the file already exists (it overwrites the file).

**Comment by theophilusx** [comment]
Yes, there does seem to be an issue there with relative paths on local
files. I notice in the debug output that the leading './' seems to have
been dropped. This is likely due to recent changes made to fix issues
with paths on win32 platforms. I'll add some additional tests and track
it down and let you know when it is fixed.

**Comment by theophilusx** [comment]
I have checked in a fix to the master branch of the repo. Please try it
and see if it now works with relative paths for local targets.

**Comment by okhick** [comment]
Yep! Can confirm that it now works for my use case.

**Comment by theophilusx** [comment]
OK, I will close this issue and release a new version (v5.3.1).
