### ISSUE TITLE
Is it possible to determine the target OS?

### ISSUE THREAD

**Issue by anton-erofeev** [theophilusx/ssh2-sftp-client#267]
Hi,
Is it possible to determine the target OS? (Win/Mac/Linux) I couldn't find any special methods for it.

**Comment by theophilusx** [comment]
No, there is no command in the ftp/sftp protocol which provides that
information. However, sometimes you can get details by adding a debug
function. This is not guaranteed to work. However, often, when you
enable debugging the remote server will respond with details regarding
the server software and this often includes platform information.

There are some heuristics you can use which may indicate a win32
platform.

You can also sometimes use realpath() to get the full path of the remote
server, which *may* provide some clues (such as starting with /C:/.../
indicating a probable win32 platform. Likewise, the list() method and
inspecting the permissions information can provide an indication of
win32 (which does not have group/other permissions, so just has '*' for
those values. 

The ssh2 module which ssh2-sftp-client uses does provide methods to
allow execution of a remote command. If you really need to determine the
remote platform AND you can ssh to it, you could knock up something
using that module which calls some remote command which may provide the
details you need to determine platform type. Theoretically, you could
ssh to the remote host, execute something like a simple node JS script
to return the platform info. You cannot do this just with
ssh2-sftp-client as it uses the sftp subsystem of ssh and only has
access to the commands which it provides.

**Comment by anton-erofeev** [comment]
Thanks for the answer!
