### ISSUE TITLE
How to change directory?

### ISSUE THREAD

**Issue by azamsolix** [theophilusx/ssh2-sftp-client#268]
Hi,
    How can I Change the current working directory using ssh2-sftp-client npm?
    How can I  Switch to the parent directory of the working directory?
    Please help me with this?
Thanks

**Comment by theophilusx** [comment]
There is no method to change the remote directory.

ssh2-sftp-client only has access to the methods provided by ssh2-streams
and there is no method provided by that module to change the remote
directory.

Note that you can reference directories relative to the local directory
using '..' (parent), '.' (current) in your remote path specification.
