### ISSUE TITLE
How to check if a sftp connection is active or not?

### ISSUE THREAD

**Issue by azamsolix** [theophilusx/ssh2-sftp-client#270]
Is there any method to check if sftp connection is active or not?

**Comment by theophilusx** [comment]
Do you mean active in the sense there is a connection or do you mean
active in the sense there is something actively using the connection?

If you just want to check that a connection exists, you can test the
'sftp' property of the object returned from call to new
ssh2-sftp-client. If non-null, a connection exists. Note however, this
relies on ssh2-sftp-client receiving a signal when a connection is lost.
This does not always happen (depending on the type of error which has
severed the connection). Most, if not all, of the methods in
ssh2-sftp-client already do this check before attempting to execute a
command and will return a rejected promise if there is no connection.

What is the context where you believe you need to do this checking?

**Comment by azamsolix** [comment]
Thank you so much sir.I understood what to do next.
You were so helpful.
Thank you
Azam
