### ISSUE TITLE
[Feature] File and Directory listeners

### ISSUE THREAD

**Issue by AllanOricil** [theophilusx/ssh2-sftp-client#276]
It would be good if we could notify the server that a new file or directory was created.

**Comment by theophilusx** [comment]
Can you expand a bit on what you mean? How do you imagine this feature working?

**Comment by AllanOricil** [comment]
Like, If a new file is added to a certain folder then the lib would dispatch an event that tells me a new file was added.
For instance, on VSCode API we can declare file listeners, which they call File System Watcher, like the one below:

````
const fileWatcher = vscode.workspace.createFileSystemWatcher(filePath);
fileWatcher.onDidChange(() => (this.mPromise = this.provideTasks()));
fileWatcher.onDidCreate(() => (this.mPromise = this.provideTasks()));
````

A File System Watcher takes a Path or something like `*.js`. When we pass a path, the file watcherr will dispatch Change or Create events anytime a new file is created or changed. If we pass `*.js` it will dispatch events only when the file ends with the js extension. We can even pass something like `**/**.js` to configure the Watcher to keep tracking any files in any folders that ends with js.

With this feature I will be able to notify other server that a File has been added and then start another process or automation.

**Comment by theophilusx** [comment]
So what you want is some way to be notified when a file is added or
changed on the remote sftp server?

This is actually quite difficult to do in an efficient manner. With
local filesystem watchers, you have low level OS support (such as
inotify), which can be used to fire an event when some filesystem change
occurs. However, with an sftp server, you don't have any such facility.
All you can do is a 'polling' type service. Essentially, a loop which
will do a list() or stat() of the remote sftp server, compare the
results to the last time the poll was taken and then trigger an event if
something has changed. This would also need to be done over a completely
separate connection as the sftp protocol does not support concurrent
operations over the sftp connection i.e. you cannot run two sftp
commands in parallel. This means that if ssh2-sftp-client had this
service, once you started the service, you could not use that instance
for anything else until you ended the service.

This would be better handled as a completely separate utility or module.
It could use ssh2-sftp-client, but would really be better if it just
used the ssh2 module as there is lots of stuff in ssh2-sftp-client which
would be of no use.
