### ISSUE TITLE
Unable to put file

### ISSUE THREAD

**Issue by omkartin** [theophilusx/ssh2-sftp-client#28]
I am getting the below error when I do this: 
let buffer = new Buffer('', 'binary');
sftp.put(buffer, '/', [false],['utf8'])

Error: 
(node:20063) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Unknown encoding: utf8
(node:20063) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And this when I do use a remote path: 
sftp.put('./tmp/test.txt', '/', [false],['utf8'])

Error: (node:20088) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: FAILURE

Please let me know what should I pass

**Comment by jyu213** [comment]
binary should be pass 'null'. 
sftp.put(buffer, '/', [false], null)

and I test put file is worked
