### ISSUE TITLE
Is it possible to connect to SSH Server via hopping? Similar to SSH2-promise?

### ISSUE THREAD

**Issue by guirkgumbo** [theophilusx/ssh2-sftp-client#288]
Example docs of SSH2-promise. I ask this because I am having issues with SSH2-promises sftp fastput. The fastput operation seems to be corrupting encrypted zips during file transfer I was interested in testing ssh2-sftp-clients put option to see if this would lead to anything different.  My use case requires I connect to a bastion server first so I gotta do a hop similar to below.

`//SSH server detail used for hopping
var sshconfig1 = {
  host: '192.168.1.2',
  username: 'ubuntu',
  identity: '/here/is/my/key1'
}

//SSH server detail to be connected
var sshconfig2 = {
  host: '192.168.1.3',
  username: 'ubuntu',
  password: 'mysecret2'
}

//It will establish connection to sshconfig2 via sshconfig1
//by default it will cache connection, 
//to disable caching, pass second parameter as true
//new SSH2Promise([sshconfig1, sshconfig2], true)
var ssh = new SSH2Promise([sshconfig1, sshconfig2]);

//Promise
ssh.connect().then(() => {
  console.log("Connection established") 
});`

**Comment by theophilusx** [comment]
ssh2-sftp-client does not support this ability. You could do it using just ssh2, but then you will be dealing with just an event model and will need to manage the events yourself (no promises, unless you wrap things yourself). 

In theory, ssh2-sftp-client could probably be extended to add this feature, but I would be concerned how much it would increase complexity and this is not a common use case. However, as ssh2 is currently undergoing a complete re-write and as there are other features requests and bugs to squash, I cannot see this happening any time soon.

**Comment by theophilusx** [comment]
BTW another approach would be to setup some form of proxy. i.e. if you need to get to Host C via Host B from Host A, you could setup a proxy on host B which listens on some port (like 4000) and have it send connections to that port to port 22 on host C. I know that others have done this with a SOCKS proxy (there is a little info in the README). Downside is that you need access/permisson to run the proxy and it creates another failure point, so more fragile).

**Comment by guirkgumbo** [comment]
Gotcha I will try some other options. Thank you for responding.
