### ISSUE TITLE
question: is connection open

### ISSUE THREAD

**Issue by jdiderik** [theophilusx/ssh2-sftp-client#295]
Hi,

I may be overlooking it, but I cannot seem to find how to verify if a sftp instantiated client has an open connection.
I use async/await and need to process multiple files.
I would like to check if the connection is open to prevent errors of a put.

I could add an eventListener for 'close' or 'end' , but is there a way without that?

Thank you for your work, really like the simplicity of this lib.

**Comment by theophilusx** [comment]
All the methods in the sftpClient class use a function called
haveConnection() in the utils.js file to check for a valid connection
before attempting any operation. If the function is called within a
Promise, it is passed the reject() function to cause the Promise to be
rejected and if it is called outside a Promise, with no reject()
function passed in, it just raises an error.

This means you can just use a normal .catch() or a try/catch to handle
situations where there is no connection. However, if you still want ot
handle this yourself, you can just check the value of the sftp property
of the object representing the sftpClient class - if
it is undefined, then there is no connection. Alternatively, you could
use the utils.haveConnection() function (you pass in the object
instance, a name, which is used in reporting errors and an optional
reject function, if called inside a Promise you created.

Have a look at the function in the utils.js file and see how it is used
in the main index.js file.

**Comment by jdiderik** [comment]
ok, cheers for the quick reply, I can work with that
(I'm trying to prevent errors being thrown (try/catch) due to disconnection during a routine and rather handle reconnecting myself. Makes developing the flow a bit easier in my code)
