### ISSUE TITLE
Any plans to upgrade to Node 14 (current LTS)

### ISSUE THREAD

**Issue by geshan** [theophilusx/ssh2-sftp-client#300]
Hello,

This is a great library, it has helped us a lot to upload files to an SFTP.

We were wondering if there are any plans to upgrade it to be compatible with Node 14 (current LTS). Node 12 will be maintained for the next 12-14 months. Still, we were thinking if there are plans for the current LTS upgrade it would help everyone. Thanks!

**Comment by theophilusx** [comment]
The only thing preventing upgrade to support node 14+ is the underlying
ssh2 library. The maintainer of that library is doing a complete
re-write of the library to address both issues with node 14.x and to
address some underlying design weaknesses. Unfortunately, this re-write
is taking some time to complete. However, as soon as it is released, I
will be able to release a new version of ssh2-sftp-client which should
support all node versions, including >= 14.x.

I have been monitoring the progress of the ssh2 re-write and tested
against it recently. Unfortunately, it still has some major issues which
make it unusable for production purposes at this time.

Note that the main incompatibility with node 14.x has been rolled back
in node 15.3. It does appear that the current ssh2-sftp-client works
with node versions greater than 15.x. However, the features in node
which caused the incompatibility and which were rolled back in node 15.3
do provide a significant network performance improvement in the majority
of use cases, so it is likely the change will be re-applied at some time
in the future. I'm hoping that if the new ssh2 version is not ready by
the time node v12 is no longer supported that node 16.x has not included
the problematic changes and the existing ssh2 and ssh2-sftp-client
library will work with node 16.x.  In the meantime, all we can do is
encourage the maintainer of ssh2 to complete the re-write of ssh2, which
will become ssh2 v1.0.0
