### ISSUE TITLE
TypeError: (intermediate value).finally is not a function

### ISSUE THREAD

**Issue by samuel-tulus** [theophilusx/ssh2-sftp-client#309]
![image](https://user-images.githubusercontent.com/47520367/113579918-273faf80-964f-11eb-86a5-d44d27fed7bb.png)
I am using Node 8.11.1 and Windows 10 x64, This 'finally' function is not supported for mine. When I change 'finally' to 'then', then it works. Please help me, Sir. Thank you.

**Comment by theophilusx** [comment]
Node 8 is very old and not supported. You need at least node 10. I would
recommend node v12. Note that node v14 has issues, so don't use it
either.

**Comment by samuel-tulus** [comment]
I was just tracing your version history and found that v 6.0.0 is not using 'finally' as a function and working for mine. Thanks for your explanation.
