### ISSUE TITLE
.finally() clauses added in v6.0.1 breaks all methods for Node version < 10

### ISSUE THREAD

**Issue by AlexGaiser** [theophilusx/ssh2-sftp-client#317]
Since the `.finally()` method was added in Node v10, in `ssh2-sftp-client` the change in `v6.0.1` to include `.finally()` for all promises breaks any environment that does not have an implementation of `.finally()` with the error:

```bash
TypeError: (intermediate value).finally is not a function
    at SftpClient.sftpConnect (.../node_modules/ssh2-sftp-client/src/index.js:118:15)
```

Suggest either adding a condition for backwards compatibility or adding this limitation to the ReadMe.

**Comment by theophilusx** [comment]
The README already states

Node versions < 10.x are not supported.

There was an error in that the current stable version number had not
been updated to 6.0.1 and was reading 5.3.2. This has now bene updated.

**Comment by AlexGaiser** [comment]
Ok thank you
