### ISSUE TITLE
Lack of good examples !

### ISSUE THREAD

**Issue by jagtapAmit** [theophilusx/ssh2-sftp-client#32]
Please add good examples showcasing the usage of basic api's like get and put . It should also include how supporting node stream code and various ways of reading and writing the file to and back from SFTP server. 
A recommended way to create a connection and maintain it across various modules in node js environment.

**Comment by theophilusx** [comment]
A directory with some examples has been aded to the github repo. Additional exmaples are being added to the FAQ section. Documentation is also being extended. This is an on-going task.
