### ISSUE TITLE
Number of files Listed are Incorrect 

### ISSUE THREAD

**Issue by ShivaPotlapelli** [theophilusx/ssh2-sftp-client#321]
I have around 68 files on my FTP server but,
**when performed client.list(remote path) then the number of files retrieved are 66
I am using version 6.0.1**
This started happening today itself earlier it worked as expected
Can someone help us know in case any breaking changes in this version

**Comment by theophilusx** [comment]
Version 6.0.1 has been out for a few months and no reported issues like
the one you are reporting. Nothing has changed in the code related to
list(). Are you using a filter pattern in the call?

I would suggest testing with the openSSH's sftp client and see if you
get a different count. Also, if you can show which files from the
listing are not being listed (assuming the same ones are skipped each
time), I might be able to look closer and see if I can reproduce the
behaviour.

Finally, I will be releasing a new version in the next couple of days.
It is based on the new ssh2 1.1.0 version (a complete re-write of ssh2).
You could also try using the master branch from the repo to see if you
observe the same issue.

**Comment by ShivaPotlapelli** [comment]
Yes @theophilusx everytime I see the same files being missed

**Comment by theophilusx** [comment]
Is there anything in the missed filenames which might explain it? For
example, utf characters, hidden files etc? Are the permissions on all
the files the same? Can you provide a sample output of what is listed
and what is listed when you use something else like openSSH's sftp CLI
client?

**Comment by ShivaPotlapelli** [comment]
I went through the files which are listed and the files which are not listed ...The files have the same permission set on all of them no difference but the difference for the files which were not present in the list is they were just uploaded into a directory i.e; timestamp difference nothing apart, not hidden files, or utf characters.

I will be providing a screenshot to you showing which are present and which are not present

**Comment by theophilusx** [comment]
OK, thanks.

One thing to check. Make sure the directory the files are being uploaded
into also has the execute bit set. On *nix systems, the execute bit must
be set on directories in order to get a listing of the directory
contents. I'm wondering if perhaps the directory does not have execute
permission, so no listing, so missing/unlisted files?

**Comment by ShivaPotlapelli** [comment]
I think this can be closed as it is intermittent issue will reopen in case it appears again
