### ISSUE TITLE
downloadDir no option for regex

### ISSUE THREAD

**Issue by efratha94** [theophilusx/ssh2-sftp-client#324]
Hi,
I already opened an issue about it which was closed, but it was still not fixed.
I'm trying to use downloadDir with regex, but there's no such option at all:

![image](https://user-images.githubusercontent.com/57014350/123224207-475a6e80-d4da-11eb-945b-3a4e911272b8.png)

Even if I pass a regex parameter, it gets ignored.

Also from the ts file:
![image](https://user-images.githubusercontent.com/57014350/123224296-60631f80-d4da-11eb-9608-cd7ce1f1d72b.png)

What can I do? Is it possible to fix it?

**Comment by theophilusx** [comment]
From my position there is nothing to be fixed, The downloadDir() method
accepts 3 arguments, remote source directory, local directory to put it
in and a filter regexp.

The fact the option is not showing up in the auto-complete in your
editor is nothing to do with ssh2-sftp-client. This is either an issue
with your editor or an issue with the typescript definition file you are
using. I have nothing to do with typescript or any typescript definition
files. The ssh2-sftp-client.ts stuff is done by someone else and nothing
to do with the ssh2-sftp-client library.

My suggestion would be to ignore the auto-complete of your editor and
just add the 3 supported arguments as documented in the ssh2-sftp-client
README.


-- 
Tim Cross
