### ISSUE TITLE
Connection time becomes longer after update to 7.0.0

### ISSUE THREAD

**Issue by zhangbaojia** [theophilusx/ssh2-sftp-client#332]
node.version: v14.15.0

updated from 6.0.01 to 7.0.0 and the connection were noticeably slower

![微信截图_20210716140925](https://user-images.githubusercontent.com/19427334/125900518-8a252d43-f00e-410e-8e45-6f85059410b1.png)

**Comment by theophilusx** [comment]
I believe this is due to changes in ssh2. See issue #1031 in the ssh2
repository. It looks like this will be resolved once a new version of
ssh2 is released.

**Comment by zhangbaojia** [comment]
Oh, I see you noticed.
thank you。
