### ISSUE TITLE
Should return SFTPstream

### ISSUE THREAD

**Issue by zenyu** [theophilusx/ssh2-sftp-client#337]
https://github.com/theophilusx/ssh2-sftp-client/blob/669f583cb19cfd44ef6fa421c94ac2e3cd298459/src/index.js#L147

DOC：`connect(config) ===> SFTPstream`

**Comment by theophilusx** [comment]
thanks. That was a documentation error. It should have been returns an
SFTP object. I have corrected this in the master branch.
