### ISSUE TITLE
Version 2.0.1 Handshake failed

### ISSUE THREAD

**Issue by pantos27** [theophilusx/ssh2-sftp-client#34]
When trying to connect to a certain sftp server with version 2.0.1I get a Handshake failed error
In version 1.1.0 it's fine

**Comment by zgriesinger** [comment]
Having the same problem here, it looks like it has something to do with ssh2-sftp-client not working well with the 'ssh-dss' host key type which was removed in OpenSSH 7+. According to the ssh2-streams package you can override host key with the algorithm object on connect but it isn't working for me.

**Comment by jyu213** [comment]
@pantos27  in version 2.0.0，I upgrade ssh depends to new version v0.5.5。 
you can  search for help in https://github.com/mscdex/ssh2/issues.
Tips: you can set debug: console.log in the config and post the result 

thx.

**Comment by theophilusx** [comment]
As this was an issue with the underlying ssh2 library and it is now quite old, I'm closing it.
