### ISSUE TITLE
Pattern Filter in list method is case sensetive

### ISSUE THREAD

**Issue by RezaRahmati** [theophilusx/ssh2-sftp-client#348]
Hi there

I am observing a behavior that Pattern Filter is `list` method is case sensitive,

for example `list(folder, 'foo*')` return empty if file name is `Foo123`

**Comment by theophilusx** [comment]
The pattern can ge a regular expression, which will be case sensitive or
not depending on how you define the regular expression. By default,
regular expressions are case sensitive.
