### ISSUE TITLE
Connection does not get closed in rare case

### ISSUE THREAD

**Issue by TomasZamecnik** [theophilusx/ssh2-sftp-client#358]
## Situation
 When `ssh2-sftp-client` is trying to connect to server where SFTP is out of order,
 client does not close SSH connection regardless of whether `end()` method is called - connection remains open.

## Idea
 Underlying method `this.client.end()` never gets called in this situation.

## How to simulate remote with SSH, but without SFTP
 In the server, in system file `/etc/ssh/sshd_config` remove line: `Subsystem      sftp    /usr/lib/openssh/sftp-server`

## Debugging
 In `src/index.js:SftpClient.end()`:
 Condition `if (haveConnection(this, 'end', reject)) {` fails, which causes that `this.client.end();` is not called.

**Comment by theophilusx** [comment]
Coincidentally, I took over the maintenance and extended this module
when I was also working on weather data - used it to transfer large
NetCDF data file from our Bureau of Meteorology for software used to
predict flystrike and sudden chills for sheep farming and prediction
software for cropping etc.

We don't normally get tornados in Australia - there might be some
climate change occurring :-) Sadly, I have a few family members and
friends who are now homeless, but luckily nobody badly hurt or dead.

I'll let you know once I've made the change and you can try out the new
version from the repo and see if it fixes the issue.

**Comment by TomasZamecnik** [comment]
Coincidentally, that public meteo server I mentioned, is Australian BOM...and it was bombed by our unterminated connections :-)
On tornadoes: I live in the Czech republic and tornadoes are very rare in history of our country. This year we experienced a huge one (probably biggest ever in CZ) which completely destroyed a few villages. Fortunately I know it only from TV.
I wish you and your family to get over this horrific situation!

**Comment by theophilusx** [comment]
Did you manage to try the master version to se if it addresses the issue you encountered?

**Comment by theophilusx** [comment]
Fix pushed to master and will be in v7.2.0
