### ISSUE TITLE
Recursive mkdir do not check target folder existance

### ISSUE THREAD

**Issue by MasterLambaster** [theophilusx/ssh2-sftp-client#360]
I'm not sure is it an issue or it's the way how it's been designed, but here's the issue I've came across with recursive mkdir.

When I have a recursive dir creation I'm passing its path `/upload/test`. My expectation would be that first we check for 
 `/upload/test` and then for `/upload` if `test` does not exist within `upload`. But in fact the check is performed only for the `/upload`. The reason is that mkdir at [index.js#L854](https://github.com/theophilusx/ssh2-sftp-client/blob/master/src/index.js#L854) uses `path.parse` which behaves like:
```
/upload/test/file.txt - {root: '/', dir: '/upload/test', base: 'file.txt', ext: '.txt', name: 'file' }
/upload/test/ - { root: '/', dir: '/upload', base: 'test', ext: '', name: 'test' }
/upload/test - { root: '/', dir: '/upload', base: 'test', ext: '', name: 'test' }
```
So when you pass just a path it'll take the last part as a base and the rest as a dir so the very last folder is always ignored.

Here's the test for it that uses `chai-spies` to verify what was the arguments for `exists` method.
```javascript
  it('relative dir is checked to exist', async function() {
    const path = `${config.sftpUrl}/test`;
    const spy = chai.spy.on(sftp, 'exists', function() {
      return 'd'
    });

    await sftp.mkdir(path, true);
    expect(spy).to.have.been.called.with(path);
  });
```

Tested with node v14.18.1 and latest master. Also I've checked v17.0.0 and `path.parse` have exactly the same behavior.

**Comment by theophilusx** [comment]
Fix in master branch and will be in v7.2.0 once released
