### ISSUE TITLE
Cannot deploy my app due to sub-modules 

### ISSUE THREAD

**Issue by bernier** [theophilusx/ssh2-sftp-client#361]
Hello,

I'm using Serverless with the serverless-bundle plugin. So I don't have access to the webpack config file.

I'm getting the following error:

```
sls offline start           
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
serverless-bundle: CommonJS, ES3, or ES5 are not supported
Serverless: Bundling with Webpack...
ERROR in ../../cpu-features/build/Release/cpufeatures.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ../../cpu-features/lib/index.js 1:16-60
 @ ../../ssh2/lib/protocol/constants.js 7:12-35
 @ ../../ssh2/lib/server.js 26:4-38
 @ ../../ssh2/lib/index.js 33:10-32
 @ ../../ssh2-sftp-client/src/index.js 7:19-34
 @ ../../../src/config/sftp.ts 62:41-68
 @ ../../../src/handlers/main.ts 77:13-38

ERROR in ../../ssh2/lib/protocol/crypto/build/Release/sshcrypto.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ../../ssh2/lib/protocol/crypto.js 30:12-60
 @ ../../ssh2/lib/server.js 27:29-60
 @ ../../ssh2/lib/index.js 33:10-32
 @ ../../ssh2-sftp-client/src/index.js 7:19-34
 @ ../../../src/config/sftp.ts 62:41-68
 @ ../../../src/handlers/main.ts 77:13-38

webpack compiled with 2 errors
```

Per cpu-features's support "You need to configure webpack to support node (compiled) addons (ending in '.node')."

Do you see any workaround?
If not, what other sftp client do you recommend using?
Thanks!

**Comment by theophilusx** [comment]
I've not used serverless.com, but from what I can see in your log, their
environment is raising what is only an optional dependency warning in
normal node environments to a hard error in theirs.

The cpu-features dependency is an optional dependency and is not
required for ssh2 to function correctly. Unless you can instruct the
serverless environment to respect optional dependencies and not error out
when they fail to build, I'm not sure what you can do. There is nothing
I can do to alter that optional dependency.

I have no other sftp recommendations. I have only ever used ssh2 and
ssh2-sftp-client. I have seen posts from others who have used both ssh2
and ssh2-sftp-client successfully under AWS and with lambda, so my
suspicion is that you may need to look at how your serverless
environment is configured.

**Comment by bernier** [comment]
@theophilusx thanks. I forwarded your answer to the devs of the serverless-bundle plugin.
I was able to use ssh2-sftp-client in a different Serverless project about a year ago without problem. But I know a lot of things changed in a year.

**Comment by theophilusx** [comment]
Please report back when you get a response from the serverless.com devs.
Note also that there has been a thread discussing the cpu-feature
optional dependency in the ssh2 issues. While the current version of
ssh2-sftp-client is based on a new version of ssh2 (a complete re-write
of ssh2), the cpu-features optional dependency has always been there.

As you say, it has been a year and things have moved on, including new
NPM and node versions. It could easily turn out all that needs to be
done is add an additional switch to npm to make it do something it was
doing by default in an earlier version.

**Comment by bernier** [comment]
Thanks @theophilusx 

I was able to deploy my app by using the "ignorePackages" option of serverless-bundle.
I gave it a try since you said these were only optional packages.

In serverless.yml
```
    ignorePackages:                 # Ignore building any of the following packages
      - cpu-features 
```

I'm only getting the crypto error when using the most recent version of serverless-bundle. I'm not using it because it's giving me other unrelated errors :) But the config should stay the same.

**Comment by redstone78** [comment]
We had the same issue with our serverless bundle, but we updated to add the IgnorePackages and then got that sshcrypto.node issue. That was a webpack issue, we just added this to our webpack.config.js

module.exports = {
  target: 'node',
  mode: 'none',
  resolve: {
    plugins: [new TsconfigPathsPlugin()]
  },
  **externals: {'ssh2-sftp-client': 'require("ssh2-sftp-client")'}**
};

![image](https://user-images.githubusercontent.com/30419028/156046469-023fe811-6f3b-45ba-962b-ef57f7a2a953.png)

**Comment by redstone78** [comment]
I actually upgraded to @7.2.2 and it shows up as warnings now instead of errors. and was able to use it successfully
