### ISSUE TITLE
Shouldn't "get" method resolve the promise with read stream instead of waiting for the "end" event?

### ISSUE THREAD

**Issue by gautamsamal** [theophilusx/ssh2-sftp-client#362]
By looking at the `get` method, it seems the method resolves promise on the `end` event. I have provided a stream as destination which is used for pipe and the method resolves almost when all the data is being read.

I was expecting something different here. The `get` method should return a readable stream after being passed all the validation f.e. file exists. Then I should be able to pipe that stream into any destination. But the current implentation resolves after all the data being read, and it's also causing issue if I have a large file - the promise never resolves as no one is comsuming at the moment. My sample code is as following - 

```
        const readStream = await source.read(sourceFilePath);
        await destination.write(destFilePath, readStream);
```
And the read method for the sake of providing a stream is as -
```
    const stream = new Transform({
      transform(chunk, encoding, callback) {
        callback(null, chunk);
      }
    });
    await this.source.get(path, stream);
    return stream;
```

So, waiting for the read to be completed doesn't work for me. I could do some hacks like calling write first with the stream and then wait for the read only but that seems clumsy and error-prone. If I don't wait, It could result in unhandled exception in either of them. Do you have any suggestions?

Thanks!

**Comment by theophilusx** [comment]
I'm sorry if the API is not what you expected, but it is that way for a
reason. There won't be any changes made to return a stream as that would
significantly change the API and break compatibility for too many users.
You are only the second person to request this and the other request was
withdrawn after it was shown they could do what they wanted with the
existing API. . 

The ssh2-sftp-client module is a promise based module which is wrapped
around an event based internal module (ssh2). This creates some
limitations on how you use the module as wrapping a promise API around
an event based module has some challenges when it comes to getting a
consistent interface which can handle most internal events in a clean
manner. .

If the get() method returned the readStream, the client code would have
to ensure it managed that stream correctly - you would have to add all
the necessary event listeners AND ensure there is no adverse
interactions with the event listeners used by ssh2-sftp-client to wrap
and catch events that occur during the get() promise (and are mostly
removed after the promise resolves). This is harder to get right than it
may seem. It also means the client code needs to ensure the stream is
destroyed correctly and deal with external issues, such as loss of
network connectivity etc. Bottom line is the client would have to add a
lot of additional code and complexity if it takes on responsibility for
managing the readStream.

I've yet to find a use case which requires the actual stream to be
returned that could not be handled using a basic stream pipeline. 

What you need to do is setup the destination pipeline before calling
get() and past the first stream in the pipeline to get() and you should
get whatever result you are after. See the examples directory in the
repository to see what I mean. I use this technique to get compressed
files, uncompress and save them locally. Some of these files are quite
large (Gb).

**Comment by gautamsamal** [comment]
Thanks for your reply. I completely understand your reasons. I ended up doing something like this - 
```
        const stream = new PassThrough();
        await promise.all([source.read(sourceFilePath, stream), destination.write(destFilePath, stream)]);
```
Keep in mind that both `source` and `destination` are Sftp clients. I am trying to transfer files from one sftp account to another recursively. This works! 
However I noticed a maxListener warning after around 11 files being transferred. 
```
(node:7467) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7467) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:7467) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
```

To add some more clarifications, I am connecting both source and destination only once and then listing files and transferring then sequentially. At the end of all operations, I am closing the connections. Is there something else I am missing?

Thanks for all the help! I really appreciate the prompt response.

**Comment by gautamsamal** [comment]
The issue seems to be with declaring `tempListeners` as global. 
https://github.com/theophilusx/ssh2-sftp-client/blob/98c60b113aed64377923c2579714536607345751/src/utils.js#L61
Since I have two clients here doing one operation each, `read` gets completed before `write` and it clears up the all the 6 listeners for both. But it actually clears up 3 listeners since the `removeTempListeners` is being called on a specific client.

Moving the `tempListerners` array into the context of client seems fine and works with respect to the client.
```
function removeTempListeners(obj, name) {
  obj.debugMsg(`${name}: Removing temp event listeners`);
  obj.tempListeners.forEach(([e, fn]) => {
    obj.client.removeListener(e, fn);
  });
  obj.tempListeners = [];
}
```
Although I can imagine having parallel operations on same client f.e. two reads or writes will decouple the listeners as soon as the first operation completes!

**Comment by theophilusx** [comment]
Yes, I think your right. Let me have a look at it and I'll see if I can
refactor things to ensure the temp listeners are in the client rather
than global.

There is a favour I'd like to ask. There are some fairly minor changes
in the current master which have been done to address a small issue
found by another user. I'm looking to test it before releasing a new
version. Your use case could be a good test. Would you be willing to try
running from the master HEAD and see if all works as expected (with the
exception of the listener issue you identified)? It would just be good
to have another person test it before I release a new minor version.

In the meantime, I'll try to look at the listener refactoring - may be a
few days as I'm in the middle of switching to a new desktop.

**Comment by gautamsamal** [comment]
Sure! Since I am working on this, I'll test the latest master with my use-case. If things work out, I could create a PR for fixing temp listeners as well. Let's see!
