### ISSUE TITLE
Can I upload the zip package and then unzip it

### ISSUE THREAD

**Issue by ccbyland** [theophilusx/ssh2-sftp-client#367]
Can I upload the zip package and then unzip it

**Comment by theophilusx** [comment]
There is no obvious clever way to do this which jumps out at me. The key
problem is, you really need the unzipping to be executed by the remote
server. All you get from this (client) end, is a writeStream you can
pipe data into. You need something on the remote server which will
execute the unzip after the file has been uploaded and there is no
'general' execute facility provided by the sftp protocol to do this.

The ssh2 library which ssh2-sftp-client uses does provide a general ssh
capability,. This means that if you can also ssh into the remote host
(not just sftp), then you could use the ssh2 library to make an
additional connection after you have done the sftp file transfer and
unzip the file. However, the files you are uploading would need to be
very large to make the additional complexity and processing overheads
beneficial. It could end up being faster just uploading without
compressing the data and avoid the additional complexity.

Note that many sftp servers have 'built-in' connection compression as
well and if the remote sftp server supports concurrent processing of
data connections, the performance improvement from compressing a file,
uploading it and then decompressing it on the remote end may not be as
good as just uploading an uncompressed file using fastPut() with
compression enabled and avoiding the overhead of uncompressing the data
anyway.

I would start by doing some testing to verify that uploading compressed
files compared to uncompressed files really provides significant enough
performance improvement to justify the additional complexity of an
additional local compress and remote decompress process. The difference may not be as large as you
would expect - especially if the server supports connection compression
as well and that is enabled (via the options passed in to the connect
call). Make sure to include the compress and decompress overheads in the
comparison - too often, people only look at the raw transfer rates and
neglect to also consider the compress and decompress steps in the total
transfer time.
