### ISSUE TITLE
creatReadableStream Issue

### ISSUE THREAD

**Issue by alexalexiuc** [theophilusx/ssh2-sftp-client#37]
I had a verry strange issue on my side because of highWaterMark. In case it is biger than 65535, then each chunk has length 65535 max but the file is splited by 65536, and one bite is lost between each chunks. It would be verry nice If will be added highWaterMark parameter to function get

**Comment by orhankutlu** [comment]
@alexalexiuc we are having exactly the same issue!! Found any solution so far?

**Comment by orhankutlu** [comment]
@jyu213 i am having exactly the same issue. Any comment on that?

**Comment by alexalexiuc** [comment]
@orhankutlu Unfortunately I didn't found where is the problem, but I solve it setting highWaterMark property to 65535, because by default in ssh2-strams module it is setted to 65536, and in this case the last bite is getting lost. Try to edit SftpClient.prototype.getOptions from ssh-sftp-client/src/index.js, add new property to retruned object highWaterMark, and set it < 65536, or use createReadStream method from module ssh2, setting in the second parameter an object {  highWaterMark: 65535 }

**Comment by orhankutlu** [comment]
@alexalexiuc i tried 65535 still having same problem for bigger file.

**Comment by maximeloizeau** [comment]
I was able to fix it with the highWaterMark options for large files (well 5MB text file).

**Comment by theophilusx** [comment]
The module has moved on a lot from when this issue was first logged. I'm closing it as I don't think the original issue is still valid. Current versions of the module allow the lclient to pass any of the valid optional parameters to the underlying ssh2/ssh-streams library.
