### ISSUE TITLE
How to use ssh2 `exec` method in the ssh2-sftp-client

### ISSUE THREAD

**Issue by hardik-singhal** [theophilusx/ssh2-sftp-client#378]
I am unable to find any method that can execute the custom commands in the terminal of our client, for instance ssh2 library has method conn.exec("whoami"); Please share your thoughts on this.

**Comment by hardik-singhal** [comment]
Found it in previous closed issues. Not Possible to do that !!!

**Comment by theophilusx** [comment]
Correct. ssh2-sftp-client is an sftp client, not a general ssh client.
The functionality your looking for is not part of the sftp protocol.
