### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by zone44** [theophilusx/ssh2-sftp-client#38]
Could you please provide more examples. For instance, how would you download mulitple files ?

**Comment by theophilusx** [comment]
A good place to find examples is to look at the test cases in the test directory. 

The module currently does not have any 'globbing' capability, so to download multiple files, you would first get a listing of the directory and then just loop through the list and call fastGet(). As every method returns a promise, you can even push each call to fastGet into an array and then call Promise.all() to process them.
