### ISSUE TITLE
Option to use put instead of fastPut for uploadDir

### ISSUE THREAD

**Issue by air2** [theophilusx/ssh2-sftp-client#380]
Because I have some problems with some server (exavault.com) when using fastPut I would like to see the option to use the put method on the uploadDir function.

See also (https://github.com/mscdex/ssh2/issues/1120)

**Comment by theophilusx** [comment]
There are a few significant changes for the upload/download dir methods. I'll keep this request in mind (but cannot promise anything of course!)

**Comment by air2** [comment]
Ok, currently I just replace the fastPut like this:

```
function repairFastPut(this: Client, localPath: string, remoteFilePath: string, _options?: FastPutTransferOptions): Promise<string>{
    return this.put(localPath, remoteFilePath);
}

Client.prototype.fastPut = repairFastPut
```

To work around this issue. But there are more people who are having problems with fastPut in the ssh2 package. So if that issue gets fixed there is not much need for this feature I guess. I am not sure if and how fast that issue get fixed, until that time the uploadDir functionality is not working correctly and this code could be used as a simple work around.

**Comment by jungdaniel** [comment]
I tried to use `uploadDir` and had the same issue as @air2. Overwriting `fastPut` did the trick for me. Smaller files were uploaded correctly btw, but with larger ones I had issues. This error was thrown:
```
Error: fastPut: Operation unsupported (code: 8)
```

This part seemed relevant from the debug log:
```
SFTP: Outbound: Sent WRITE (id:9)
SFTP: Outbound: Sent WRITE (id:10)
...
SFTP: Inbound: Received STATUS (id:9, 0, "Success")
SFTP: Inbound: Received STATUS (id:10, 8, "Operation unsupported")
```

(Thank you for working on this lib.)

**Comment by jungdaniel** [comment]
node: v17.4.0
ssh2-sftp-client: ^7.2.2

I tried to upload to Akamai's NetStorage.

**Comment by theophilusx** [comment]
This error indicates Akamai's net storage does not support concurrent upload/download. These broken sftp server implementations are a real pain as it means I have to dumb down things and/or add complexity. 

For now, I'll change the uploadDir/downloadDir to use get/put rather than fastGet/fastPut. At some later point, I'll see about adding an option to allow the user to select fastPut/fastGet.

**Comment by theophilusx** [comment]
This change has been added to HEAD of mster branch and will be in the next release.

**Comment by bombino** [comment]
Just wanted to update this old thread to clarify that ExaVault.com (mentioned in the OP) and its successor company Files.com, are fully compatible with fastPut, as implemented in this package.
