### ISSUE TITLE
Any way to make a file appear on the SFTP server after a full upload only?

### ISSUE THREAD

**Issue by A3a3e1** [theophilusx/ssh2-sftp-client#388]
First of all, thank you @theophilusx very much for what you keep doing!

Context: we use the library to upload (put) files to an SFTP server. The files are periodically retrieved from there by a 3rd party tool automatically.
As we use streams to put files, the 3rd party tool often downloads files that are not 100% uploaded yet.
The question is - is there any way (except for some manual file renaming with some kind of 'draft' prefixes) to make files "visible" AFTER they are 100% uploaded only?

**Comment by theophilusx** [comment]
There is nothing in the ssh2 API to directly help with this. Best I can
suggest is that you upload the file with a temporary name (like
file.part or file.upload) and then after the upload has completed,
rename the file to its final name. You would then tell your client not
to download anything with the .part or .upload extension.

Might seem a little clunky, but this is basically what chrome does when
you download a file (it uses the .part extension).
