### ISSUE TITLE
Error: connect->getConnection: Unexpected end event raised

### ISSUE THREAD

**Issue by zhangbaojia** [theophilusx/ssh2-sftp-client#393]
[#346 ](https://github.com/theophilusx/ssh2-sftp-client/issues/346)

version:7+ not work
![7](https://user-images.githubusercontent.com/19427334/155693245-b9c64923-7bf8-46ef-bc08-6382ecf970ad.png)

version :6 is OK
![6](https://user-images.githubusercontent.com/19427334/155693234-255d5c79-dc1c-4f21-b302-edeb6317de8b.png)

**Comment by zhangbaojia** [comment]
Is it also the server configuration?

**Comment by theophilusx** [comment]
Sorry, but there is far too little information here for me to help. I
need to know

1. Exact ssh2-sftp-client version (should be 7.2.2)
2. Node version being used
3. Client platform (Linux, macOS, Windows etc)
4. Minimal reproducible example I can test with.

**Comment by zhangbaojia** [comment]
Thanks for your prompt reply，
I used ssh2[version(^1.6.0)] test also failed, should be the server problem。
Then, when I know why, I will continue to comment.

**Comment by zhangbaojia** [comment]
> Sorry, but there is far too little information here for me to help. I need to know 1. Exact ssh2-sftp-client version (should be 7.2.2) 2. Node version being used 3. Client platform (Linux, macOS, Windows etc) 4. Minimal reproducible example I can test with.

1、tested (ssh2-sftp-client) Version 7.0.2、7.2.1、7.2.2
2、**node** Version 14.18.0
3、**Client：** Win10,  **Server：**Linux linux 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux
4、code is shown in figure

**Comment by theophilusx** [comment]
I notice an unnecessary 'async' in your script. Don't do

.then(async () => {
  ....
})

it is unnecessary and could cause confusion. In general, seeing an
'async' in a promise chain is a 'code smell'. All you need is

.then(() => {
   ...
})

The error you are getting is saying that the connection was ended
unexpectedly. However, it isn't clear why. I would add a debug function
to see if it provides any additional information i.e.

sftp.connect({
  host: .....,
  port: 22,
  username: ....,
  password: ....,
  debug: (msg) => console.log(msg),
}).then(() => {
  console.log('Connected to server');
  return sftp.end();
}).then(() => {
  console.log('script finished');
}).catch(err => {
  console.log('Error', err);
})

**Comment by zhangbaojia** [comment]
oh, thanks。tests  ssh2 is not working after being  upgraded from 0.8.9 to 1.0.0。

**Comment by zhangbaojia** [comment]
tests ssh2 1.0.0+ , It doesn't have any output, so I don't know why。

**Comment by theophilusx** [comment]
If the issue is the same just using ssh2, then you will need to log an
issue with that project. A debug log will be critical in identifying the
issue. I would also try testing against ssh2 HEAD from the ssh2
repository in case there are fixes in the current master which have not
yet been pushed out to npmjs.com.

**Comment by zhangbaojia** [comment]
Thank you again for

**Comment by arinashilyaeva** [comment]
@zhangbaojia Hi, just curious, did you mange to solve the issue? I'm facing the same issue currently and I've been stuck for hours wondering what actually happed, as I cannot fully reproduce, but it happend in prod env of our app. Would appreciate your feedback

**Comment by zhangbaojia** [comment]
> @zhangbaojia Hi, just curious, did you mange to solve the issue? I'm facing the same issue currently and I've been stuck for hours wondering what actually happened, as I cannot fully reproduce, but it happend in prod env of our app. Would appreciate your feedback

no, Continue with the old version。`https://github.com/mscdex/ssh2/issues/1148`

**Comment by arinashilyaeva** [comment]
@zhangbaojia thanks a lof for the reply, downgrading seems to be the only option then, that's unfortunate
