### ISSUE TITLE
7z file getting corrupted during download

### ISSUE THREAD

**Issue by dhorialpesh** [theophilusx/ssh2-sftp-client#394]
Hi,

I'm trying to download .7z file from SFTP using this ssh2-sftp-client npm package and I notice compress file getting corrupted and when try to open the compress file it showing 'Cannot open file as archive' also notice file size is getting bigger then original one.

Have you guys test with downloading's 7z file or jpg from sftp ?. I tried with multiple sftp server and notice same issue.

I also tried to pass various encoding in sftp.get method but no difference in the result

For normal text file it work as expected.

**Comment by theophilusx** [comment]
As there has not been any further feedback on this issue for 3 weeks, I'm closing it.
