### ISSUE TITLE
Error: end: No SFTP connection available

### ISSUE THREAD

**Issue by gaurav16694** [theophilusx/ssh2-sftp-client#395]
I am getting this error intermittently

`Error: end: No SFTP connection available`

**Comment by MykhailoDiachenkoDevPro** [comment]
to add details about env / code snip / version of lib node.js
If I were the author, I would close your request at all

**Comment by theophilusx** [comment]
Do you seriously expect any meaningful response when you log an issue
like this?

The amount of effort I'm prepared to put into assisting in the
resolution of an issue is directly proportional to the amount of effort
you are prepared to put into reporting it.

That amount has now reached its limit.
