### ISSUE TITLE
Exists and List methods resolving remotePath differently

### ISSUE THREAD

**Issue by Rioos** [theophilusx/ssh2-sftp-client#397]
Hey all,

I've upgraded the lib from version 5.2.1 to 7.x version and realize it caused some of my SFTP connections to fail.

Basically, I designed that to before executing a `list` I execute a `exists` on the remotePath. Problem is, before on version 5.2.1 list and exists would normalize the path, if I was passing a relative path it would first resolve it and then execute the command. 

`exists` still does that, but `list` does not do that anymore. 

Is it an intended breaking change? If so, it would be good to report that to the users. If that is a bug, I would love to help on solving.

Thanks,
Ricardo.

**Comment by theophilusx** [comment]
It looks like this could be an oversight on my part while trying to optimise
performance. A lot of additional error checking was removed in v7.x to
improve performance. Most of these checks were done to provide better
error messages as the 'default' errors from many SFTP servers are
extremely terse and generic (i.e. 'Error 4' or just 'Failure'). However,
doing these additional checks adds at least one additional remote call
(in some cases more) to each command.

In the case of list(), I thought the underlying ssh2 readdir() call
normalised the path as part of the call, but if your getting errors when
you use list() with a relative path, perhaps it doesn't or doesn't with
all sftp servers.

I will add back the normalizePath() call to list() (and verify other
methods are OK) in the next few days and push out a new version.

**Comment by Rioos** [comment]
Thanks for the update @theophilusx.

**Comment by theophilusx** [comment]
Now that I've gone back an looked at this more closely, I recall that the call to normalizePath was deliberately removed because it was not necessary for the list() method as this method does the path normalisation automatically. As removing this reduces network requests and as it is not needed it was removed. 

Are you seeing an error? If so, what error are you seeing?

**Comment by theophilusx** [comment]
As there has been no response on this issue and I'm now pushing v8.0.0, I'm closing it. We can reopen it if a specific issue is identified.
