### ISSUE TITLE
why python is nessary?

### ISSUE THREAD

**Issue by xiyuanyuan** [theophilusx/ssh2-sftp-client#401]
node:  v14.19.1
ssh2-sftp-client: ^7.2.3

> ssh2@1.8.0 install D:\mycode\new-edsweb\node_modules\ssh2
> node install.js

D:\mycode\new-edsweb\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "D:\nvm\v14.19.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v14.19.1 --real_openssl_major=1 rebuild )  else (node "D:\nvm\v14.19.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v14.19.1 --real_openssl_major=1 rebuild ) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (D:\nvm\v14.19.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (D:\nvm\v14.19.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\nvm\v14.19.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (D:\nvm\v14.19.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "D:\\programs\\node.exe" "D:\\nvm\\v14.19.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v14.19.1" "--real_openssl_major=1" "rebuild"
gyp ERR! cwd D:\mycode\new-edsweb\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding

**Comment by theophilusx** [comment]
The failure is in an optional dependency only required if you want to use faster native crypto algorithms rather than the default node ones. It isn't an error, just a warning telling you that optional native crpto module is not being used. 

This is an optional ssh2 dependency and nothing to do with ssh2-sftp-client, which just uses ssh2. For more details, please visit the ssh2 project.
