### ISSUE TITLE
Security Configurations

### ISSUE THREAD

**Issue by questiosn9832** [theophilusx/ssh2-sftp-client#405]
Hi,

I am reaching out to get an idea of how someone can make granular configuration changes to further secure usage of the SFTP code.

For example would I be able to edit an SSHD config file that would be respected?

**Comment by questiosn9832** [comment]
To be a little more specific I see this module https://github.com/theophilusx/ssh2-sftp-client uses https://github.com/mscdex/ssh2#client and I want to see how I would be able to disable x11 (Set to true)

**Comment by theophilusx** [comment]
I think you have things a little confused. This module provides the client side for interacting with an sftp server. It is restricted to the commands which make up the sftp protocol i.e. FTP protocol. The sshd configuration is part of the server and it would be a critical security vulnerability if the client could modify an sftp servers configuration. 

The ssh2 module which this module uses is a more general ssh2 module which does support the facilities of ssh, such as opening a remote shell. So, if you can use the command line to ssh into the remote server and use something like sudo to edit the sshd.conf file on the server, then you could replicate that using the ssh2 modulle. 

X11 also has nothing to do with sftp. X11 is only relevant with respect to redirecting the GUI output of a remote application to the local display. As there is no GUI output with sftp, it has no purpose. 

From a client perspective, I don't understand what configuration concerns you might have which you feel need to be addressed/changed. What are the specific security risks you have identified which you feel need mitigation?

**Comment by questiosn9832** [comment]
Thank you for the follow up. Some things I want to be able to lockdown in sftp server include stuff like max sessions/connections, failed login attempts banning, idle time out etc. Ideally want to be able to see server configuration and how to edit/change it.

**Comment by theophilusx** [comment]
This is a system administration issue and well outside the role/purpose of ssh2-sftp-client. Obviously, you cannot modify the sftp server configuration unless it is under your administration/control. If it is, then you just need to edit the sshd.conf file, which is typically located in the /etc directory on the host where the sftp daemon is running. You need to read the man pages/documentation for your sftp server for details.
