### ISSUE TITLE
works locally, but not on heroku (but this maybe isn't an ssh2-sftp-client issue)

### ISSUE THREAD

**Issue by joshpsawyer** [theophilusx/ssh2-sftp-client#408]
This is a frustrating issue, because it makes no sense. I've got a script that takes a file from one sftp, modifies it and puts it in another sftp. This script works locally using the `password` authentication method:

```Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
```

When deployed on Heroku, it can't negotiate the USERAUTH:

```bash
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_FAILURE (publickey)
Client: password auth failed
Outbound: Sending USERAUTH_REQUEST (keyboard-interactive)
Inbound: Received USERAUTH_FAILURE (publickey)
Client: keyboard-interactive auth failed
CLIENT[sftp]: getConnection Error: Handling error: All configured authentication methods failed
CLIENT[sftp]: getConnection Error: handled error with reject
```

but I can successfully connect to the sftp server using the CLI sftp command. This doesn't seem like an ssh2-sftp-client issue, but maybe you know what's going on? Why would the server offer different authentication methods depending on the client? Is there some configuration I'm missing in the package that would bypass this?

**Comment by joshpsawyer** [comment]
Another thought: if it was the server restricting the password authentication method based on the server IP address, then I wouldn't be able to sftp into it with the CLI. Maybe this is an ssh2-sftp-client configuration issue after all?

**Comment by theophilusx** [comment]
There is nothing obvious I can think of which would explain this. Suspect you will have to break things down to a minimal reproducible case and try to isolate what is different.

**Comment by joshpsawyer** [comment]
Thanks! I'll close the issue until / if I get something I can reproduce.
