### ISSUE TITLE
DevTools was Disconnected from the page

### ISSUE THREAD

**Issue by hadiarakos** [theophilusx/ssh2-sftp-client#41]
Hello. 
Suddenly Im getting this mysterious error.    

![image](https://user-images.githubusercontent.com/16122234/33982330-c8c63d88-e0b8-11e7-9dd7-dfb48e0e39a7.png)

Can you help please ? 

Thank you.

**Comment by jyu213** [comment]
what? maybe this is the problem for chrome... 
you can reinstall it

**Comment by hadiarakos** [comment]
Hello, 

I role back my code and it works again. 
Maybe a NodeJS module break something . 

Thank you. 

On 14 December 2017 at 7:41:20 PM, 见见 (notifications@github.com) wrote:

what? maybe this is the problem for chrome...
you can reinstall it
