### ISSUE TITLE
node 18 : Cannot set property closed of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by rafipiccolo** [theophilusx/ssh2-sftp-client#410]
following code returns an error when using node 18.

ps :
- works on node 17
- sftp.list works on 17 and 18.
- i use latest package versions (in particular ssh2/ssh2-sftp-client)

```
let sftp = await sftp.connect(...);
let x = await sftp.get('/xxx.xml');
console.log(x);

----------

/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:3389
  this.closed = false;
              ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at new ReadStream (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:3389:15)
    at SFTP.createReadStream (/root/docker/push/node_modules/ssh2/lib/protocol/SFTP.js:305:12)
    at /root/docker/push/node_modules/ssh2-sftp-client/src/index.js:479:25
    at new Promise (<anonymous>)
    at SftpClient.get (/root/docker/push/node_modules/ssh2-sftp-client/src/index.js:475:12)
    at file:///root/docker/push/testrawmaileva.js:20:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.0.0
```

**Comment by theophilusx** [comment]
Looks like your code is missing a destination i.e. 

> let x = await sftp.get('/xxx.xml');

The get() method expects two arguments, source and destination.

**Comment by rafipiccolo** [comment]
According to the documentation dst can be ommited and the data should be returned :

```
If dst is undefined, the method will put the data into a buffer and return that buffer when the Promise is resolved
```

i like to be able to only get the data in a buffer instead of a creating file on the disk.

is it still a thing ?


i have a similar error with sftp.put (when using 2 parameters : src, dst)
the error is : 
```
Cannot set property closed of #<Writable>
```

**Comment by theophilusx** [comment]
No, there is nothing to do from the ssh2-sftp-client perspective. Provided the new version of ssh2 is still 1.x, ssh2-sftp-client will pick it up as its dependency automatically. I will push out a new version once ssh2 is pushed though as there are some minor updates in ssh2-sftp-client which need to go out anyway.

**Comment by theophilusx** [comment]
Just pushed version 8.1.0, which uses ssh2 1.10.0. This should resolve the issue, so closing this now.
