### ISSUE TITLE
Feature: fastPut/put Selector

### ISSUE THREAD

**Issue by obrhaberer** [theophilusx/ssh2-sftp-client#413]
"OK, that now makes more sense. No, there is no switch to select fastPut instead of put. Unfortunately, there were just too many sftp servers which did not support fastPut to keep it as the default. I do have a note to add a switch which would allow fastPut, but not sure when I will get to that."

_Originally posted by @theophilusx in https://github.com/theophilusx/ssh2-sftp-client/issues/402#issuecomment-1093476285_

**Comment by theophilusx** [comment]
This feature as now been added to uploadDir and downloadDir methods. Both these methods have also been changed to transfer files using asynchronous processes (regardless of which method is used for the transfer), so should see performance improvement for both put/get and fastPut/fastGet. 

These changes are in the master branch. Would be great if you have time to test before I release verison 9.0.0. There are also some other changes in this version, some of which are API breaking, so check the README.

**Comment by obrhaberer** [comment]
I can confirm the performance improvements for the methods. Also the previous listener-warnings are gone. Thanks for the good work.
