### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by mohit8285** [theophilusx/ssh2-sftp-client#416]
Node version 15.14.0
npm version 7.7.6

Error in file :
dir/node_modules/ssh2-sftp-client/src/index.js:1250 
 if (options?.filter) {
                 ^
SyntaxError: Unexpected token .

Getting this error after install ssh2-sftp-client npm. Please help !
Any ideas what am I doing wrong? Clearly I do not understand something obvious. Could you point me in the right direction?

**Comment by theophilusx** [comment]
Can you show a minimal sample script which is generating this issue? I
cannot reproduce it with node v15.14.0, v14.19.1 or v18.1.0 using
ssh2-sftp-client 9.0.0

**Comment by mohit8285** [comment]
Sure, let me share

This is the simple script that i am using to move the file local to remote server And its working fine. 
But problem is inside : node_modules/ssh2-sftp-client/src/index.js:1250
That is i already mentioned above.

Script :

    let data = fs.createReadStream(localPath);
    var writeStream = remotePath;
    conn.connect(config)
        .then(() => {
            console.log("CLIENT : READY");
            return conn.put(data, writeStream);
        })
        .then(() => {
            conn.end();
            callback({"type":"success"});
        })
        .catch((err: any) => {
            console.error(err);
            callback({"type":"error"});
        });

Please check this.
Thanks for your efforts.

**Comment by theophilusx** [comment]
It isn't clear to me where you are seeing/getting that error and I
cannot reproduce it. I can run your example script with minimal
modification and it works fine with no errors. 

The error you are seeing is not correct - there is no syntax error in
the file.  You should only see that error if your running a version of
node <14.19 as that syntax was not introduced into node until v14. 

The changes I made to your sample script were to remove the references
to some function called 'callback', which is not defined and to remove
what looks like a typescript type specifier in the catch clause. 

My guess would be that either you have a very old version of typescript
or a typescript configuration error or perhaps you are using some other
tool, like eslint, which is misconfigured or restricting permitted node
versions to a version prior to the introduction of the ?. syntax e.g.
the ?. syntax is not supported in node versions <14.x

You are running v15.x of node and while I don't see the error with that
version, you really should upgrade to at least v16. (the odd numbered
versions of node are development versions and should not be used after
the next production version is released i.e. after v16 was released).
The version of npn your running is also old (I'm running 8.11.0). Current
node LTS version is 16.15.1 and latest node version is 18.3.0

I was able to run your script with no errors/warnings with node versions
14.19.1, 15.14.0, 16.15.1 and 18.3.0

My guess is you need to upgrade your typescript version/configuration.

**Comment by arash-bizcover** [comment]
Same problem, It should be related to NodeJS version

**Comment by theophilusx** [comment]
@arash-bizcover Not sure what you mean. As already stated, versions prior to v14 are not supported. Current v14 onwards work fine. If your running v14 or higher and seeing this error, then either it is because your using an outdated typescript compiler or you have something like eslint configured to generate errors when using newer JS features.
