### ISSUE TITLE
running command as different user

### ISSUE THREAD

**Issue by reidsneo** [theophilusx/ssh2-sftp-client#418]
Hello how do running command with different user?
Below is using typescript with will sleep for 1 second before virtually typing the password

```
conn.exec("sh -c 'sleep 1; echo p4ssw0rd' | /usr/bin/script -qc  'su -c 'whoami' - root '", (err, stream) => {
    if (err)
    {
        console.log(err);
    }else{
        stream.on('close', (code, signal) => {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', (data) => {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', (data) => {
            console.log('STDERR: ' + data);
        });
    }
});
```

it didn't return as expected
only return 

`STDOUT: Password: `

which is working on other platform
for example PHP
`
$sftp->exec('sh -c "sleep 1; echo p4ssw0rd" | /usr/bin/script -qc  \'su -c "whoami" - root \'');`

would return
```
Password: 
root
```

Thanks!

**Comment by theophilusx** [comment]
You have submitted this issue to the wrong project. This repository is
for the ssh2-sftp-client module, which does not support executing
commands over ssh. It only supports using sftp.

You probably want the ssh2 project.

**Comment by reidsneo** [comment]
Oh no!, this is so embarrassing, after tracking the load it was using pure ssh2
again, sorry for wrong room
