### ISSUE TITLE
Mismatch between last lib version and last DefinitelyTyped version

### ISSUE THREAD

**Issue by cbyad** [theophilusx/ssh2-sftp-client#422]
you wrote this about version breaking changes :

> Breaking Change: This list() method no longer accepts a regular expression for filtering the entries to be returned. You can now specify a filter function instead. The function is called for each item in the list of items to be returned, passing in the item object as its only argument. Essentially, this is just a call to Array.filter(), so the filter function should behave in the same way i.e. return true for items to be retained and false for those to be dropped.

But from `@types/ssh2-sftp-client: "^7.0.1"`, the expected signature of the `list` function is :
 ```ts
list(remoteFilePath: string, pattern?: string | RegExp | undefined): Promise<sftp.FileInfo[]>
```

Maybe an update is required.
Thanks

**Comment by theophilusx** [comment]
I have nothing to do with @types/ssh2-sftp-client. It is not part of
this project or repository and I have no access to update it, nor do I
use typescript.
