### ISSUE TITLE
Copy/Override files recursively under a folder

### ISSUE THREAD

**Issue by ramesh-git** [theophilusx/ssh2-sftp-client#43]
I am new to this module and by exploring I could able to connect to my server and able to copy a file using sftp.put method. But I wanted to copy some set of files recursively within a folder to my FTP server.

Is there any best way to do this. If this issue already exists and duplicate please guide me where I can figure out the solution.

Thanks in advance.

Ramesh

**Comment by theophilusx** [comment]
This is something you need to manage in your client code. The module provides the basic infrastructure to upload/download files - your code needs to determine which files to upload/download.  BAsic idea would be to do something like pushing a list of dile paths into an array and then pass that array to a function which would open an sftp connection and then use fastPut or fastGet to upload/download each file.
