### ISSUE TITLE
connect(...) promise never rejected with wrong private key

### ISSUE THREAD

**Issue by jer-sen** [theophilusx/ssh2-sftp-client#430]
When I try to connect to a server with a wrong private key, if it's wrong (change a letter in the key), the promise is never resolved nor rejected.

```
await (new SftpClient()).connect({
        host: configuration.host,
        port: configuration.port,
        username: configuration.username,
        privateKey: configuration.openSshCertificate,
      });
```

When the private key is correct, every thing is ok.

ssh2@1.11.0
ssh2-sftp-client@9.0.3

**Comment by theophilusx** [comment]
Yes, there does seem to be an issue here. It looks like the 'retry'
mechanism is eating the connection errors. In my tests, the scripts do
exit, but silently with no errors (it may take a while if you are doing
multiple retries and have larger timeouts).

I think I've got to the point I'm going to rip out the retry mechanism
completely I've never liked it and it has been the source of multiple
problems, plus it complicates the code far more than any benefit it
brings (reality is, it is very rare for the initial connection to fail
and then work on subsequent retries. More often than not, if it fails and
remains failed regardless of how many times you try). Besides, if
someone really wants to use retry, they can add it around the connect
method themselves in their own code. Think I prefer to keep this module
simpler and avoid trying to be too clever. 

Will look at removing, updating API and pushing a new version over the
next week or so.

**Comment by theophilusx** [comment]
Have pushed a fix which should address this issue. Now, when the private key cannot be processed, you should get an error stating the private key could not be parsed with some details indicating why not. 

Plase test and let me know if it fixes your problem. I will push a new 9.0.4 version next week.

**Comment by jer-sen** [comment]
Thanks. I won't be able to test it before the 9.0.4 release.

**Comment by jer-sen** [comment]
@theophilusx it seems to work! You can push the fix in a new version!

**Comment by gpjeeves** [comment]
@theophilusx Thanks for the fix! Can you please publish the new version? Thanks!

**Comment by theophilusx** [comment]
Version 9.0.4 pushed to npmjs.com
