### ISSUE TITLE
downloadDir's dstDir can be stream?

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#432]
just like get method, and uploadDir also have the need.

## downloadDir
![image](https://user-images.githubusercontent.com/9245110/187191013-d4703d7f-a980-4731-949f-c9237e2842ed.png)

## get
![image](https://user-images.githubusercontent.com/9245110/187191030-e0b91628-4802-464c-8e9b-fa289fbc815b.png)

**Comment by theophilusx** [comment]
No, these methods do not support stream and it isn't clear exactly what the right semantics would be for such a feature. i.e. if your downloading many files and directories, why would you want to write them all to the same stream? If you wanted to write each file to its own stream, how would you specify the list of streams? 

If you want this functionality, you can implement it yourself using the available methods like createReadStream and createWriteStream.
