### ISSUE TITLE
@types/ssh2-sftp-client using outdated list parameters

### ISSUE THREAD

**Issue by cah-james-arnold01** [theophilusx/ssh2-sftp-client#435]
https://www.npmjs.com/package/@types/ssh2-sftp-client

The types package is still referencing the `list(remoteFilePath, pattern)` and breaks the typing of the latest ssh2-sftp-client package, which now uses the filter function.

**Comment by theophilusx** [comment]
I don't have anything to do with the @types/ssh2-sftp-client package. You need to lodge this issue with whoever maintains that package.

**Comment by theophilusx** [comment]
I don't have anything to do with the @types/ssh2-sftp-client package and
so cannot update/modify/fix it. You need to report this to @types
project.

**Comment by cah-james-arnold01** [comment]
I'll reach out there and hopefully get the issue addressed. Appreciate the response.
