### ISSUE TITLE
Error check:  throw new Error('Unable to detect compiler type');

### ISSUE THREAD

**Issue by thesuhu** [theophilusx/ssh2-sftp-client#446]
When install the package on Windows, got error  throw new Error('Unable to detect compiler type'). But the package workfine. List, upload successfuly tested on Windows.

Can you disable compiler check on Windows?

**Comment by thesuhu** [comment]
sorry i close the issue, cpu check is on ssh2 package dependencies

**Comment by theophilusx** [comment]
o
This 'error' is actually just a warning telling you that the optional
ssh2 dependency on cpu-freq was not able to be installed. I cannot do
anything about it as it is from the ssh2 module, not ssh2-sftp-client.

There have been many discussions regarding this issue on the ssh2
project site and there is some work to find ways of avoiding the issue.

It does not affect the operation of ssh2 or ssh2-sftp-client.

**Comment by thesuhu** [comment]
Thank you
