### ISSUE TITLE
v9.0.4 - get/put options are overwritten by defaults

### ISSUE THREAD

**Issue by dimbslmh** [theophilusx/ssh2-sftp-client#447]
Caused by https://github.com/theophilusx/ssh2-sftp-client/commit/dc262b6cf757974adb780cd078adf730d219254d

https://github.com/theophilusx/ssh2-sftp-client/blob/b308ca662776ff6ed1667288777accbd8ed92fc9/src/index.js#L498-L507

https://github.com/theophilusx/ssh2-sftp-client/blob/b308ca662776ff6ed1667288777accbd8ed92fc9/src/index.js#L697-L706

Solution (keeping the defaults for readStreamOptions/writeStreamOptions/pipeOptions):

```ts
     opts = { 
       readStreamOptions: { ...opts.readStreamOptions, autoClose: true }, 
       writeStreamOptions: { ...opts.writeStreamOptions, autoClose: true }, 
       pipeOptions: { ...opts.pipeOptions, end: true }, 
     }; 
```

**Comment by theophilusx** [comment]
This is deliberate. Changing those options creates problems with promise
resolution and implementing the code to handle those problems severely
complicates the put/get functions.

If you need to change options at this level, you need to use the
supplied createReadStream and createWriteStream functions, which will
give you full low level access.

**Comment by dimbslmh** [comment]
> **Breaking Change**: The ability to set **autoClose** on read and write streams and the ability to set **end** on pipe operations has been removed. These options caused confusion for users and were too easy to get wrong, plus it made the methods overly complicated.

@theophilusx Yes, from what I understood is that you want to prevent the user to set `autoClose` on read and write streams and the `end` on pipe operations. The `autoClose` and `end` options only. CMIIW.

The solution above will keep preventing the mentioned options from being changed by the user, because your default options will overwrite the user provided options (they are set _after_ the spread syntax).

> two new methods have been added, createReadStream() and createWriteStream(). However, it should be noted that client code is 100% responsible for managing streams obtained using these methods.

Using the new createReadStream and createWriteStream is essentially asking the user to duplicate existing code.

**Comment by theophilusx** [comment]
Nadim Basalamah ***@***.***> writes:

>  Breaking Change: The ability to set autoClose on read and write streams and the ability to set end on pipe operations has
>  been removed. These options caused confusion for users and were too easy to get wrong, plus it made the methods overly
>  complicated.
>
> @theophilusx Yes, from what I understood is that you want to prevent the user to set autoClose on read and write streams and
> the end on pipe operations. The autoClose and end options only. CMIIW.
>
> The solution above will keep preventing the mentioned options from being changed by the user, because your default options
> will overwrite the user provided options (they are set after the spread syntax).

What other options are you concerned about? 

>
>  two new methods have been added, createReadStream() and createWriteStream(). However, it should be noted that client
>  code is 100% responsible for managing streams obtained using these methods.
>
> Using the new createReadStream and createWriteStream is essentially asking the user to duplicate existing code.

I disagree. Once you change those options, the exiting code does not
work. You have to implement the functionality in a different way i.e. a
different design approach is needed to get reliable get/put
operations. If it was just duplicating the same code to get it to work,
then it wouldn't be necessary to prevent setting those options. 

The big issue here is with how to implement a general solution which
would work for all combinations of those options. There are a number of
trivial cases where almost identical code will mostly work. However,
there are many other cases where it doesn't. If your providing
functionality in a library, you need to satisfy the general case, not
just the simple trivial case. When you cannot provide the general
solution without significantly complicating the most common use case,
I think it is better to restrict the basic case and provide the tools
necessary for users to implement their specific case.

**Comment by dimbslmh** [comment]
> I think it is better to restrict the basic case and provide the tools
necessary for users to implement their specific case.

Ok, no problem.

> What other options are you concerned about?

The mode option. I'll just use call the `chmod` method after the initial request.

**Comment by theophilusx** [comment]
Actually, having looked at the code, I *think* I see what your getting
at.

What you would prefer is something like

if (opts?.readStreamOptions?.autoClose === false) {
  opts.readStreamOptions.autoClose = true;
}

and similar for writeStreamOptions and pipeOptions
instead of

opts = {
        ...opts,
        readStreamOptions: { autoClose: true },
        writeStreamOptions: { autoClose: true },
        pipeOptions: { end: true },
      };

???

Probably more correct and I'll see about doing that before next
release. I think it is low priority.

**Comment by theophilusx** [comment]
Nadim Basalamah ***@***.***> writes:

>  I think it is better to restrict the basic case and provide the tools
>  necessary for users to implement their specific case.
>
> Ok, no problem.
>
>  What other options are you concerned about?
>
> The mode option. I'll just use call the chmod method after the initial request.
>

This should only be a problem with put(). For get() you can avoid it by
passing in a stream object as the second argument. For put() you will
need to use chmod() for now.

**Comment by dimbslmh** [comment]
It's unnecessary to add the if statement.

```ts
{ ...{ autoClose: false }, autoClose: true }
```

or even

```ts
{ ...undefined, autoClose: true }
```

will end up being: 

```ts
{ autoClose: true }
```

`undefined`/`null` spread won't give an error inside an object.

**Comment by theophilusx** [comment]
Looking at this now. Interesting you say the if statement is not necessary. However, as the parent properties i.e. readStreamOptions, writeStreamOptions and pipeOptions may not exist, I cannot see how your solution will work (it would work if you can guarantee those properties always exists, but that isn't the case). Am I missing something here?

**Comment by dimbslmh** [comment]
You are right, opts is not always given by the user. It should work like this:

```ts
     opts = { 
       readStreamOptions: { ...opts?.readStreamOptions, autoClose: true }, 
       writeStreamOptions: { ...opts?.writeStreamOptions, autoClose: true }, 
       pipeOptions: { ...opts?.pipeOptions, end: true }, 
     }; 
```

**Comment by theophilusx** [comment]
Thanks. Came up with same solution. Just wanted to verify I wasn't missing something. 

Have pushed a fix into git which will be in next release (couple of other issues to clean up before I can push a new version).
