### ISSUE TITLE
stat mode is different to understand

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#449]
![image](https://user-images.githubusercontent.com/9245110/202996501-ec9362fd-bb45-4da4-9f6b-c595921b04ce.png)
https://github.com/theophilusx/ssh2-sftp-client#sec-4-2-5

how to convert to rights , just like list return 

https://github.com/theophilusx/ssh2-sftp-client#sec-4-2-3

![image](https://user-images.githubusercontent.com/9245110/202996720-2f2d0a6a-cdab-4927-8b1d-2472480b9a62.png)

**Comment by theophilusx** [comment]
The mode is a bit-field. It is the same as the mode in the value
returned by fs.stat et. al. See the node file system module
documentation for details. Basically, there are constants defined by
node which you use to AND with the mode to determine various bits of
information about the file, including different access rights, file type
etc.

**Comment by alanhg** [comment]
> 

got it. thank you.

```javascript
(rslt.mode& parseInt('777', 8)).toString(8)
```
