### ISSUE TITLE
`client.connect` fails but doesn't reject or resolve

### ISSUE THREAD

**Issue by kpapadatos** [theophilusx/ssh2-sftp-client#451]
Hello, we have a service that checks every few minutes for files in an SFTP server. Pseudocode looks like this:
```ts
import Client from 'ssh2-sftp-client';

while (true) {
   await checkForFilesInSftpServer().catch(someHandler);
   await sleep(120e3);
}

async function checkForFilesInSftpServer() {
    const client = new Client();
    await client.connect({ ... });
    
    // ...
}
```

We have had several incidents over the past 2 years where we found the service in a state where `client.connect` never resolved or rejected, but the following message was printed in the logs: `connect ECONNREFUSED <address>:9200`. It seems that even though `client.connect` fails, it does not reject, resulting in the service waiting forever.

This could be due to a transient error or an SFTP server restart but currently, the library doesn't offer any way to handle it.

**Comment by theophilusx** [comment]
What version of ssh2-sftp-client?

What version of node?

What platform are you running on?

**Comment by kpapadatos** [comment]
@theophilusx 
```
ssh2-sftp-client@7.2.1
ssh2@1.5.0
```

Runs inside a `node:16.13.1-alpine3.15`  container managed by Kubernetes with Ubuntu 18.04 base OS.

**Comment by theophilusx** [comment]
You need to upgrade to latest ssh2-sftp-client. The 7.2.1 has numerous
bug fixes which are likely related to your issue.

Also, the ssh2 version is old and has numerous bug fixes. Upgrading to
latest ssh2-sftp-client should see that updated to 1.11.0 as well.

**Comment by kpapadatos** [comment]
@theophilusx It looks like the update fixed it, thank you.
