### ISSUE TITLE
[ERROR] fastPut: Backend does not support resume Local

### ISSUE THREAD

**Issue by gazal-k** [theophilusx/ssh2-sftp-client#461]
We use this library within AWS Lambdas for a lot of file based integrations, transferring to partner SFTP servers.

Most of them work flawlessly except for the SFTP server for Google Merchant Center. The SFTP server is `partnerupload.google.com`.
The error is not consistent. About half the time it fails, and then the automatic retry for the lambda generally goes fine. The error message is like:

`fastPut: Backend does not support resume Local: /tmp/a9b4f1a3-50d6-4420-8156-f80f840321e0 Remote: /<remoteFileName>`

We are using an older version of this library, but haven't found anything definitive about this error.

```
ssh2-sftp-client: 7.0.1
ssh2: 1.11.0
cpu-features: 0.0.4
```

Should we just upgrade the library? Use regular put instead of fastPut?

**Comment by theophilusx** [comment]
One of the problems with fastPut (and fastGet) is that it depends on
server functionality which isn't supported by all
servers. Unfortunately, as far as I know, there isn't a reliable
mechanism to know or test to see if the server supports it - either it
works or it doesn't.

Based on the error you seem to get, I suspect the server does not
support the underlying concurrency primitives used by
fastGet/fastPut. Smaller files probably transfer fine, but larger ones
will fail.

My advice would be to both upgrade to current version and for the server
where you get failures using fastGet/fastPut, use get/put instead.

**Comment by gazal-k** [comment]
Thanks @theophilusx, we'll verify that.
