### ISSUE TITLE
No documentation for the usage of sftp.get("/path/to/file") and it could be really helpful

### ISSUE THREAD

**Issue by camilo0365** [theophilusx/ssh2-sftp-client#463]
Hello,

I have a use case where I''m dealing with retrieving a file via SFTP and need a `Buffer` out of it. Reading the current `README.md` documentation, it wasn't clear how to be certain that the return type would be a `Buffer` given that the function's type signature is `get(path, dst, options) ==> String|Stream|Buffer`

An example like this:

```typescript
const fileAsBuffer = (await sftp.get("/path/to/file") ) as Buffer

// Do things with a Buffer...
```

Could probably help other developers quickly realise how to use this overloaded function in this particular use case.

Hope it's helpful and more than happy to put a PR if needed :)
Best.

**Comment by theophilusx** [comment]
If you feel the documentation or examples can be improved, please feel free to submit a PR and I will be happy to consider it for inclusion. However, please note that your example uses Typescript and this is not a typescript project. Only javascript is used, so any example should use vanilla JS. 

Note also that the documentation in the README states for get()

> The dst argument defines the destination and can be either a string, a stream object or undefined. If it is a string, it is interpreted as the path to a location on the local file system (path should include the file name). If it is a stream object, the remote data is passed to it via a call to pipe(). If dst is undefined, the method will put the data into a buffer and return that buffer when the Promise is resolved.

IF you have suggestions for improving the text, please submit them as a PR.
