### ISSUE TITLE
File not found on all files after the 12th

### ISSUE THREAD

**Issue by Josh1133** [theophilusx/ssh2-sftp-client#47]
Hello,

i am putting an array of files on a SFTP server and the first 11 files are uploading correctly anything after that i just get an error saying File not found. i have validated that i am passing data to the put method. on the server i see a black file created. Any idea why.

thank you,

**Comment by aaronmckeehan** [comment]
I have the same issue. Here is an example of my code:

```
objarray.forEach((item)=>{
        
        sftp.connect(config).then(() => {  
            return sftp.put(item.localpath, item.remotepath);  
        }).then(() => {
            console.log(item.id+ " uploaded.");
        }).catch((err) => {
            console.log(err, 'catch error ');
        });   
        
    });
```

**Comment by theophilusx** [comment]
The module has changed significantly since this issue was logged. Is this still and issue or has it been resolved?

**Comment by theophilusx** [comment]
No caction on issue. closing.
