### ISSUE TITLE
File not extractable

### ISSUE THREAD

**Issue by MikeF999** [theophilusx/ssh2-sftp-client#471]
Receiving an error that the file is not extractable. Using a FTP client like FileZilla allows for the download.
The FTP server does have an extract limit of 1 per file.

Error: fastGet->sftp: The message [filename] is not extractable! Remote: filename Local: tofilename
    at SftpClient.fmtError (C:\Projects\ftptest\node_modules\ssh2-sftp-client\src\index.js:111:22)
    at SftpClient.fastGet (C:\Projects\ftptest\node_modules\ssh2-sftp-client\src\index.js:616:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Node Version: 14.7.2
Package Version:    "ssh2-sftp-client": "^9.0.4"

It sounds very similar to the following issue:
https://github.com/mscdex/ssh2/issues/611

**Comment by theophilusx** [comment]
Not all SFTP servers support fastGet/fastPut. See if it works with just
get/put. If it still fails, please provide a minimal script which is
able to reproduce the issue as well as a log of a failed run (by adding
a log function to the debug property of the connection config object)

FYI your node version is end of life at the end of this month.

**Comment by MikeF999** [comment]
> 

Get was able to download the file, just had to wait another day for a new file to be available :)

And yes it will be EOL. Hoping to dedicate some dev time to upgrade versions however newer versions of node include breaking changes for our production system so it will require some significant time investment.

Thank you!
