### ISSUE TITLE
unzip file?

### ISSUE THREAD

**Issue by zhangjingle** [theophilusx/ssh2-sftp-client#475]
This tool is great, and I have a requirement. After connecting to the server using ssh2-sftp-client, I hope to be able to compress the directories on the server and decompress zip files. Thank you.

**Comment by zhangjingle** [comment]
ChatGPT told me like this code,but I can't find a method like sftp.createReadStream() 

`const unzipper = require('unzipper');
const { Client } = require('ssh2-sftp-client');

const sftp = new Client();
await sftp.connect({
  host: 'example.com',
  port: '22',
  username: 'username',
  password: 'password'
});

// create a read stream for the remote archive
const stream = await sftp.createReadStream('/path/to/remote/archive.zip');

// extract the contents of the archive to a local directory
stream.pipe(unzipper.Extract({ path: '/path/to/local/directory' }));

// wait for the extraction to finish and end the SFTP connection
await new Promise(resolve => stream.on('end', resolve));
await sftp.end();`

**Comment by theophilusx** [comment]
This is easy to do as both the get() and put() methods allow you to pass
in streams as the source/destination. For example, the following is one
of the unit tests for the module

  it('get gzipped file and gunzip in pipe', async function () {
    let localPath = makeLocalPath(config.localUrl, 'get-unzip.txt');
    let remotePath = config.sftpUrl + '/get-gzip.txt.gz';
    let gunzip = zlib.createGunzip();
    let out = fs.createWriteStream(localPath, {
      flags: 'w',
      encoding: null,
    });
    gunzip.pipe(out);
    await sftp.get(remotePath, gunzip);
    let stats = await sftp.stat(remotePath);
    let localStats = fs.statSync(localPath);
    return expect(stats.size < localStats.size).to.equal(true);
  });

There are also createReadStream and createWriteStream methods if you
want to manage things more directly, butg this isn't usually necessary.

**Comment by theophilusx** [comment]
Unless there is anything else required here, I plan to close this issue.
