### ISSUE TITLE
Privatekey connection isn't proceeding after trying none

### ISSUE THREAD

**Issue by ChrisTolmeijer** [theophilusx/ssh2-sftp-client#479]
I have an SFTP server accepting either password or publickey authentication. 

When setup my connection with password everything works great. However, when I try to connect using privatekey, it seems like it's not going past trying the 'none' method.
```
const connectionDetails = {
      host: host,
      port: port,
      username: username,
      password: password,
      readyTimeout: 10000,
      debug: (d) => console.log(d)
};
```    
This is the output for password auth:
```
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_FAILURE (password,publickey)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
```

When I modify the connection details to have a privatekey instead of a password:
```
const connectionDetails = {
      ...,
      privatekey: readFileSync(authentication_key);
};
```  

The client is failing as soon as the SFTP server responds to the none request with a failure:
```
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_FAILURE (password,publickey)
Client: none auth failed
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global error event: Ignoring expected and handled event
Outbound: Sending DISCONNECT (11)
CLIENT[sftp]: end: Called when no connection active
CLIENT[sftp]: connect: getConnection: All configured authentication methods failed (ERR_GENERIC_CLIENT)
Socket ended
CLIENT[sftp]: Global end event: Handling unexpected event
Socket closed
CLIENT[sftp]: Global close event: Handling unexpected event
```

Does anybody know what I could be doing wrong?

**Comment by theophilusx** [comment]
What format is your ssh key? There are issues using some key formats
(see the ssh2 repository issues as this is an ssh2 issue). It works for
me using a key which is using the ed25519  format.

Also, make sure your not also sending the password and include the
passphrase (assuming your key has a passphrase).

**Comment by ChrisTolmeijer** [comment]
I was using the default that `ssh-keygen` generates on Mac OS, I believe 2048 bit RSA. I generated a new key pair using ed25519 and I'm running into the same issue. The key does not have a passphrase, I'm making sure I'm not also sending the password in the connection object.
