### ISSUE TITLE
authMethod not being sent and password is swallowed as a result

### ISSUE THREAD

**Issue by igor-savin-ht** [theophilusx/ssh2-sftp-client#48]
When using this client together with node-sftp-server, client doesn't seem to be passing authMethod (which is supposed to be 'password'), and it seems that due to this password is set to undefined as well and it is not possible to implement proper authentication.

**Comment by theophilusx** [comment]
Is this still and issue with current version? If so, please provide sample code and we can investigate further. (current version is 2.5.2).

**Comment by theophilusx** [comment]
Closing as a dead issue.
