### ISSUE TITLE
Copy Files from Linux to Windows

### ISSUE THREAD

**Issue by jayaganeshk** [theophilusx/ssh2-sftp-client#480]
Hello,
Am trying to copy a file from linux to windows.
am able to copy file to "/" location only. am not able to copy to windows custom location like "F:/Documents"
any suggestions?

**Comment by theophilusx** [comment]
The location where you can copy to is usually controlled by the remote
sftp server your accessing i.e. this could be a config/restriction on
the remote server?

**Comment by theophilusx** [comment]
As there has been no further feedback on this issue, I'm closing it.
