### ISSUE TITLE
any method to continuous downloading , just like append of uploading

### ISSUE THREAD

**Issue by alanhg** [theophilusx/ssh2-sftp-client#483]
I have a need for continuous downloading and uploading. For uploading, I see there is an append method that can solve it, so is there a way for downloading?

Sometimes when a user is downloading a file, the SSH connection gets disconnected, so I only get a portion of the data. If I can continue downloading after re-establishing the connection, the experience would be much better.

https://github.com/theophilusx/ssh2-sftp-client#appendinput-remotepath-options--string

**Comment by theophilusx** [comment]
There is no specific method for downloads as it isn't needed. You have
full control/access to the local file. All you need to do is pass in a
writeStream which you have opened for append and job done.

**Comment by alanhg** [comment]
My question is, after a disconnection, I use the GET method to download the file again, but how can I control it to resume from a certain point? For example, if I have already downloaded 50% previously, I need to download the remaining 50% from the remote server. I understand that I can control whether the local file is appended or created anew, but the data stream from the remote server is still the full set, isn't it? That's my understanding.

**Comment by theophilusx** [comment]
There is no facility to provide what you want. You would have to
implement that yourself. This is precisely why I mentioned rsync in my
response to your question about bandwidth limiting.

The ability to resume a partially completed download or upload is not
part of the sftp protocol. Therefore it isn't part of ssh2 and has not
been implemented in ssh2-sftp-client. While I suspect you could use ssh2
(and probably ssh2-sftp-client) to implement such a feature, the low
level control code would need to be implemented as part of your client
code.

**Comment by alanhg** [comment]
![image](https://github.com/theophilusx/ssh2-sftp-client/assets/9245110/4a71b57a-d194-4eb4-b60b-b728bd965025)

I've found a solution. For downloading files using put, the remote source is a readable stream, and all I need to do is to pass the start position for reading.
