### ISSUE TITLE
put is always transferring into root folder ignoring path

### ISSUE THREAD

**Issue by cfroe** [theophilusx/ssh2-sftp-client#488]
Perhaps it's not an issue and I make something wrong. Sorry then it is a question for help.

I used for testing the  "example/upload-with-keys.js", connection is working perfect. For the upload I configured this:

```
let localFile = "test.txt";
let remoteDir = "/root/test/";
let remoteFilename = "test.txt";
```
When I put the File the output is like this:
![grafik](https://github.com/theophilusx/ssh2-sftp-client/assets/12471024/467ab2b6-e52d-4d02-9c15-04d6b1d40c02)

The folder test is created but instead of "test.txt" file in the folder "test" a file with the full path is created in the root.

Windows 11
Node v18.16.0

Here is also the debug output:

![grafik](https://github.com/theophilusx/ssh2-sftp-client/assets/12471024/56ff8609-b41b-475a-9817-ddb82ffe8ee5)

![grafik](https://github.com/theophilusx/ssh2-sftp-client/assets/12471024/bd008c8f-5f67-4e21-964f-f3824c64f204)

![grafik](https://github.com/theophilusx/ssh2-sftp-client/assets/12471024/1dee4035-a7f3-45d2-8e42-61e3e84fe6a4)

**Comment by theophilusx** [comment]
Sorry, but can you update your question and use only text and not
screenshots/graphics? They are not accessible for me and so I cannot
read them. Having the log in multiple screenshot images also makes them
difficult to use for analysis. 

What version of ssh2-sftp-client are you using?

Is the remote server a Windows, Linux or macOS system? If it is a
Windows server, are you using WSL? I need to know if the remote sftp
server is Linux or Windows based. 

From your description, this could well be a bug related to the different
path separators using on Windows and all other platforms. I don't run
Windows, so my ability to debug and test on that platform is very
limited.

**Comment by cfroe** [comment]
Thx for your fast response. I'm using Windows OS as a source machine and the server to transfer to is Linux. We are using the latest version of ssh2-sftp-client 9.1.0 but I also tried with 8.1.0.

The result of the upload is a new empty directory "test" and a file with the name "\root\test\test.txt" is created in the root folder with right content.

Here ist the debug output:

`test.js:98Server running at http://127.0.0.1:8081/
test.js:59CLIENT[sftp]: connect: Debugging turned on
test.js:59CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4  {
 "node": "18.16.0",
 "acorn": "8.8.2",
 "ada": "1.0.4",
 "ares": "1.19.0",
 "brotli": "1.0.9",
 "cldr": "42.0",
 "icu": "72.1",
 "llhttp": "6.0.10",
 "modules": "108",
 "napi": "8",
 "nghttp2": "1.52.0",
 "nghttp3": "0.7.0",
 "ngtcp2": "0.8.1",
 "openssl": "3.0.8+quic",
 "simdutf": "3.2.2",
 "tz": "2022g",
 "undici": "5.21.0",
 "unicode": "15.0",
 "uv": "1.44.2",
 "uvwasi": "0.0.15",
 "v8": "10.2.154.26-node.26",
 "zlib": "1.2.13"
}
test.js:59CLIENT[sftp]: connect: Connect attempt 1
test.js:59Custom crypto binding not available
test.js:59Local ident: 'SSH-2.0-ssh2js1.14.0'
test.js:59Client: Trying amirada.net on port 22 ...
test.js:59Socket connected
test.js:59Remote ident: 'SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5'
test.js:59Outbound: Sending KEXINIT
test.js:59Inbound: Handshake in progress
test.js:59Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ext-info-c
test.js:59Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
test.js:59Handshake: KEX algorithm: curve25519-sha256@libssh.org
test.js:59Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
test.js:59Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
test.js:59Handshake: Host key format: ssh-ed25519
test.js:59Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
test.js:59Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
test.js:59Handshake: C->S Cipher: aes128-gcm@openssh.com
test.js:59Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
test.js:59Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
test.js:59Handshake: S->C cipher: aes128-gcm@openssh.com
test.js:59Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
test.js:59Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
test.js:59Handshake: C->S MAC: <implicit>
test.js:59Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
test.js:59Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
test.js:59Handshake: S->C MAC: <implicit>
test.js:59Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
test.js:59Handshake: (remote) C->S compression: none,zlib@openssh.com
test.js:59Handshake: C->S compression: none
test.js:59Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
test.js:59Handshake: (remote) S->C compression: none,zlib@openssh.com
test.js:59Handshake: S->C compression: none
test.js:59Outbound: Sending KEXECDH_INIT
test.js:59Received DH Reply
test.js:59Host accepted by default (no verification)
test.js:59Host accepted (verified)
test.js:59Outbound: Sending NEWKEYS
test.js:59Inbound: NEWKEYS
test.js:59Verifying signature ...
test.js:59Verified signature
test.js:59Handshake completed
test.js:59Outbound: Sending SERVICE_REQUEST (ssh-userauth)
test.js:59Inbound: Received EXT_INFO
test.js:59Inbound: Received SERVICE_ACCEPT (ssh-userauth)
test.js:59Outbound: Sending USERAUTH_REQUEST (none)
test.js:59Inbound: Received USERAUTH_FAILURE (publickey,password)
test.js:59Client: none auth failed
test.js:59Outbound: Sending USERAUTH_REQUEST (password)
test.js:59Inbound: Received USERAUTH_SUCCESS
test.js:59CLIENT[sftp]: getConnection ready listener: got connection - promise resolved
test.js:59Outbound: Sending CHANNEL_OPEN (r:0, session)
test.js:59Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
test.js:59Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
test.js:59Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
test.js:59Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
test.js:59Inbound: REQUEST_SUCCESS
test.js:59Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
test.js:59Inbound: CHANNEL_SUCCESS (r:0)
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 9)
test.js:59Inbound: CHANNEL_DATA (r:0, 183)
test.js:59SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com,lsetstat@openssh.com)
test.js:59CLIENT[sftp]: exists: remotePath = /root/test/
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 24)
test.js:59SFTP: Outbound: Buffered LSTAT
test.js:59Inbound: CHANNEL_DATA (r:0, 33)
test.js:59SFTP: Inbound: Received STATUS (id:0, 2, "No such file")
test.js:59CLIENT[sftp]: _xstat: No such file: /root/test/ (ENOENT)
test.js:59CLIENT[sftp]: exists: remotePath = /root/test/
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 24)
test.js:59SFTP: Outbound: Buffered LSTAT
test.js:59Inbound: CHANNEL_DATA (r:0, 33)
test.js:59SFTP: Inbound: Received STATUS (id:1, 2, "No such file")
test.js:59CLIENT[sftp]: _xstat: No such file: /root/test/ (ENOENT)
test.js:59CLIENT[sftp]: exists: remotePath = /root
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 18)
test.js:59SFTP: Outbound: Buffered LSTAT
test.js:59Inbound: CHANNEL_DATA (r:0, 41)
test.js:59SFTP: Inbound: Received ATTRS (id:2)
test.js:59CLIENT[sftp]: _xstat: result =  {
 "mode": 16832,
 "uid": 0,
 "gid": 0,
 "size": 4096,
 "accessTime": 1687509302000,
 "modifyTime": 1687509302000,
 "isDirectory": true,
 "isFile": false,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
test.js:59CLIENT[sftp]: exists: <-  {
 "mode": 16832,
 "uid": 0,
 "gid": 0,
 "size": 4096,
 "accessTime": 1687509302000,
 "modifyTime": 1687509302000,
 "isDirectory": true,
 "isFile": false,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 28)
test.js:59SFTP: Outbound: Buffered MKDIR
test.js:59Inbound: CHANNEL_DATA (r:0, 28)
test.js:59SFTP: Inbound: Received STATUS (id:3, 0, "Success")
test.js:59CLIENT[sftp]: exists: remotePath = \root\test\test.txt
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 32)
test.js:59SFTP: Outbound: Buffered LSTAT
test.js:59Inbound: CHANNEL_DATA (r:0, 33)
test.js:59SFTP: Inbound: Received STATUS (id:4, 2, "No such file")
test.js:59CLIENT[sftp]: _xstat: No such file: \root\test\test.txt (ENOENT)
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 44)
test.js:59SFTP: Outbound: Buffered OPEN
test.js:59Inbound: CHANNEL_DATA (r:0, 17)
test.js:59SFTP: Inbound: Received HANDLE (id:5)
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 25)
test.js:59SFTP: Outbound: Buffered FSETSTAT
test.js:59Inbound: CHANNEL_DATA (r:0, 28)
test.js:59SFTP: Inbound: Received STATUS (id:6, 0, "Success")
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 47)
test.js:59SFTP: Outbound: Sent WRITE (id:7)
test.js:59Inbound: CHANNEL_DATA (r:0, 28)
test.js:59SFTP: Inbound: Received STATUS (id:7, 0, "Success")
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 17)
test.js:59SFTP: Outbound: Buffered CLOSE
test.js:59Inbound: CHANNEL_DATA (r:0, 28)
test.js:59SFTP: Inbound: Received STATUS (id:8, 0, "Success")
test.js:59Outbound: Sending CHANNEL_DATA (r:0, 32)
test.js:59SFTP: Outbound: Buffered STAT
test.js:59Inbound: CHANNEL_DATA (r:0, 41)
test.js:59SFTP: Inbound: Received ATTRS (id:9)
test.js:59CLIENT[sftp]: _xstat: result =  {
 "mode": 33206,
 "uid": 0,
 "gid": 0,
 "size": 18,
 "accessTime": 1687509309000,
 "modifyTime": 1687509309000,
 "isDirectory": false,
 "isFile": true,
 "isBlockDevice": false,
 "isCharacterDevice": false,
 "isSymbolicLink": false,
 "isFIFO": false,
 "isSocket": false
}
test.js:83Remote file \root\test\test.txt size is 18
test.js:59Outbound: Sending DISCONNECT (11)
test.js:59Socket ended
test.js:59CLIENT[sftp]: end endListener - ignoring handled error
test.js:59CLIENT[sftp]: Global end event: Ignoring expected and handled event
test.js:59Socket closed
test.js:59CLIENT[sftp]: end: Connection closed
test.js:59CLIENT[sftp]: end closeListener - ignoring handled error
test.js:59CLIENT[sftp]: Global close event: Ignoring expected and handled event`

**Comment by cfroe** [comment]
Now I tested the same code on a linux server everything is working fine, so the problem seems to be my local windows OS. For production the script is running on a linux server, so I'm able to use your module. For debugging for sure it would be nice if it also works on windows. Let me know if you need more information.
Thx Christoph

**Comment by cfroe** [comment]
Now it's also working under windows with my new test. I have no idea why. It looks like the path to the source is the problem Thx Christoph
