### ISSUE TITLE
fastGet corrupts downloaded file

### ISSUE THREAD

**Issue by dankolz** [theophilusx/ssh2-sftp-client#504]
For version 9.1.0, using fastGet downloads a file which is different every time, even though the file on the server hasn't changed. I'm downloading a CSV of about 83 megs. 

I'm not sure what the SFTP server is. The `version` command tells me "SFTP protocol version 3". It does NOT look like the simple SFTP I set up by configuring the /etc/ssh* files.

`get` seems to give a consistent result and match the file download from the command line sftp client.

**Comment by dankolz** [comment]
Ah! I see this is documented in a closed issue now. Sorry for the duplicate.

**Comment by theophilusx** [comment]
Docs updated

**Comment by dankolz** [comment]
Thank you!
