### ISSUE TITLE
Remote host has reset the connection: getConnection: read ECONNRESET

### ISSUE THREAD

**Issue by EliasSalom** [theophilusx/ssh2-sftp-client#511]
I'm using the package to upload files to the remote Windows server, 
the use started when I tried to upload many files at once,
now if I upload one file it's okay but uploading multiple files returns this error specific to more than 3 files

`[Nest] 28748  - 31/12/2023, 16:09:52   ERROR [ExceptionsHandler] connect: Remote host has reset the connection: getConnection: read ECONNRESET
Error: connect: Remote host has reset the connection: getConnection: read ECONNRESET
`
![image](https://github.com/theophilusx/ssh2-sftp-client/assets/39850311/5230ab58-cef3-43e0-8eb2-322ae02e9c06)

now I'm using nestJs as the backend, 
details
-    `ssh2-sftp-client": "^9.1.0`
-    `@nestjs/config": "^3.0.0`
-   `@nestjs/core": "^10.0.2`
-   `@nestjs/jwt": "^10.1.1`
-    `@nestjs/passport": "^10.0.1`
-   `@nestjs/platform-express": "^10.0.2`

a little snap code of how I'm using it
```ts
	public async saveFile(folderName: string, fileName: string, fileBase64: string) {
               const fileBuffer = this.base64ToBuffer(fileBase64);
                await this.initFtpClient();
		await this.ensureDirectoryExists(`E:/file/sub_folder/${Nickname}/printed_docs/${folderName}`);
		await this.localSaveFile(`${folderName}/${fileName}.${fileType}`, fileBuffer);

		return this.sftpClient.put(
			`C:/Users/Desktop/project/myApp-monorepo/apps/server/UploadedFile/${folderName}/${fileName}.${fileType}`,
			`E:/file/sub_folder/${Nickname}/printed_docs/${folderName}/${fileName}.${fileType}`
		);
           }

	async initFtpClient(): Promise<void> {
		if (this.isConnected) return;

		const credentials = await this.getFtpCredentials();
		await this.sftpClient.connect(credentials);
		this.isConnected = true;
	}

	private async getFtpCredentials(): Promise<{
		username: string;
		password: string;
		host: string;
		port: number;
		protocol?: string;
		readyTimeout?: number;
		algorithms?: object;
	}> {
		const Nickname = this.request.headers['x-nickname'] as string;
		if (!Nickname) {
			throw new BadRequestException('x-nickname header not provided.');
		}

		return {
			username: '***',
			password: '***',
			host: '***',
			port: 22,
			readyTimeout: 99999,
		};
	}
```

**Comment by theophilusx** [comment]
That error indicates the remote sftp server is closing the
connection. You need to inspect the logs for the sftp server to get a
clue as to why it is closing the connection.

One thing to check, it isn't clear from your code sample that you are
waiting for one upload to finish before starting the next. It is
possible that you are just exceeding the maximum concurrent connections
with the remote sftp server and it is therefore closing the connection
or your running into some other form of rate limiting on the remote
server.

At any rate, I doubt this is an ssh2-sftp-client specific issue. More
likely something to do with the remote server, so I would start
diagnosis from there.

**Comment by EliasSalom** [comment]
thank you for your answer @theophilusx , in my case,
I went after your lead and checked the server
the server is Windows Server 2022 and the openSSH feature from Microsoft 
the problem was the time-out 
after reading this (article)[https://www.nixcraft.com/t/clientalive-messages-tmout-and-ssh-session-logging-of/2874]
I changed `ClientAliveCountMax = 50` and `ClientAliveInterval = 300` in the `sshd_config` on the server and that solve my issue
