### ISSUE TITLE
Urgent: SSH2 Dependency Vulnerability - Action Required

### ISSUE THREAD

**Issue by dcamacho10** [theophilusx/ssh2-sftp-client#512]
Hi team,

I would like to bring to your attention a critical vulnerability present in the ssh2 dependency. The recommended fix for this issue is to update the version from 1.14 to 1.15.

Vulnerability Details:

The SSH transport protocol, including certain OpenSSH extensions found in versions prior to 9.6, along with other products, is susceptible to a security loophole. This vulnerability allows remote attackers to bypass integrity checks, resulting in the omission of some packets from the extension negotiation message. Consequently, a client and server may end up with a connection in which certain security features have been downgraded or disabled. This is known as a Terrapin attack.

The vulnerability arises due to mishandling of the handshake phase and improper use of sequence numbers in the SSH Binary Packet Protocol (BPP), as implemented by these extensions. Notably, there is an effective attack against SSH's use of ChaCha20-Poly1305 (and CBC with Encrypt-then-MAC). The bypass affects [chacha20-poly1305@openssh.com](mailto:chacha20-poly1305@openssh.com) and, if CBC is used, the [-etm@openssh.com](mailto:-etm@openssh.com) MAC algorithms.

This vulnerability extends to various software and libraries, including but not limited to:

Maverick Synergy Java SSH API before 3.1.0-SNAPSHOT
Dropbear through 2022.83
Ssh before 5.1.1 in Erlang/OTP
PuTTY before 0.80
AsyncSSH before 2.14.2
golang.org/x/crypto before 0.17.0
libssh before 0.10.6
libssh2 through 1.11.0
Thorn Tech SFTP Gateway before 3.4.6
Tera Term before 5.1
Paramiko before 3.4.0
jsch before 0.2.15
SFTPGo before 2.5.6
Netgate pfSense Plus through 23.09.1
Netgate pfSense CE through 2.7.2
HPN-SSH through 18.2.0
ProFTPD before 1.3.8b (and before 1.3.9rc2)
ORYX CycloneSSH before 2.3.4
NetSarang XShell 7 before Build 0144
CrushFTP before 10.6.0
ConnectBot SSH library before 2.2.22
Apache MINA sshd through 2.11.0
sshj through 0.37.0
TinySSH through 20230101
trilead-ssh2 6401
LANCOM LCOS and LANconfig
FileZilla before 3.66.4
Nova before 11.8
PKIX-SSH before 14.4
SecureCRT before 9.4.3
Transmit5 before 5.10.4
Win32-OpenSSH before 9.5.0.0p1-Beta
WinSCP before 6.2.2
Bitvise SSH Server before 9.32
Bitvise SSH Client before 9.33
KiTTY through 0.76.1.13
the net-ssh gem 7.2.0 for Ruby
the mscdex ssh2 module before 1.15.0 for Node.js
the thrussh library before 0.35.1 for Rust
the Russh crate before 0.40.2 for Rust.
Immediate action is required to update the ssh2 dependency to version 1.15 and mitigate the risk associated with this vulnerability.

Thank you for your prompt attention to this matter.

Best regards,

**Comment by theophilusx** [comment]
1. This does not impact new installs as new installs will depend on ssh2
1.15.0, which has already fixed this issue.

2. Existing installs can run 'npm update' which will update the ssh2
dependency to 1.15.0, mitigating this issue.

3. The current master has already updated the ssh2 dependency to
1.15.0. A new version will be pushed out this week.

**Comment by dcamacho10** [comment]
Thank you so much!
