### ISSUE TITLE
connection -timeout

### ISSUE THREAD

**Issue by aswinkumar686** [theophilusx/ssh2-sftp-client#515]
Hi
Iam facing the same issue

CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4 {
"node": "16.20.2",
"v8": "9.4.146.26-node.26",
"uv": "1.43.0",
"zlib": "1.2.11",
"brotli": "1.0.9",
"ares": "1.19.1",
"modules": "93",
"nghttp2": "1.47.0",
"napi": "8",
"llhttp": "6.0.11",
"openssl": "1.1.1v+quic",
"cldr": "41.0",
"icu": "71.1",
"tz": "2022f",
"unicode": "14.0",
"ngtcp2": "0.8.1",
"nghttp3": "0.7.0"
}
CLIENT[sftp]: connect: Connect attempt 1
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.15.0'
Client: Trying ****** on port 22 ...
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global error event: Ignoring expected and handled event
Socket closed
CLIENT[sftp]: connect closeListener - ignoring handled error
CLIENT[sftp]: Global close event: Ignoring expected and handled event
CLIENT[sftp]: connect: Connect attempt 2
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.15.0'
Client: Trying ***** on port 22 ...
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global error event: Ignoring expected and handled event
Socket closed
CLIENT[sftp]: connect closeListener - ignoring handled error
CLIENT[sftp]: Global close event: Ignoring expected and handled event
CLIENT[sftp]: connect: Connect attempt 3
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.15.0'
Client: Trying ***** on port 22 ...
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global error event: Ignoring expected and handled event
Socket closed
CLIENT[sftp]: connect closeListener - ignoring handled error
CLIENT[sftp]: Global close event: Ignoring expected and handled event
CLIENT[sftp]: connect: Connect attempt 4
Custom crypto binding not available
Local ident: 'SSH-2.0-ssh2js1.15.0'
Client: Trying ***** on port 22 ...
CLIENT[sftp]: connect errorListener - ignoring handled error
CLIENT[sftp]: Global error event: Ignoring expected and handled event
CLIENT[sftp]: end: Called when no connection active
CLIENT[sftp]: connect: getConnection: Timed out while waiting for handshake (ERR_GENERIC_CLIENT)
[info][2024-01-18 05:08:59][EkitService] - connect: getConnection: Timed out while waiting for handshake
Socket closed
CLIENT[sftp]: Global close event: Handling unexpected event

Here is the config

    readyTimeout: 99999,
    secure: true,
    compress: 'none',
    debug: console.info,
    pasvTimeout: 200000,
    keepalive: 200000,
    secureOptions: {
      rejectUnauthorized: false
    },
    retries: 3,
    retry_factor: 2,
    retry_minTimeout: 2000,
    algorithms: {
      kex: [
        'diffie-hellman-group1-sha1',
        'ecdh-sha2-nistp256',
        'ecdh-sha2-nistp384',
        'ecdh-sha2-nistp521',
        'diffie-hellman-group-exchange-sha256',
        'diffie-hellman-group14-sha1'
      ],
      cipher: [
        '3des-cbc',
        'aes128-ctr',
        'aes192-ctr',
        'aes256-ctr',
        'aes128-gcm',
        'aes256-gcm',
        'aes256-cbc'
      ],
      serverHostKey: [
        'ssh-rsa',
        'ssh-dss',
        'ecdsa-sha2-nistp256',
        'ecdsa-sha2-nistp384',
        'ecdsa-sha2-nistp521'
      ],
      hmac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1']
    }

**Comment by theophilusx** [comment]
ASWIN KUMAR P ***@***.***> writes:

This error is telling you that the connection timed out because the
remote sftp server has not responded. You need to debug this at the
server. You could also try using openSSH's sftp client to see if that
works with -vvv to get verbose debug output and verify the remote sftp
server supports one of the key exchange or ciphers you have configured.
