### ISSUE TITLE
What is a path in the 'put' method?

### ISSUE THREAD

**Issue by simonh1000** [theophilusx/ssh2-sftp-client#516]
In https://github.com/theophilusx/ssh2-sftp-client?tab=readme-ov-file#putsrc-remotepath-options--string an example path is given of `'/path/to/remote/file.txt'`

However, in my code when I pass a remote path of e.g. `/index.html` I am getting a `code: 4` error and have to remove the `/` to make it work.

Could you clarify how top level paths are supposed to work?

**Comment by theophilusx** [comment]
This is really determined by the type and configuration of the remote
sftp server. In some cases, an sftp server is setup in a chroot
environment, in others it is just linked to a user account and in some
cases you have access only to a limited subset of the remote disk while
in others, you may hve broader access.

If you specify a path starting with '/' you are specifying a fully
qualified absolute path. This may or may not work depending on the remote system
configuraiton. If you only specify either ./filename or just 'filename'
your providing a path relative to whatever the login directory is for
your remote sftp configuration.

Essentially the file path is just a normal Unix styhle file path. How it
is interpreted by the remote system is a matter of configuraiton of the
remote system. If you used the path /index.html, it is likely that you
were referencing a file in the root directory of the remote system
(unless you are accessing a 'real' chroot sftp server). In your case, I
suspect your actually loging into a remote user account over sftp and
requesting the 'index.html' file in the home directory of the login
user. This is the same as ./index.html, a relative
path - a path relative to the home directory of the user you are logging
into. You can probably do something like sftp.realPath('.') and it will
show you what the full path is from the root e.g. /var/www or /home/user
or something like that.
