### ISSUE TITLE
pacakge@version ssh2-sftp-client@9.0.1 | custom crypto binding not available

### ISSUE THREAD

**Issue by ubaidraza** [theophilusx/ssh2-sftp-client#522]
Hi,

I'm having this issue '**custom crypto binding not available**' when our server is making call to SFTP server of Cloudflare, can you please help us.

I tried latest version 10.0.1 and 7.2.3 also but that doesn't work also

following are parameters
const SFTP_CREDENTIALS = {
  host: 'HOST_NAME',
  port: '22',
  username: 'USER_NAME',
  password: 'PASSWORD',
  readyTimeout: 99999,
  keepaliveInterval: 9999,
  keepaliveCountMax: 99,
  debug: console.log
};

Here is debug logs
```
 CLIENT[****-client]: connect: Debugging turned on
 CLIENT[****-client]: ssh2-sftp-client Version: 9.0.4  {
  "node": "16.13.0",
  "v8": "9.4.146.19-node.13",
  "uv": "1.42.0",
  "zlib": "1.2.11",
  "brotli": "1.0.9",
  "ares": "1.17.2",
  "modules": "93",
  "nghttp2": "1.45.1",
  "napi": "8",
  "llhttp": "6.0.4",
  "openssl": "1.1.1l+quic",
  "cldr": "39.0",
  "icu": "69.1",
  "tz": "2021a",
  "unicode": "13.0",
  "ngtcp2": "0.1.0-DEV",
  "nghttp3": "0.1.0-DEV"
 }
 CLIENT[****-client]: connect: Connect attempt 1
 Custom crypto binding not available
 Local ident: 'SSH-2.0-ssh2js1.15.0'
```

**Comment by theophilusx** [comment]
Previous response does not seem to have got added here. 

The 'custom crypto bindings not available' is not an error. This is just a message informing you that your version is not using the native node-gyp crypto code. This code is an optional dependency which is automatically built if the platform can support it. Without it, everything still works the same, though possibly slightly slower.
