### ISSUE TITLE
Writing to Stream after using put method

### ISSUE THREAD

**Issue by fearless23** [theophilusx/ssh2-sftp-client#524]
The issue is node js skills :) not with package, but still wanted to ask community here.

I am trying to upload csv file given i have rows of file as array of string. I use a pass through stream and pass it to put methd of sftp client. 

If i await on client.put; nothing is written to stream, because process will wait for put promise to finish. If i do not use await, it works, but process exists early (usually seen in aws-lambda type environments), in which case stream ends but put method may not have finished completely.  I tried some hacky solutions mentioned in the end. 

Is there a nice way to approach this problem

```ts
import { PassThrough } from "node:stream";
import { finished } from "node:stream/promises";

const uploadCsv = async (csvRows: string[]) => {
	const stream = new PassThrough();
	await client.put(stream, "remote_path");
	for (const row of csvRows) {
		stream.write(row, "utf-8");
	}
	stream.end();
	await finished(stream);
};
```

Hacky solution

```ts
const uploadCsv = async (csvRows: string[]) => {
	const stream = new PassThrough();
	const putPromise = client.put(stream, "remote_path");

	putPromise.catch((error) => {
		console.error("Error while putting:", error);
		stream.destroy(error);
	});
	for (const row of csvRows) {
		stream.write(row, "utf-8");
	}
	stream.end();
	await putPromise;
	await finished(stream);
};
```

**Comment by theophilusx** [comment]
You are correct, it is your knowledge of node that is causing you
issues. 

My suggestion would be to start of smaller and learn how node streams
work. Start by writing a very simple node script which uses streams to
copy an array of file from one location to another location locally (no
sftp, just local copy). For deeper understanding, try 2 scripts, one
which uses promises and one which just uses events. Once you have that
working and have a clearer idea how node works, re-read the README,
browse the scripts in the example directory of the ssh2-sftp-client
repository and start again from fresh.

You may need to expand your understanding of streams and the different
types of streams you have available. For exmaple, your use of a pass
through stream in your example is completely wrong (you don't need a
pass through stream in your example). You should also understand how
stream.pipe() works as this will greatly simplify how you use streams. 

There are many good videos and written tutorials on using node streams
out there. Higherly recommend you work through a couple of them as it
will save you time in the long run.

Something to consider in your example. The ssh2-sftp-client put() method
supports strings (filename), buffers and streams as the source input
(first argument). While you can pass in a stream, you don't have to. You
could just pass in the filename and let the package take care of all the
stream handling. Although this would likely solve your issue, it won't
help with your understanding of how things work and will almost
certainly just push the problem to a new point in your code.
