### ISSUE TITLE
Question: Does this package support TransferSecurityPolicy-2022-03?

### ISSUE THREAD

**Issue by Megapixel99** [theophilusx/ssh2-sftp-client#529]
Hi,

I have a project and one of the features of the project is that it uploads two files to an SFTP server every night using ssh2-sftp-client. The company which runs the SFTP server(s) recently stated they are going to release an update requiring everyone who uses their SFTP server(s) to use TransferSecurityPolicy-2022-03 instead of TransferSecurityPolicy-2020-06. I personally had never heard of these specific transport security policies until today and wanted to see if ssh2-sftp-client supported TransferSecurityPolicy-2022-03.

**Comment by enov** [comment]
Those are AWS [policies](https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html).

Diff left 2022-03, right 2020-06
![image](https://github.com/theophilusx/ssh2-sftp-client/assets/4045110/7a36014b-0942-4c49-b6d5-e106e04e82e2)

List of ciphers ssh2 supports
https://github.com/mscdex/ssh2?tab=readme-ov-file#client-methods
