### ISSUE TITLE
Basic usage is impossible

### ISSUE THREAD

**Issue by herenickname** [theophilusx/ssh2-sftp-client#556]
```ts
const entrySftp = new SFTPClient()
await entrySftp.connect({
        host: config.ip,
        port: 22,
        username: config.username,
        privateKey: localSshKeyPrivate
})
```

```
error: Uncaught (in promise) Error: getSftpChannel: Packet length 1349281121 exceeds max length of 262144
    at SftpClient.fmtError (node_modules/.deno/ssh2-sftp-client@11.0.0/node_modules/ssh2-sftp-client/src/index.js:94:22)
    at node_modules/.deno/ssh2-sftp-client@11.0.0/node_modules/ssh2-sftp-client/src/index.js:156:23
```
    
Deno 2.0, last lib version from npm.

**Comment by theophilusx** [comment]
Have never seen this error before. Suspect it is a deno issue. I'm not
interested in supporting deno You will need to resolve this one
yourself.

One thing I did notice is that you don't show that you setup the private
key via a stream. For example,

 privateKey: readFileSync(keyFile, { encoding: 'utf8' }),

It also looks like your not usinhg a passphrase. Really should use a
passphrase to protect stolen keys from being usable.

**Comment by herenickname** [comment]
@theophilusx для будущих поколений :))
проблема заключалась в no-shell у пользователя к профилю которого я пытался подключиться.
с вашим модулем все хорошо, спасибо!

p.s.: это сгенерированные сервера и практически одноразовые приватные ключи, с безопасностью тоже все ок :)

**Comment by herenickname** [comment]
@theophilusx for future generations:
the problem was the no-shell of the user whose profile I was trying to connect to.
everything is fine with your module, thanks!

p.s.: these are generated servers and practically one-time private keys, security is fine too :)
