### ISSUE TITLE
New file banned

### ISSUE THREAD

**Issue by gearintellix** [theophilusx/ssh2-sftp-client#68]
before i trying put with exists file,

this the message i put on new file (not exists before), i've try more 3 times
![screen shot 2018-05-18 at 05 17 12](https://user-images.githubusercontent.com/7834238/40206625-19c771a4-5a5b-11e8-8ea5-84728597e4be.png)

then after i trying put with exists file, message above not show again.

I am afraid if this package is unstable,
please review it, thanks for your attention

**Comment by theophilusx** [comment]
This error is from the underlying modules that this module uses. Without more details and sample of code, there is nothing I can do.
