### ISSUE TITLE
end() -- shouldn't it wait for drain/continue before calling resolve if underlying client.end() returns false?

### ISSUE THREAD

**Issue by shaunc** [theophilusx/ssh2-sftp-client#69]
I sometimes (very sporadically) seem to be getting truncated files. Looking at the code, shouldn't end() wait for "continue" if underlying end (which seems to call ssh2-streams.disconnect) returns false, before calling resolve()?

**Comment by edy** [comment]
see #70

**Comment by theophilusx** [comment]
API changed significantly, which should both have resolved this issue and made this issue outdated. Closing. If issue persists, please open a new issue with details regarding version and node version etc.
