### ISSUE TITLE
Resolve get()'s Promise after read stream has completed.

### ISSUE THREAD

**Issue by xTriad** [theophilusx/ssh2-sftp-client#70]
https://github.com/jyu213/ssh2-sftp-client/blob/791e5efc660f787f0f21dbe43e5622719074fa5b/src/index.js#L81

In the above line, the `resolve` needs to happen after the `while` loop has completed.

```javascript
stream.on('readable', () => {
	let chunk;
	let accumulator = '';
	while((chunk = stream.read()) !== null) {
		accumulator += chunk;
	}
	resolve(accumulator);
});
```

**Comment by theophilusx** [comment]
With the changes to the get interface, this issue should be resolved. Therefore, I think this issue could be closed.
