### ISSUE TITLE
3.0.0 get interface won't work for large files

### ISSUE THREAD

**Issue by shaunc** [theophilusx/ssh2-sftp-client#72]
See https://github.com/jyu213/ssh2-sftp-client/commit/cd69ab2ba2a2557557236e225ca5ee3edd1e583c#commitcomment-29106818

**Comment by shaunc** [comment]
In this fork: https://github.com/shaunc/ssh2-sftp-client
I've cleaned up, and got working with node 10. You might not consider it suitable for a PR as I formatted according to the eslint/standard preset, as well as opportunistically using async/await to clean up the code.
The moral of the story for get() seems to be that the underlying stream from ssh2/ssh2-streams is fine -- you can just return that.

**Comment by rhodul** [comment]
I came across your issue post while struggling with this code:
`sftp.get('/sandbox/test.xyz').then(stream => {
    const readlineInterface = readline.createInterface({
        input: stream,
    });
    readlineInterface.on('line', function (line) {
        console.log('Never called');
    });
    readlineInterface.on('close', function (info) {
        console.log('Never called');
    });
});`
It seems related, right?
If yes, how can one yarn add your project?
Thanks.

**Comment by rhodul** [comment]
@shaunc, I just want to confirm that my problem above is solved by your fix!

**Comment by rhodul** [comment]
My problem above can be solved thusly:
```javascript
const Client = require('ssh2-sftp-client');
const client = new Client();
const credentials = require('./credentials');
const readline = require('readline');
console.log('Started processing SFTP files.....');
client.connect({
    host: credentials.sftpHost,
    username: credentials.sftpUser,
    password: credentials.sftpPwd,
}).then(sftp => {
    return new Promise(function (resolve, reject) {
        const stream = sftp.createReadStream('/sandbox/test.xyz', {encoding: 'utf8'});
        const readlineInterface = readline.createInterface({
            input: stream,
        });
        readlineInterface.on('line', function (line) {
            console.log(line);
        });
        readlineInterface.on('close', function (info) {
            console.log('Info: ' + info);
            resolve(info);
        });
    });
}).catch((err) => {
    console.error(err);
}).finally(() => {
    console.log('finished proces');
    return client.end();
});
```

**Comment by theophilusx** [comment]
The v3.0.0 was deprecated due to various other issues. Also, main branch has progressed significantly since this issue was originally logged, so am closing it as being outdated.
