### ISSUE TITLE
multiple files upload

### ISSUE THREAD

**Issue by estivalet** [theophilusx/ssh2-sftp-client#73]
I'm not able to upload multiple files, probabling coding it wrong. Could someone provide me an example of multiple file upload? I want to upload over 500 files and in the end of all of them I want to return if the upload was success or not. thanks

**Comment by NDMCreative** [comment]
const glob = require("glob")
const currentPath = process.cwd();

glob( currentPath+ "/content/*.html", function(er, files) {
        for (let f in files) {  console.log(files[f])  //sftp.put()  }
}

**Comment by slamus** [comment]
Hi, 

I did it that way

```js
const putFiles = (sftpConfig) => (fileList) => {
  const sftp = new sftpClient()
  return new Promise(function(resolve, reject) {
    sftp
    .connect(sftpConfig)
    .then(() => {
      return Promise.all(fileList.map(args => {
        return sftp.put.apply(sftp, args)
      }))
    })
    .then(() => sftp.end())
    .then(resolve)
    .catch(reject)
  });
}
```

You could replace the first line with this if you don't want a closure-like behaviour
```
const putFiles = (sftpConfig, fileList) => {
```


Good Luck ;-)

**Comment by theophilusx** [comment]
Multiple examples provided. Closing issue as resolved.

**Comment by sulthan6** [comment]
> Multiple examples provided. Closing issue as resolved.

Can you please provide link of other exmaple to show multiple file upload?

**Comment by theophilusx** [comment]
There are a number of examples in the example/ directory of the repository. The module also now includes an uploadDir method which also uploads mult9iple files.
