### ISSUE TITLE
File not actually being uploaded to server

### ISSUE THREAD

**Issue by dahudson88** [theophilusx/ssh2-sftp-client#80]
Ok I am trying to upload a single file to a remote server. 
I get the following message...
<localfilePath> was successfully uploaded to <remoteFilePath>!

I then go take a look in the server and the file is not there.

I have done the step function as described and see each chunk get uploaded, but still no file.

Full code snippet:
```
let Client = require('ssh2-sftp-client');
    let sftp = new Client();
    sftp.connect({
      host: <host>,
      port: 22,
      username: '<user>',
      password: '<password>',
    })
    .then(() => {
      return sftp.fastPut(<localFilePath>, 'remoteFilePath',{
        step: function ( totalTx, chunk, total ) {
            console.log( 'uploadFile.step totalTx', totalTx, 'chunk', chunk, 'total', total );
        }
      });
    })
    .then((data) => {
      console.log(data, 'the data info');
    }).catch((err) => {
      console.log(err, 'catch error');
    });


```
Any Idea what we could be doing wrong?  or could it be an issue not allowing applications on the server?  Using Transmit(SFTP Client) I can create folders and add files, but not with this application.

**Comment by jyu213** [comment]
I test the snippet code with local server, it just works fine.

**Comment by eragon11** [comment]
i'm also used the sftp.fastput( ) but got error:
errno: -2
no such file or directory.. IDK how to give.. i tried all methods..
I gave like this below:
sftp.fastput('/xxx/yyy','/aaa/bbbb')........

**Comment by theophilusx** [comment]
We cannot repoduce this issue and all our tests are passing. Suspect this may be a server issue.
