### ISSUE TITLE
How to download file as text?

### ISSUE THREAD

**Issue by becauseinterwebs** [theophilusx/ssh2-sftp-client#86]
I'm connecting to a server to download a text file, but when I try to open it, it is binary encoded.  I tried setting { encoding : 'ascii' }, but that did not work.  I know if most FTP clients you can choose how files are downloaded as ascii or binary. How do I download a text file using get or fastGet?  Thank you!

**Comment by johnmeister** [comment]
Share what code you've already written.

**Comment by softerboy** [comment]
client = new Client()

    // .... connect to server ... then
    
    client.get(remote_filename))
         .then(stream => {

               // here you can set encoding
               stream.setEncoding('utf8')
               stream.resume()
               const content = stream.read()

              // do something with content
         })
        .catch(err => { /* handle error */})

**Comment by theophilusx** [comment]
Closing as the module iAPI  has changed and an answer using the old API has been provided.
