### ISSUE TITLE
Shut down sftp server automatically after half an hour

### ISSUE THREAD

**Issue by vishnusinghchauhan** [theophilusx/ssh2-sftp-client#87]
i am using ss2 library my server automatically shutdown.

var stream, currentUserId, filepath;
let sftp = new Client();
sftp.connect({
host: hostname,
port: 22,
username: test,
password: test
}).then(() => {
return sftp.fastGet(filename, locaion);
}).then((data) => {
console.log(data, 'the data info');
filepath = filepath;
fs.readFile(filepath, 'utf8', function(err, data) {
//if (err) throw err;
if (err) {
console.log(err);
throw err
} else {
stream = data;
foo()
}
sftp.close();
}));

    }).catch((err) => {
        console.log(err, 'catch error');
        sftp.close();
    })

**Comment by theophilusx** [comment]
ssh2-sftp-client has no control or relationship to the server other than connecting to it as a client. If the server is shuting down, it must be due to something else.
