### ISSUE TITLE
How to Log the File Upload progress percentage ?

### ISSUE THREAD

**Issue by KrVijay89** [theophilusx/ssh2-sftp-client#89]
Hi
I am able the upload the File, by sftp, but not getting any proper docs, where and how to log the file progress in percentage to show user how mush data has been transferred.

Thanks for helping.

**Comment by sean256** [comment]
This would help a ton with troubleshooting performance

**Comment by zohon** [comment]
sftp.fastPut(localPath, remotePath, {
          step: step => {
            const percent = Math.floor((step / fileSize) * 100);
            process.stdout.write("\r" + `${percent}%`);
          }
        })

**Comment by LMJayasundara** [comment]
this works for me in ssh2-sftp-client put method

``
import Client from 'ssh2-sftp-client';
import throttle from 'throttle'; // Import throttle
import progress from 'progress-stream'; // Import progress-stream

const sftpClient = new Client();
await sftpClient.connect();

// Determine the full remote path
const finalRemotePath = remotePath ? `${remotePath}/${fileName}` : `/${fileName}`;

// Convert the received ArrayBuffer to Buffer
const buffer = Buffer.isBuffer(fileContent) ? fileContent : Buffer.from(fileContent);

// Create a Readable stream from the buffer
const readStream = Readable.from(buffer);

// Optional: Limit upload speed (e.g., 1MB/s)
const throttleStream = new throttle(1024 * 1024 * 2); // 2MB/s

// Create a progress-stream to monitor progress
const progressStream = progress({
  length: totalSize,
  time: 100 /* ms */
});

// Listen to progress events and emit to client
progressStream.on('progress', (prog) => {
  const percentage = Math.round(prog.percentage);
  console.log(`Progress for ${minionId}: ${percentage}%`);
});

// Pipe the streams: Readable -> Throttle -> Progress -> SFTP Put
const uploadStream = readStream.pipe(throttleStream).pipe(progressStream);

// Upload the processed stream to the remote server
await sftpClient.put(uploadStream, finalRemotePath);

// Emit upload completion status
console.log(`Upload completed`);

``
