### ISSUE TITLE
Integration with React & Webpack issue

### ISSUE THREAD

**Issue by KrVijay89** [theophilusx/ssh2-sftp-client#94]
Hi,

I trying the integrate this package with react and webpack.
But while bundling its throwing the error of "process.binding is not supported" in 
node_modules/ssh2-streams/lib/sftp.js file, can any help to resolve this issue.

**Comment by rkaw92** [comment]
Hi. Literally the first line in the README says:
> a SFTP client for node.js

This module will not work in the browser for various reasons.

**Comment by KrVijay89** [comment]
Hi, i am trying to build a desktop application by Using ElectronJs, And if i write plain javascript with ElectronJs that time package work fine for me.
But when i combine the package with (Electron+React+Webpack) that time, its throwing error, 
while Webpack compile it.


<img width="1064" alt="screen shot 2018-10-10 at 6 41 08 pm" src="https://user-images.githubusercontent.com/6492570/46738565-29ae3200-ccbc-11e8-9401-3a0b7f75903f.png">

**Comment by jyu213** [comment]
@KrVijay89 when run with Webpack, It don't support Node.js module default, You can set `target: electron-renderer` with on webpack.config.js which mention on [document](https://webpack.js.org/configuration/target/#string)
