### ISSUE TITLE
connect method documentation 

### ISSUE THREAD

**Issue by theophilusx** [theophilusx/ssh2-sftp-client#95]
The ssh2-sftp-client.connect() method takes a second argument of 'connectMethod'. This does not seem to be documented. Looking at the code and tests, it appears this can have a value of either 'on' (default) or 'once' and it looks like it determines weather once or on is used to attach a listener to the 'ready' event which will set the module 'sftp' object to the sftp object in  the module client object. I'm guessing this is done to provide an easy way to test that a connection has been made and to make the code a little cleaner by allowing tests of the form

    if (sftp) {
        ....
    } 

It isn't clear to me when you would want 'on' rather than 'once'. Also, the function adds a listener to the this.client error event with 'on' rather than 'once'. So a bit confused, could you clarify and perhaps add to the documentation? Also, as you are just adding 'reject' as an error listener, do you still need to add another reject listener in most of the other methods - isn't a single reject listener on the client object error even sufficient?

**Comment by dvlato** [comment]
Hi @theophilusx  I see that probably as part of this ticket you removed the reject listener from most methods.  In our use case, our code  is hanging forever as the e.g., list method never completes the Promise when the connection is lost (we could detect that with the previous "onError handler" that's been removed).

Are we doing something wrong? What's the way we are supposed to deal with connectivity issues after your commits on 16/10/2018?

**Comment by rkaw92** [comment]
@dvlato Hi, fellow user here. We "solved" this by adding timeouts to literally every library call (using `when.js` and its Promise wrapper's `.timeout()` method), which also alleviates connection loss detection problems present with this library. This is not optimal, but it prevents indefinite stalls due to "hung promises", which we were experiencing before, and seems like a useful failsafe in general.

**Comment by theophilusx** [comment]
The new version has better handling for error events, so likely fixes this issue. Another approach would be to add a 'finish' listener. For example

```javascript
let client = new Client();

client.connect(config)
.then(() => {
  client.on('finish', withError => {
     console.error('client exited because of errors');
    });
   return true;
});
```

The 'finish' event is raised whenever the client socket is closed. It is passed a boolean which is set to true if the socket was closed due to errors.
