### ISSUE TITLE
how to persist file transfer when internet is off in between

### ISSUE THREAD

**Issue by anubhav04** [theophilusx/ssh2-sftp-client#96]
I am using ssh2 to upload to sftp server, in between if the internet goes off I am unable to reconnect the same and resume the upload from where it was left.

**Comment by theophilusx** [comment]
I don't believe that the underlying ssh2 module has support for resuming a download/upload. Quite a bit of additional infrastructure would be required to achieve this.

**Comment by theophilusx** [comment]
As the underlying libraries don't support resume, this module is unable to add such functionality. It would be better to build this into a higher abstraction which possibly uses this module, but takes care of tracking and resuming partial downloads.
